---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: backup-weekly
  namespace: storage
spec:
  cron: "20 4 * * 0"
  task: "backup"
  groups:
    - backup
  retain: 8
  concurrency: 1
