---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot
  namespace: storage
spec:
  cron: "20 3 * * 0"
  task: "snapshot"
  groups:
    - backup
  retain: 2
  concurrency: 1
