---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.18.1
      sourceRef:
        kind: HelmRepository
        name: kubernetes-sigs-nfd
        namespace: flux-system
      interval: 30m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    master:
      resources:
        requests:
          cpu: 23m
          memory: 64M
        limits:
          memory: 64M
    worker:
      resources:
        requests:
          cpu: 15m
          memory: 64M
        limits:
          cpu: 300m
          memory: 64M
    gc:
      resources:
        limits:
          cpu: 100m
    prometheus:
      enable: true
