apiVersion: v1
kind: Secret
metadata:
    name: metube-oauth2-proxy
    namespace: media
stringData:
    OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:fpu9SRn8,iv:T6+hu0YTnlUJztR/Ngsx7b8P4DFHMtRJcB77QGmSLyc=,tag:g1EdOSrQCgmmru1sivOT4A==,type:str]
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:pBK7BQJjoW2nr22UvdXeMP5eSFH1M0VZnmrqzDBXYFg=,iv:gXHqbWelUPhNnISSn+xZDBWux0mQUkBhQeZZYXOagkg=,tag:ubAE9f40kEhMV0jVg2PMig==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:e4BTzM5c9MdGSjTqFq9Rls1v26Dc65Bzrt/1lid3GAc=,iv:K59Kn8BEHmAn8E+F2ma8CzR4QYVsjz100RQQdEQFDVU=,tag:Ka+GncftQqsgZzwUl1819g==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6OTd5M0duRjN4Qjh4aWxt
            UGlkNFB5V09qV084RDdpOXk3ZXB5UTZFaVVVCmwxNENjak9tUWNNUDNWa01sWWJT
            QkFKbU9VM2EyVWhTYXRqRXRUcTdCSjgKLS0tIGw2VzE5SXNJdC9sZFZReGRESTlM
            NjZBd2d2Si9tWVY3RTZnZlJDVk1sMTQK53BW8reGj83xxmxdymD2yLUkglY1TzWF
            GvrgBeA/iobaxsVRqnlKSNkBDWpzsE2MrDrXhRrSoTtohNQC2N0SOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-18T10:54:44Z"
    mac: ENC[AES256_GCM,data:aK8IcpaijTgT4SI23Y5EdZO2Zvao4NsTiACsNPS+jVSQJJRxeXkXctRB5T3TEFndHCbGa3xuRF+9VsbqGSLODE8wIQZKAFvOdaO13yXODnSVbm1/HCgIUzcXsXhDhKGO+W/mHugMXUHNpOyXiaKY7P+Gjhq62QR71NB9KiQ8WfU=,iv:01FwghMejW5TIyKQ+Y6G4bwGQ6f9xC3+eRy/F75Y68A=,tag:+gWfPA827tX3gzsi/qo3iA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
