apiVersion: v1
kind: Secret
metadata:
    name: metube-oauth2-proxy
    namespace: media
stringData:
    OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:htsRL9Np,iv:A2581CAs7Ue2aM/jEoVd+hKZSFGawgfNZ7sMUY5hdG0=,tag:6Ca9MJADdpqb9YvUrPP7gg==,type:str]
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:ycRIJl8rVlfJOD7BjwxUrGvE/etk1zNlpnjenLjgvBo=,iv:13v7nSsa5g3tGM3AQe0OJEDl2Lk9K1DaYGm+IGDa6tw=,tag:LTRFIlIQatyQx5hfDstVgQ==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:QPK+1WM3EXPJCc/5bc8GwRZxkNMm1Hi79TiVRvDlEx9KjwhD5ccpr1jcRl8=,iv:anfukYemaYwX+IJY9JlxuHAtmdRWZnmUMrKIjLxwuyE=,tag:w9dQa/T34hBH32leT4qcLg==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvU2tuYzlFL0ROSE1VWERD
            VjJ0ZHEvckNuTEU3L2RNSXFGeUJaS3c2aXlRClR1ZmFrd3VDZmNyVkk2RnVxdktt
            d3U1NXlOMlM4empPenhDRTRQUGpUUGcKLS0tIHh4Vi9hdXJveVlLcXhIMlZvRkpq
            LzRadzZ4VFJ1MHRCSHlVSGgxQm95QU0KG9ooLgd1iHDzEkrMh9AQQftOvMsH3YF3
            bRKdkvLK5oKoj/rPY2BGzLl76mH5Hs/sp9ZnZx9Gnvwzirkx1ADZVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-18T10:12:22Z"
    mac: ENC[AES256_GCM,data:F3R0L4swpyIlh1+dEfc9GVUN9DjpF7NvGounTd3IBn2Q/vFqvn6EY0VaezewLUmneRLFyVDxEVLgOp0keh+Cw3MwzaQ8x5bobhRm3LSA0+TfEESMECGqcLZ5kpv46CEcDQkNVLwtvmlGje7iDr1uGaTWoHxAAugKX+HtIrNnOW8=,iv:3jQaTo3wQJhlGalSQ3ma+udRzgcuwtlNMEEFW41a2WQ=,tag:8POgp71xZMqDvl1XV73ZRw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
