---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpn-gateway
  namespace: vpn-gateway
spec:
  interval: 15m
  chart:
    spec:
      chart: pod-gateway
      version: 6.5.1
      sourceRef:
        kind: HelmRepository
        name: angelnu-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/angelnu/pod-gateway
      tag: v1.8.1@sha256:690b6365728fe9012ad4cdfca38334992664596513dca187d1b93d2025205776
    addons:
      netshoot:
        enabled: true
      vpn:
        enabled: true
        type: gluetun
        image:
          repository: docker.io/qmcgaw/gluetun
          tag: v3.34.2@sha256:96892b27c27653244df1ab8dc1a9e1f719db7fffee755ce20eb81e2dce663f59

        envFrom:
          - secretRef:
              name: gateway-vpnconfig-secret
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        networkPolicy:
          enabled: true
          egress:
            - to:
                - ipBlock:
                    cidr: 0.0.0.0/0
              ports:
                # VPN traffic
                - port: 1194
                  protocol: UDP
            - to:
                - namespaceSelector: {}
    podAnnotations:
      configmap.reloader.stakater.com/reload: gateway-pod-gateway-configmap
      secret.reloader.stakater.com/reload: gateway-vpnconfig-secret
    routed_namespaces:
      - media
    settings:
      VPN_INTERFACE: "tun0"
      VPN_BLOCK_OTHER_TRAFFIC: false
      VPN_TRAFFIC_PORT: "1194"
      VPN_LOCAL_CIDRS: 10.0.0.0/8 192.168.0.0/16
      NOT_ROUTED_TO_GATEWAY_CIDRS: 10.0.0.0/8 192.168.0.0/16
    # publicPorts:
    #   - hostname: qbittorrent
    #     IP: 10
    #     ports:
    #       - type: tcp
    #         port: 55633
    webhook:
      image:
        repository: ghcr.io/angelnu/gateway-admision-controller
        tag: v3.9.0@sha256:4e169da5af107a9c6c784d3e03c89da07fad45f18358ab5b7177662df12d955a
      gatewayDefault: true
      gatewayLabel: setGateway
      gatewayAnnotation: setGateway
      namespaceSelector:
        label: "vpn-routed-gateway"
