---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpn-gateway
  namespace: vpn-gateway
spec:
  interval: 15m
  chart:
    spec:
      chart: pod-gateway
      version: 6.5.1
      sourceRef:
        kind: HelmRepository
        name: angelnu-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/angelnu/pod-gateway
      tag: v1.10.0@sha256:d728eac85f750b37c96a0dafd038561ea4b8035857802be1128ea9b19c61e181
    addons:
      netshoot:
        enabled: true
      vpn:
        enabled: true
        type: gluetun
        image:
          repository: docker.io/qmcgaw/gluetun
          tag: v3.36.0@sha256:011bea4f0743864d4eda5a569217a6fe18e3a52f5d6df31b4ceb9f7763bfbf6b

        envFrom:
          - secretRef:
              name: gateway-vpnconfig-secret
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        networkPolicy:
          enabled: true
          egress:
            - to:
                - ipBlock:
                    cidr: 0.0.0.0/0
              ports:
                # VPN traffic
                - port: 1194
                  protocol: UDP
            - to:
                - namespaceSelector: {}
    podAnnotations:
      configmap.reloader.stakater.com/reload: gateway-pod-gateway-configmap
      secret.reloader.stakater.com/reload: gateway-vpnconfig-secret
    routed_namespaces:
      - media
    settings:
      VPN_INTERFACE: "tun0"
      VPN_BLOCK_OTHER_TRAFFIC: false
      VPN_TRAFFIC_PORT: "1194"
      VPN_LOCAL_CIDRS: 10.0.0.0/8 192.168.0.0/16
      NOT_ROUTED_TO_GATEWAY_CIDRS: 10.0.0.0/8 192.168.0.0/16
    # publicPorts:
    #   - hostname: qbittorrent
    #     IP: 10
    #     ports:
    #       - type: tcp
    #         port: 55633
    webhook:
      image:
        repository: ghcr.io/angelnu/gateway-admision-controller
        tag: v3.9.0@sha256:4e169da5af107a9c6c784d3e03c89da07fad45f18358ab5b7177662df12d955a
      gatewayDefault: true
      gatewayLabel: setGateway
      gatewayAnnotation: setGateway
      namespaceSelector:
        label: "vpn-routed-gateway"
