---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vpn-gateway
  namespace: vpn-gateway
spec:
  interval: 15m
  chart:
    spec:
      chart: pod-gateway
      version: 6.5.1
      sourceRef:
        kind: HelmRepository
        name: angelnu-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/angelnu/pod-gateway
      tag: v1.10.0@sha256:d728eac85f750b37c96a0dafd038561ea4b8035857802be1128ea9b19c61e181
    addons:
      netshoot:
        enabled: true
      vpn:
        enabled: true
        type: gluetun
        gluetun:
          image:
            repository: docker.io/qmcgaw/gluetun
            tag: v3.39.1@sha256:6a8058e626763cbf735ac2f78c774dbb24fec2490bd9d9f7d67e22592cb4a991

        envFrom:
          - secretRef:
              name: vpn-gateway-pod-gateway
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        networkPolicy:
          enabled: true
          egress:
            - ports:
                - port: 1194
                  protocol: UDP
              to:
                - ipBlock:
                    cidr: 0.0.0.0/0
            - to:
                - ipBlock:
                    cidr: 10.0.0.0/8
                - ipBlock:
                    cidr: 192.168.0.0/16
                - namespaceSelector: {}
    podAnnotations:
      configmap.reloader.stakater.com/reload: vpn-gateway-pod-gateway
      secret.reloader.stakater.com/reload: vpn-gateway-pod-gateway
    routed_namespaces:
      - media
    settings:
      VPN_INTERFACE: "tun0"
      VPN_BLOCK_OTHER_TRAFFIC: false
      VPN_TRAFFIC_PORT: "1194"
      VPN_LOCAL_CIDRS: 10.0.0.0/8 192.168.0.0/16
      NOT_ROUTED_TO_GATEWAY_CIDRS: 10.0.0.0/8 192.168.0.0/16
    webhook:
      image:
        repository: ghcr.io/angelnu/gateway-admision-controller
        tag: v3.10.0@sha256:a8ed630613de277244dfe203cd11d05905d7eeba8d8c41e399b02ee9a847b2f5
      gatewayDefault: true
      gatewayLabel: setGateway
      gatewayAnnotation: setGateway
      namespaceSelector:
        label: "vpn-routed-gateway"
