---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vpn-gateway
  namespace: vpn-gateway
spec:
  interval: 15m
  chart:
    spec:
      chart: pod-gateway
      version: 6.5.1
      sourceRef:
        kind: HelmRepository
        name: angelnu-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/angelnu/pod-gateway
      tag: v1.12.0@sha256:8b35b9ebe2be4dfdce44934e298ab196bc59dd2a47ec5f62423e6b573ae94a6b
    addons:
      netshoot:
        enabled: false
      vpn:
        enabled: true
        type: gluetun
        gluetun:
          image:
            repository: docker.io/qmcgaw/gluetun
            tag: v3.40.0@sha256:2b42bfa046757145a5155acece417b65b4443c8033fb88661a8e9dcf7fda5a00
        envFrom:
          - secretRef:
              name: vpn-gateway-pod-gateway
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        resources:
          requests:
            cpu: 100m
            memory: 40Mi
          limits:
            cpu: 175m
            memory: 100Mi
        networkPolicy:
          enabled: false
    podAnnotations:
      configmap.reloader.stakater.com/reload: vpn-gateway-pod-gateway
      secret.reloader.stakater.com/reload: vpn-gateway-pod-gateway
    routed_namespaces:
      - media
    settings:
      NOT_ROUTED_TO_GATEWAY_CIDRS: "10.0.0.0/8 172.16.0.0/12 192.168.0.0/16"
      VPN_BLOCK_OTHER_TRAFFIC: false
      # 51820 is for wireguard
      VPN_TRAFFIC_PORT: 51820
      # 1194 is for openvpn
      # VPN_TRAFFIC_PORT: 1194
      VPN_INTERFACE: "wg0"
      VPN_LOCAL_CIDRS: "10.0.0.0/8 172.16.0.0/12 192.168.0.0/16"
      VXLAN_PORT: 4789
    webhook:
      image:
        repository: ghcr.io/angelnu/gateway-admision-controller
        tag: v3.12.0@sha256:6f6ab596afd5fef0ca4648eadfb21cd37ba86fa5afa8b85edcc072976a61fbed
      gatewayDefault: true
      gatewayLabel: setGateway
      gatewayAnnotation: setGateway
      namespaceSelector:
        label: "vpn-routed-gateway"
