apiVersion: v1
kind: Secret
metadata:
    name: vpn-gateway-pod-gateway
    namespace: vpn-gateway
stringData:
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:gUmCjfa+,iv:UIQy/lU70HCB2EVs00k8c2gmS07gW/Vuqp857J6Cdag=,tag:d/fAbQwJ4eHVi7ahNRE62A==,type:str]
    VPN_TYPE: ENC[AES256_GCM,data:3ZZlcUiElt9y,iv:s7MlflX7294k0Sl5UKxOvTp23pzeWVHlZHgRpzgHbe0=,tag:+jlmsfb3Vq9Lnsqwdw0Reg==,type:str]
    VPN_INTERFACE: ENC[AES256_GCM,data:wR3c,iv:/+IzAgNdpFmWGPCagmvzdpVv3QN8HyVKDo2uUpyBTxI=,tag:VAhDmbbzd1Eq332wO9BBfQ==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:42p5nI6Y5W1eK/cvQri1tl4cTDCp8ZRNkMXDtFFo5dU8mR8WGPkMHpJWUXg=,iv:7pkzR6Wxq2ZvnTkVMhnm6eH3U6WAHPG/rfwSNIUOPY0=,tag:yuF6MTzBqRzn/Zr/qVZELA==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:9aa5UCb/oiO4SZNxnCQ2xuuXUUuJt2hTZSnc5NALBrbu9IhEB7zpfvRWJdw=,iv:Hov5tI9L+MJutvv49OovYnxK6VcqYKrzsc4a0zuRWtA=,tag:wHQxE489Jppr0yHl080y5A==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:LkXoKqR26Rfa/woiB33o,iv:DMX4+4ohdRMpu7kJxBUs0ckzDuoxYMhX256RZPBG0PM=,tag:16Mhu57DRNXEDvdp2QnJvQ==,type:str]
    WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:bacJnFYuVkuzNFF4NCQ=,iv:gZ53UlqpB+U2nlwsDgqPJ+P4vdkf0FNwkwYWxUUVf/0=,tag:46p6E1JUCJxjmetHtzLo3Q==,type:str]
    WIREGUARD_ENDPOINT_PORT: ENC[AES256_GCM,data:XBv7kw==,iv:+8UiaCSizv7zW7BTyDe7edec0GLSih/JJg0YmdHMcHw=,tag:cK1VTVZJSZo6kb3+WB4YbQ==,type:str]
    WIREGUARD_PERSISTENT_KEEPALIVE_INTERVAL: ENC[AES256_GCM,data:Bgk/,iv:fSR3e/PZZAkmAx9TLqGdwyDDPh5mQaU/3GxUGWoYc04=,tag:nFI+ewJ/pxQdYpSZyod2kQ==,type:str]
    #ENC[AES256_GCM,data:IjrHhGkOSekY,iv:upKYl78x7NKWGH0EwtsaFs2KqSOfE7wq8oKqNnYSYOs=,tag:aGJWc+KvzbB33Mghqjt7dA==,type:comment]
    FIREWALL_ENABLED_DISABLING_IT_SHOOTS_YOU_IN_YOUR_FOOT: ENC[AES256_GCM,data:/F5L,iv:KtKpC2MW3DBLJPxwu7LTuuEPOGISLIllZYHjxXr8zzU=,tag:uPFceDGFYbAM68j0DXBt6Q==,type:str]
    FIREWALL_DEBUG: ENC[AES256_GCM,data:Ric=,iv:hrP9sowMPu/f5tSwzw1J8Zg4G3qR5nffdo637hXuUX8=,tag:ZCHrfpd6m9kt2vmzIqqDGA==,type:str]
    #ENC[AES256_GCM,data:CQiKMQ==,iv:mWB6eqtkccp4rbaF81d8QHQj09054pH3cK7pBu7RTOg=,tag:kED7PzawkN/fa3Vn00HvTA==,type:comment]
    BLOCK_MALICIOUS: ENC[AES256_GCM,data:bbZ5,iv:MRDctllvRL40kOIEPuLxwdr1E/1e++IFyGljyVQhmFc=,tag:EkAEhAa9ctVznGiMaCBjcg==,type:str]
    DOT: ENC[AES256_GCM,data:gUB2,iv:v6xQJML4PCgKah6KWvzI6XZX1o1hRzOtJxrph16njHE=,tag:YZFGph/jn+oItzyaesR4xQ==,type:str]
    DNS_ADDRESS: ENC[AES256_GCM,data:/hjnCmfmaMM/lA==,iv:YJecRoHMdlc1n+mdCZTFG7s1i1wCDKMLiOb8Y8/NQr4=,tag:cVQ6fiANNh6mPBmMTkQWOg==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkTWdoRFhHd1FZOFl0SWdS
            eFpCVm5VZ0F4Mzh4TDhDSVZYeTN6M095Q24wCnEyTzZwTjUyQzhOWVRGbWo1bC9h
            UUZndVlRVXYzSFlTMFYzRzdaMEg0YU0KLS0tIDdZQlIxa1hYQWMxVzlPdGh4RXIv
            dERXUm40NUlybldRQ01GUEFNVWVHMVkKu1XxOSuTNRFads7G+FjY5pem0zf0P8OU
            QCzyB+MfzAMx++fA8bqX8byxv8xd0RM8JMts+p7NgXy9KJ2LfTJGfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-21T23:17:45Z"
    mac: ENC[AES256_GCM,data:pc0Cd0REvY7H1ScgDICfzuX/oeQG50CCN/ipFkPF9CQrS3r8E4mcNyOplPUgxs60yEV7iK5rmbdKyPi5mlPLegPRwbN4kS83Kug39mPhz3K9frJ9wMEBS1nwC+3u+v/UvCegM4KCK1lS+JLdak33XH968QylnDapNWoe/M5CifY=,iv:sh09YV9q1j97vEZyHZY1z2/TbHQb8AEnllhImFWRwx0=,tag:aax8ctGlJKU553jGHjFGOA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
