apiVersion: v1
kind: Secret
metadata:
    name: vpn-gateway-pod-gateway
    namespace: vpn-gateway
stringData:
    OPENVPN_USER: ENC[AES256_GCM,data:qxMw9so+Fpc=,iv:bJ5tJ4PxnZ5M9z5d6zbQLiKXq2D1X03tFTnGFOKtKKM=,tag:HLun9s4e4jtKFhG5tBDf1g==,type:str]
    OPENVPN_PASSWORD: ENC[AES256_GCM,data:ARn4hTRy44eCBQ==,iv:KYHSJ15IesVoObN2eKex3a8hveoHKuHfd6K+ysyIagU=,tag:sbKClZ+ZDVc5F37yERhIUQ==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMM1p3OGkrbzB6d0ZRVHFO
            Snh2Q2w3RDBNRjZYdFh3RUxtS0xERnZPRkY0Cnk4U2U3N2dLWEpVemt3Vk96VXZ0
            MkovWlZqaXlmM3I1V2UwbHlTdDd2MGcKLS0tIG5YQTJkT0VZeTlrbUtGRVNHQlQ5
            ZUMydDZsWEpRbjJya0JRblhwZ2tvZEUKk8+vOjRuU5+FSYT7cwx4Xp7r5ErjbB08
            2jolWusks3H7WIvJLEWg+tv7hNMA9FpBgdJtF84BcStyecWN/iqepA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-02T06:59:13Z"
    mac: ENC[AES256_GCM,data:5yvZ4b+xKjDqCmBVqBEo4PhbpPZziWintqSbcMVibXnh6tql7Q/H6GZ1qKVIM/1aoh5XnkWcQ6a/SDfZQC1TGUPYaz1ZL/39b/V0aOUzzSEfXlLfWL+SvoJlev8UfWSutbf4TAFDpLT6ly1bBwnStfMyKm8VRSc6Tu/aFQC77Ks=,iv:AiMFsGskgx73BhbVMDdplnM2l5TZkxVqiygQSaWiX9U=,tag:h6fwHIv3K885g9tsBFxm+A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
