apiVersion: v1
kind: Secret
metadata:
    name: vpn-gateway-pod-gateway
    namespace: vpn-gateway
stringData:
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:yFBMIMgcuQ==,iv:Xj2IERmMpc3H5TywVgYh0cJtYyyXwOJS4aFuQ+ulHuc=,tag:hvgIjvw6XGOKvNQi0titRQ==,type:str]
    OPENVPN_USER: ENC[AES256_GCM,data:2yLPYmjtlsFXL+SMyCIUVbNfeDuAa15H,iv:NmSUVm/5EpqK8SbQTTaP11j6UDPTVNDtDTZi6Towh+U=,tag:ArcOGxzvrUUvDAn33ssgHA==,type:str]
    OPENVPN_PASSWORD: ENC[AES256_GCM,data:pY/Fmm3EL3xH7ZYgKhw5psfLj7o+IygJ,iv:oTrXLnthYI9jEzsq2NkxmRoUCq21TQrerK1ydw79Ev0=,tag:Y6agqmY32H6yxNKDmOAoDw==,type:str]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:1V0YfyRB,iv:q2RQzzuoBdsxeFOBvXsMZz4o6m2FdmkVPB6lVh4EYuE=,tag:8ypEUrPs0Rj++Yycr9+RBA==,type:str]
    SERVER_CATEGORIES: ENC[AES256_GCM,data:+89q,iv:rigBPGHktm/0pxd68gBNvXrcss5bXLvi8KbFIugy8MY=,tag:DmLIl2QD3+UPin28cnKXpQ==,type:str]
    VPN_INTERFACE: ENC[AES256_GCM,data:CAPdhw==,iv:8OvJJMYn4DcGvlX2NwcCQZlePW5bu3850pjknrqx85g=,tag:bR4RMrV+Lt/ZjW12GDNQwQ==,type:str]
    FIREWALL_ENABLED_DISABLING_IT_SHOOTS_YOU_IN_YOUR_FOOT: ENC[AES256_GCM,data:flk=,iv:i7DsBhR6RIFuVMS5SaL2et/NZcUb12I1/XLxjRq5NbA=,tag:Ox+CZOcAPMFDmItBQ1oBGw==,type:str]
    DOT: ENC[AES256_GCM,data:aLC7,iv:+ej4wzPC3+pK+1I8QyjZwWkkcSwQq412l3MEgJC624Y=,tag:Azbezl6rYCJnBHXakH135g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyN1NvU0dhcElvenRTa1ND
            TGhtZDNybjJKNmwxZk9USGZNdjVQL2xCeHprCkM5NlJzUERlV3dsOWh2K1pXcndE
            SVh1eGR5alB2aE5WeG96dllqeWdmTWsKLS0tIEtUeFJKY1E2M0dxZFoxTTdxV1Js
            d0I3LytZQ3NTQWd3YlZNU0dOb0RZb00KMHJVzY7lWT5qmATVsw2AT3Rwlxoh/lJP
            ijh4L4e6/lNJej+lB5Oc8O8OpBEthlUck4TUFuKN/oGDpVdVyMCtDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-23T21:58:39Z"
    mac: ENC[AES256_GCM,data:JFAcBzAjqdMuPNFefvEqmlow36XH+ZLzTaasPkx/arBW3ebmkUlHWQ3kVqua05akrDvgZpIt0iUKy6+SkMoYy2GXCm6v+2TiE8IXwacBcMRiO+AUe9D8OmPcU7hgBZ2Xeui8YZE5wyMz0BFKmvAYsW0KcIaESxUwg2zH09wGnj8=,iv:JEl0QFz41MVO5Azm/FM5G+URO+H/1eb1f4hGQmhExRk=,tag:7Ol93DNwoM5wRxMtsgGuqQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
