apiVersion: v1
kind: Secret
metadata:
    name: gateway-vpnconfig-secret
    namespace: vpn-gateway
stringData:
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:UhEY6n7pPg==,iv:+/yrPd/93S2Je4vpNXZWiQ7r/FVyoa2zanSyBxWu230=,tag:sqlIonHakynqCsMYZeMftg==,type:str]
    OPENVPN_USER: ENC[AES256_GCM,data:oKIU/67VJC4GG22herZ22T5vSbur5BTm,iv:Zpi9a6nHnrhzIVQC8JXWwcaDuGCzuPPNcQbKVhlcGOQ=,tag:T+4UV+DqAN8ZUkAeWLOryw==,type:str]
    OPENVPN_PASSWORD: ENC[AES256_GCM,data:O16d8SnKl42OxBff5AQGxJc97l5gfnzp,iv:9Tw6Ur8EIEGogn9W7oFUJmC+GyVELZ/Yq7NKoNxQjcs=,tag:dFRuR4hHkuIYav13JfAKSw==,type:str]
    SERVER_REGIONS: ENC[AES256_GCM,data:EX1HN0WK,iv:DiKftxqftC7j7Vl+tPqZJVilVk/Xdlley0/4WFLFSus=,tag:pl4O2JADBHi5IRvceLB0Kg==,type:str]
    VPN_INTERFACE: ENC[AES256_GCM,data:c0BLUQ==,iv:ok05QVU61Wog+3rNY8ukvPiYMMfDUILYfG4K3N17WP4=,tag:B2cjvRqV2n05v68byPSR0g==,type:str]
    FIREWALL: ENC[AES256_GCM,data:wrhM,iv:4kQd5eSX+75wMONd97hxqLwR32pxQE9HM9aCc/myax4=,tag:9VNfMW4DlStgRZXLIlHbig==,type:str]
    DOT: ENC[AES256_GCM,data:tyeD,iv:PQ+4bfPVfl48xRtGXVqSrXBzUVcYg1IaoSxjxQQxlUE=,tag:c6IFZb5wyS0mBP1udZqZyA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOYzZJM3BHNVRnRW1CdDg2
            b2c4dWhhQWdUVVcvVFF1RUtwMjIrSDRHRTJ3CmxJclh5bm42V09KVnNBRE5adnV6
            TGRKOG1TMWM5UytNUVNUVzNlYWlOS0UKLS0tIEJhbTlQcWpnWmJrL2RuaDIyYmhr
            Qks5ejg1Zkg3QUtBYnNFcFNVYXRxNVkKrI8HpxKeC73b9lYRnrgqAy/5djSgNrUF
            oI5f2+KeDIVC/KfrpZhXOvX0hn6JXfg32g8ah0XlvyHuLYArf2Qq4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-28T09:31:15Z"
    mac: ENC[AES256_GCM,data:8SOQ2Ivnr/H1Nqdmv2oV+7H7OQh6QS85q0eHm27HxSQOcD7MRASny2nZKBBoxK5eRpSCCk7JTop8DIVc2CLTI0lU/y4ZBtI9b1aYT8fqeMPGQPawKyAU2Q0EbgC8FhzK4Rxasv3M0vpL4WY1VpLroV+47p4bBwYq3cWj4NET/cw=,iv:u7+O3++7sMBVdcUNjsYdRXdw/WYznUOCP1C+mzuLZbE=,tag:zVWqXjeMI/cXpfsYMyczBQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
