apiVersion: v1
kind: Secret
metadata:
    name: vpn-gateway-pod-gateway
    namespace: vpn-gateway
stringData:
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:YKsvB0Q0,iv:uNa4pT8IlViEJH96gSi+U0yaEmy5l7xOZ0JBx6wL5/k=,tag:esyG89slXz2a/l7nY+p2rw==,type:str]
    VPN_TYPE: ENC[AES256_GCM,data:VxpPYNtZJhep,iv:b4gfPLPCGG66oePvO47YtwhaQuN4rEeGNEmCzAD1TPg=,tag:kw5yTf1wCfnJTgNYkC4wrA==,type:str]
    VPN_INTERFACE: ENC[AES256_GCM,data:bjSM,iv:ebV85rYtCgzErAIMOK1PhMD8421LKK9gsuV2QokuNXA=,tag:fYklWEIufquBDlQb4IqabA==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:fBopQdLcbgqp+ZdyKw4BGz+hzVoCOOufLoLWwsMNgcTDgZJsSqf8DcWq5Dc=,iv:xGVgf0BGX3u7HdxP48TiMwMvdzA/yKU54jRmr3/5mdg=,tag:7btghL0QN0aXrt8+JD4nQA==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:S81+n1E9BEyZrqm9VJuFo3gzwUH3gnv257B7GJQSaoCeva6UqwZUlgTHAFc=,iv:i2enhp2B5mUbNzoaxrvdZEORt+Jaj7/ySVOYmVLBvPI=,tag:Ypwf5reHtyjKlCOYB/ofaQ==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:M17UWUvRxuo9DvR1oO6E,iv:N8C6f/BvHtaaYwWCjJDpErKTumwmqaKnHb8Pa4GGsBU=,tag:2oRU5jqkEpLxq60c8/UUrQ==,type:str]
    WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:FClVi6751tll9p9W8uI=,iv:EnPWYFNbYNfOIQ5MybdVvpqpKzB0+7YOw/z0RDOvJg0=,tag:gV4YuwHnDr4LIVCupis99A==,type:str]
    WIREGUARD_ENDPOINT_PORT: ENC[AES256_GCM,data:rRE/xw==,iv:doh4+fufvUIE88yAaXaYuC6dc//ke8KhRHeyFYc6wVg=,tag:6Uvr956f12DQqyqYh9Y1lA==,type:str]
    WIREGUARD_PERSISTENT_KEEPALIVE_INTERVAL: ENC[AES256_GCM,data:YpZW,iv:n4Ew7pwgkjxGYx27Lk6jdXuAZd7rGGyMfIUWDzo8MKE=,tag:tD1W0/Qk37Z+8Y+7FR23yA==,type:str]
    #ENC[AES256_GCM,data:MGN4EC8qufux,iv:0mQJF40mZF6L5nSLrNPHZCSQPS0dfWW6J+Shz4pidhE=,tag:oSZzql5J+L/L78tsKZ+ApQ==,type:comment]
    FIREWALL_ENABLED_DISABLING_IT_SHOOTS_YOU_IN_YOUR_FOOT: ENC[AES256_GCM,data:kVvk,iv:Y3NEhKSPyLeMqq00AbJEB7wFywsO0t5IOW00ty8L74g=,tag:llrz36hm5jYaaIT4dlo4sg==,type:str]
    FIREWALL_DEBUG: ENC[AES256_GCM,data:lmA=,iv:UP+XdI67iWaKVpaHXFfUsR0D8x95Ybt/eNqea6oGJ+0=,tag:QOgvx6SNz6EieNY+1T7+3Q==,type:str]
    #ENC[AES256_GCM,data:8kEWeA==,iv:syHID7jKNVoJKRIV8TM5/bk8qe17R1xYlIkmmHZQlz8=,tag:Lg8zE+xj4lTrc4+7aEH+ww==,type:comment]
    BLOCK_MALICIOUS: ENC[AES256_GCM,data:JjJH,iv:m2H05qZLNhEKts6yfM/GTxdI6Ekgy/TZqwZbQuu26gw=,tag:t26vdt0z27B4VmGZSj9rjA==,type:str]
    DOT: ENC[AES256_GCM,data:CrYy,iv:M7kWygPbQlw9zw0Cq0/vF0r/cNbEZpVnJkXXg6NAlwc=,tag:e34w9AmTSQsdNcK6RC8xlQ==,type:str]
    DNS_ADDRESS: ENC[AES256_GCM,data:pWTXsBFNmyPs4Q==,iv:uRCkUgfH1GSZy9nV8RVulBa2LCvnaJQCiJawlMY+SEM=,tag:0wlqohHzdycDCztzbZGhtw==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuWjhjRUZ5b01TejJlM3BI
            S1lvckVuT25IcWtic2lheS90bXdyK3pCS2ljCjJBWjRhcjYvQk51Rmp6dTA0WTFv
            dXE3OXR6dlJlcnFXNWF1MFBMbjFvTVUKLS0tIEVSd0hyWXZVM25objdDRjg3clBF
            ckRJV0x5ZWQ4K1Q2NUxjMVZta29vRG8Ky/w26cJKxHWXFVG+pZxWGfspZQSlmtZs
            K5GCbJhtn5rQBj3cI5zIVfI2O4NDYtSlQhUqEFTVJIA+UZ5lbNuYPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-21T23:59:59Z"
    mac: ENC[AES256_GCM,data:nUBLnEblnexxMBqcPAPHzKSn2ciik7Eljxc3PjzYaiMFU8OH3utiWcr6dGNVWLCl97BK5fRN3KZfeShqxxt/kfdtnq+GVSpcOJldoR8bye4cvX56Fhbp0wW+ntVp8/D0I+vcR6owNpmEgvdUKLgJUbnUS7uHaEBXQwfkt7UuDXg=,iv:wDVqRVt8cQTWai5w2D0/9QSm80qr/mGJSqt4eDuJp90=,tag:6U5BqfrsF2K/0gR0XXSTiw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
