# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: rustfs-secret
    namespace: storage
type: Opaque
stringData:
    RUSTFS_ACCESS_KEY: ENC[AES256_GCM,data:U3J9bnWBD8jdwno/xxqHbv9TjR1CWStM,iv:Gjq4wKL24GnxNKutG3IitBJzOenNQEUbMaX4TSRiBqA=,tag:9hzx61KXMswFAz6MmVEdyg==,type:str]
    RUSTFS_SECRET_KEY: ENC[AES256_GCM,data:VDl2fN+V7MdvziE+VBTSFxtQ1GjD6Bo6Og4ZcbCcgUBiDXOKeB6skg==,iv:l5QTtIt156E/B9DHuO/15kuBb7ypnzlYk9AITI/VA/g=,tag:DXaFkdnOp8tXo9/OhPMgHw==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSDA5MkJ5V2htcEJROHJn
            WCt5VnZLUnZscWZhNnUvckpDVnJLRlFBV1hRCngzS1BINkVDRzZ0c1Mybm9VcUhJ
            YWw0NU1TbURjUm9XZkI5eVB1MHovc28KLS0tIHJxeHRIWkw5MU5XWFZsQWxpT2tB
            YmdlVXZBWUtoT1NjNHpXck1HZitaSFkKkWyqNtFNuvlkCwKGy0LCIzqlG2hEon98
            8t++uU5JWfNYiofyvIJsTZC2wiVgMSG90kA7/kXXJxkCxtja7Qi+cQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T06:20:02Z"
    mac: ENC[AES256_GCM,data:5mkRf25IpditnzE6oKWpVteYnI/mtnGrKRHwztlvfBCIq5eqw2Ry6GSNbd2KfbGjXQjyzcR8Db7AZloAHk/TQpS26Y2AC8nyMaf+g5iGymrCVQER3m72U9XtdwkkmBnZYPhLPMqmohqXoRvshFqj9/n43+GHBludtvE+KQsfvx8=,iv:6spbEedvqPQpcowI8VA4A949MTScRdDCo6o5VDCGRwg=,tag:o0TDAVBx47nATStt2jVPEw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
