---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: kanidm
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: kanidm
  validation:
    wellKnownCACertificates: System
    hostname: "auth.${PUBLIC_DOMAIN}"
