# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
    namespace: storage
type: Opaque
stringData:
    RUSTFS_ACCESS_KEY: ENC[AES256_GCM,data:tCEY8rNjOEyfqQ==,iv:eZj/KZGF+/VtrydscgYlrxicM0Pq6hXVXnbGfTxPWWI=,tag:cU8AqGpszN2sLUsWwZf+KQ==,type:str]
    RUSTFS_SECRET_KEY: ENC[AES256_GCM,data:i6WTOwxJJB9hOju5M50I8+EYUHNIiCtgxeHeRu5Hdis=,iv:shImS+lHW0rTYKnHAefFbAFZ2lJITdlxU3XcSIc+2MQ=,tag:jWJ5Ru8MnyRpWGa3NPjJfg==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTzlOOWZHZWNkSXZlZjYx
            U1JzUnBEOVBZT0FxaXN2SzdIYm1raklFRFdjCmkrb041cTA3Z0F6Smg3bUN6Vi9S
            dWtKbm94anQwS1dwcW1oUk1TUW9PckUKLS0tIEpLVVkrelhhK3ZLWnJmL3BoSkNB
            bmJKbTVDQ01CRi9kbjFoSmN3TEY5Vm8Knf4+2cn7heHIa62suffW7W274WNzBp+6
            vELIIo5GTJ9wCa5aA6g+ebYkQDSukhhCN6iGAh+xXpDw7tbIaDZR2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T19:21:25Z"
    mac: ENC[AES256_GCM,data:0H5v/hdllekfGJXb3JR02NaJO+jMBdzYYVWoXM07rSsV30E8yG++MYVxA8Cd/ItKoEoLDdM3xDGc/THHH6PBGda4ufriuHuSO67Loi+nJAAVQzRZKpNW10AsScNfc+8FTj/yRSOYU1/Ozo0VvqPWhg6J7pxwfJ7+HNhy+4Z3BZ0=,iv:kPI4bUSOdtWja4PR8T2hxPS+tGCivy5+PU4y9K0eca4=,tag:QxKxwCihY3APwt0nhBoLAw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
