---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app home-assistant
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/home-assistant
              tag: 2024.12.5@sha256:638e519c874a06389ce6f03e435dd80a6697e8692eac88b459775839410f3439
            envFrom:
              - secretRef:
                  name: home-assistant-secret
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 15m
                memory: 375Mi
              limits:
                cpu: 400m
                memory: 650Mi
          code-server:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.97.2@sha256:6ff0e9cf5a553b3961ece200be75e21e8c887ed0ae28a7c28213722dccf74b0c
            args:
              - --auth
              - none
              - --user-data-dir
              - "/config/.vscode"
              - --extensions-dir
              - "/config/.vscode"
              - --port
              - "8080"
              - "/config"
            env:
              TZ: "${TIMEZONE}"
            resources:
              requests:
                cpu: 50m
                memory: 375Mi
              limits:
                cpu: 200m
                memory: 950Mi
    service:
      main:
        controller: main
        type: ClusterIP
        ports:
          http:
            port: 8123
          code-server:
            port: 8080
    serviceMonitor:
      main:
        serviceName: home-assistant
        enabled: true
        endpoints:
          - port: http
            scheme: http
            path: /api/prometheus
            bearerTokenSecret:
              name: home-assistant-secret
              key: HASS_BEARER_TOKEN
    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          hajimari.io/icon: mdi:home-assistant
          nginx.ingress.kubernetes.io/proxy-body-size: 1000M
          nginx.ingress.kubernetes.io/proxy-connect-timeout: "20"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "14400"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "14400"
        hosts:
          - host: &host "hass.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
      code-server:
        enabled: true
        className: nginx
        annotations:
          hajimari.io/appName: 'Hass Config'
          hajimari.io/icon: cib:visual-studio-code
        hosts:
          - host: &hostvs 'hass-vscode.${SECRET_DOMAIN}'
            paths:
              - path: /
                service:
                  identifier: main
                  port: code-server
        tls:
          - hosts:
              - *hostvs
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 3Gi
        globalMounts:
          - path: /config
      ssh:
        enabled: true
        type: secret
        name: code-server-hass-secret
        items:
          - key: id_rsa
            path: id_rsa
          - key: known_hosts
            path: known_hosts
        defaultMode: 256
        advancedMounts:
          main:
            code-server:
              - path: /home/coder/.ssh
                readOnly: true
