---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app home-assistant
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    timeout: 10m
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
        containers:
          main:
            image:
              repository: ghcr.io/home-operations/home-assistant
              tag: 2025.10.4@sha256:25a113a6d3e42ac66ba6b4172300b8c9a66f91e707a03cab5ad454910ca37eeb
            envFrom:
              - secretRef:
                  name: home-assistant-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 8123
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 15m
                memory: 375Mi
              limits:
                cpu: 400m
                memory: 650Mi
          code-server:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.105.1@sha256:2d48970bd2084aa34a522d772b6a437981ea80407465b3bf7958553985c570e1
            args:
              - --auth
              - none
              - --user-data-dir
              - "/config/.vscode"
              - --extensions-dir
              - "/config/.vscode"
              - --port
              - "8080"
              - "/config"
            env:
              TZ: "${TIMEZONE}"
            resources:
              requests:
                cpu: 50m
                memory: 375Mi
              limits:
                cpu: 350m
                memory: 950Mi
            probes:
              liveness: &codeserver-probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &codeserverPort 8080
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *codeserver-probes
    service:
      main:
        controller: main
        type: ClusterIP
        ports:
          http:
            port: *port
          code-server:
            port: *codeserverPort
    serviceMonitor:
      main:
        serviceName: home-assistant
        enabled: true
        endpoints:
          - port: http
            scheme: http
            path: /api/prometheus
            bearerTokenSecret:
              name: home-assistant-secret
              key: HASS_BEARER_TOKEN
    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          hajimari.io/icon: mdi:home-assistant
          nginx.ingress.kubernetes.io/proxy-body-size: 1000M
          nginx.ingress.kubernetes.io/proxy-connect-timeout: "20"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "14400"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "14400"
        hosts:
          - host: &host "hass.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
      code-server:
        enabled: true
        className: nginx
        annotations:
          hajimari.io/appName: 'Hass Config'
          hajimari.io/icon: cib:visual-studio-code
        hosts:
          - host: &hostvs 'hass-vscode.${SECRET_DOMAIN}'
            paths:
              - path: /
                service:
                  identifier: main
                  port: code-server
        tls:
          - hosts:
              - *hostvs
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 6Gi
        globalMounts:
          - path: /config
      ssh:
        enabled: true
        type: secret
        name: code-server-hass-secret
        items:
          - key: id_rsa
            path: id_rsa
          - key: known_hosts
            path: known_hosts
        defaultMode: 256
        advancedMounts:
          main:
            code-server:
              - path: /home/coder/.ssh
                readOnly: true
