---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - ./helmrelease.yaml
  - ./code-server-hass.sops.yaml
  - ./hass.sops.yaml
  - ./prometheus-rules.yaml
configMapGenerator:
  - name: loki-rules
    namespace: monitoring
    files:
      - HassLogs.yaml=./loki-rules.yaml
    options:
      labels:
        loki_rule: "true"
generatorOptions:
  disableNameSuffixHash: true
