---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/prometheusrule_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: hass-rules
  namespace: home
spec:
  groups:
    - name: hass.rules
      rules:
        - alert: hassComponentAbsent
          annotations:
            summary: Home-assistant Component has disappeared from Prometheus target discovery.
          expr: absent(up{job="home-assistant"} == 1)
          for: 15m
          labels:
            severity: critical
        - alert: hassDbConnectionFailed
          annotations:
            summary: "High rate of database connectivity issues in Home Assistant"
            description: |
              The error rate for SQLAlchemy errors from Home Assistant has exceeded {{ $value }}
              in a 3-minute period. This indicates potential connectivity issues with PostgreSQL.
              Potential causes may include network disruptions, database server overload,
              or configuration changes. Recommended action: Check the database connection settings
              and logs for any anomalies or error messages.
          expr: sum by (app)(count_over_time({app=~"home-assistant"} |~ "SQLAlchemyError" [3m])) > 5
          for: 2m
          labels:
            severity: critical
