mqtt_username: ENC[AES256_GCM,data:G6yMCIcT4bVAY6o2ow==,iv:MRDFT9r7Xm/s7J/9uomF3MRMMb9zfXOTpKdxyij/AJA=,tag:2VP9L1uRJZ33+SN7eFl+lA==,type:str]
mqtt_password: ENC[AES256_GCM,data:dCjIKt7UT4OMV9O5gA==,iv:Ac71x9pFJAlKlJWBhbmcexSu6TMM4YOtwt40+d5o+aY=,tag:MLGuQK1oA2wzKoaFKTLyCA==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBadnlqNExFMVc5ZmMyYzJT
            Q0tTSmlkQ1F4TDY3RlRrcWlPT0VxRG1yK1NVCjVtN0xaY2czYWlmRWVvNkJyRHdx
            WFlzWGwvSFVJWExudC9tNUgvUFd3bHcKLS0tIGZ3NGNwdXV0ZW5tWm1nM255dllN
            S2w5WVVXc0Q5MzEwVWRUTWZtYTdoTG8K8CKAbBmNASfojkVBzBAkNK2ZOk7+sT3R
            byHYyDOdDH04FJk+BxjSByUqm6OIUxVhcoAfj02o6P9+HbupwqpKfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-05T07:47:02Z"
    mac: ENC[AES256_GCM,data:kdh9WAxzsZMdrkXxo587Gd3pBc9nCJ5aq6v8/ug8TA90gPkbPuvyzPyIYRYuUiWHnZW2TMMxHjYEpUOTO3Ibu9B3Et9k/1ZhsaiVIvEqJiOrWnG+Ey3Ja4+vfn15O7Ds3t/qQbJzgKrHaNJpu66dGtmzp6udot7FYAbFUvqLD74=,iv:3f73oNeAAig66l8yWVCLPdtEtWP1mYdXOX805JnxbSM=,tag:f4LdT2ryJWgksEzFtAmXfg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
