#ENC[AES256_GCM,data:pq2At+LTcek7ZcWCjsElaxMYcrhS+1OhBJ24tmjbRC8HEpsQlysQTdRtvWbIGUMBOz8ku7mzXKVZDjYII196solwKQQTC6LSoE6kjG8GMw==,iv:iMXlIM+IdPqvEI9wML0hr7Cg90BlomZMsmc8Ek2gI4w=,tag:KsmIVQg3H17Dbta4s0Pi+Q==,type:comment]
#ENC[AES256_GCM,data:/0NoL+AmYn1yZaI+ijJJroZNKLxmbNWOGyQ4QjcJ93y99FLMz4+VQlN3CZIplFuS/Saixsqhr+wp4iGqOFRb,iv:ogj5HylFYOnPxvvhybWHidC9jzAX7vONbgL/gWq/lcw=,tag:C/6E55FO7kBjBWdZX6yDKQ==,type:comment]
secret_domain: ENC[AES256_GCM,data:7zm/YLvCnqtd/Uef+eT6ZuAKKUqb+2ftEA==,iv:JsuKZQtBkNQhrBIn7q178XTwUUEToKOaHp21h2/WLtg=,tag:aaMNco52fYxxjNSpXfqasg==,type:str]
#ENC[AES256_GCM,data:3RQlIQWQq0zInlUjbUJbXQZRl9hCBSGd/wUris4TGhjp7G7qUdd07l7ExBidyqM8ThPpDsj6G9m51pG+GSXfApFS/l39EmTb,iv:6j93Zd7h5oZ0p8lkPcUwTKaqjy2+UjSVjDQoNsSfXQ0=,tag:MLHLqgmGu10Ni6gy3fZkSA==,type:comment]
#ENC[AES256_GCM,data:NkUNLRaZ3jKICk2m1OkuHWc099tQg4xOhqN+It3RejAHyIWSN7OQrUMoaWJp7h21A3JPa8bgDZdBwKdbKfpEG3I=,iv:bPYYnrCH0kt4F8Fsi54Wh23WbsZ9zshof0woOv5ZZDM=,tag:aipqE7u9ugJ9rTKAntwkLQ==,type:comment]
#ENC[AES256_GCM,data:HpHr6quJl9I8odbtIxTD8LZzivl+Vpz7aNGkisOe8K/theCOsf72dPV6loBYf1JYvxtTc0u9EFspG+OGEYs8,iv:RGqznmwx3dMWz0CtBCCMhokX/T6gkgvW51kQTc1qp64=,tag:18/WnbM8sQI7Vw3WBZDmoQ==,type:comment]
public_domain: ENC[AES256_GCM,data:6nCOwrXVCzHxD2KAFssYd9c=,iv:U68mDq4HcuhSi231ifdm7vYED4Jwhg/7cXp0q5J4DQY=,tag:NAnDnqVwxhBLAG1OcEMZGw==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMeDBXOUs3T0MzbkJCY0VT
            R21JTTVMa3dMOFp4SlQxRjkrQzBhMlU2Tm5vCmVLbUhuVW5rNEhleVBGMVRYeXd6
            blRnakt0V2lBOTQzMzM3Y1l3NmQ0K2sKLS0tIFJZWDR6elVDdHRqZGh2Uko0K1RC
            L0FtMWJnVUwyQ3pFWiswMjBuVHZKVE0KZPNnH3tblRUSh0kpqkkWfJRBVV8uTYb7
            FK9r4ZTYVklSzYWJCgpXoAEu9uFYmyKvmsodtOCogRVaZ1CsIw9N/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T12:11:58Z"
    mac: ENC[AES256_GCM,data:SKPAU5NOK2pUhypKMRjcL17Oljc5IP+bLhgjWgPfmpt5t7NMTYet4SzOjWCktuq7hTasiHzviURA1GiJcYko5jUT82SEZQ1Z/z0z10N5b/4oWre6FmcZGxYqUGPzI9ZcGA5+o0cZjkUW0ep8ron9nM7kpYapT8VImXGyqiANsMk=,iv:jMXMPSUW250RTcRkd+uNHKlqcLrrRUp56fZMO8ShQGc=,tag:hYIovU0JJBkvz8oQplzAvA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
