---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
spec:
  interval: 30m
  timeout: 15m
  install:
    timeout: 15m
    remediation:
      retries: 3
  upgrade:
    timeout: 15m
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      n8n:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          app:
            image:
              repository: ghcr.io/n8n-io/n8n
              tag: 2.32.3@sha256:c848162d17a99af20792358e4b075658ad00a80301419415305d66d10888d3f2
            env:
              DB_SQLITE_VACUUM_ON_STARTUP: true
              DB_SQLITE_POOL_SIZE: 3
              N8N_RUNNERS_ENABLED: true
              EXECUTIONS_DATA_PRUNE: true
              EXECUTIONS_DATA_MAX_AGE: 7
              EXECUTIONS_DATA_PRUNE_MAX_COUNT: 50000
              GENERIC_TIMEZONE: ${TIMEZONE}
              N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: false
              N8N_PROTOCOL: "https"
              N8N_PORT: &port 8080
              N8N_HOST: &hostName n8n.${SECRET_DOMAIN}
              N8N_METRICS: true
              N8N_LOG_LEVEL: info
              N8N_LOG_OUTPUT: console
              N8N_PROXY_HOPS: 1
              WEBHOOK_URL: https://n8n.${PUBLIC_DOMAIN}/
              N8N_EDITOR_BASE_URL: https://n8n.${SECRET_DOMAIN}/
            envFrom:
              - secretRef:
                  name: n8n-secret
            resources:
              requests:
                cpu: 5m
                memory: 128Mi
              limits:
                memory: 2Gi

    service:
      app:
        ports:
          http:
            port: *port

    serviceMonitor:
      app:
        serviceName: n8n
        endpoints:
          - port: http
            scheme: http
            path: /metrics

    persistence:
      data:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        retain: true
        size: 10Gi
        storageClass: longhorn
        labels:
          recurring-job-group.longhorn.io/backup: enabled
          recurring-job.longhorn.io/source: enabled
        globalMounts:
          - path: /home/node/.n8n
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: n8n
          gethomepage.dev/group: Productivity
          gethomepage.dev/icon: n8n.png
        parentRefs:
          - name: internal
            namespace: networking
            sectionName: https
        hostnames: ["n8n.${SECRET_DOMAIN}"]
        rules:
          - backendRefs:
              - identifier: app
                port: http
      webhook:
        parentRefs:
          - name: external
            namespace: networking
            sectionName: https
        hostnames: ["n8n.${PUBLIC_DOMAIN}"]
        rules:
          - matches:
              - path: { type: PathPrefix, value: /webhook }
              - path: { type: PathPrefix, value: /rest/oauth2-credential/callback }
            backendRefs:
              - identifier: app
                port: http
