---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: descheduler
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: descheduler
      version: 0.32.2
      sourceRef:
        kind: HelmRepository
        name: descheduler
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    replicas: 2
    kind: CronJob
    cronJobApiVersion: "batch/v1"
    schedule: "*/15 * * * *"
    startingDeadlineSeconds: 200
    successfulJobsHistoryLimit: 3
    failedJobsHistoryLimit: 1
    ttlSecondsAfterFinished: 600
    timeZone: ${TIMEZONE}
    deschedulerPolicyAPIVersion: descheduler/v1alpha2

    deschedulerPolicy:
      profiles:
        - name: Default
          pluginConfig:
            - name: DefaultEvictor
              args:
                evictFailedBarePods: true
                evictLocalStoragePods: true
                evictSystemCriticalPods: true
                nodeFit: true
            - name: RemovePodsViolatingInterPodAntiAffinity
            - name: RemovePodsHavingTooManyRestarts
              args:
                includingInitContainers: true
                podRestartThreshold: 100
            - name: RemovePodsViolatingNodeAffinity
              args:
                nodeAffinityType:
                  - requiredDuringSchedulingIgnoredDuringExecution
            - name: RemovePodsViolatingNodeTaints
            - name: RemovePodsViolatingTopologySpreadConstraint
              args:
                constraints:
                  - DoNotSchedule
                  - ScheduleAnyway
            - name: LowNodeUtilization
              namespaces:
                exclude:
                  - "storage"
              args:
                thresholds:
                  cpu: 35
                  memory: 35
                  pods: 20
                targetThresholds:
                  cpu: 50
                  memory: 40
                  pods: 50
          plugins:
            balance:
              enabled:
                - RemovePodsViolatingTopologySpreadConstraint
                - LowNodeUtilization
            deschedule:
              enabled:
                - RemovePodsViolatingInterPodAntiAffinity
                - RemovePodsViolatingNodeAffinity
                - RemovePodsViolatingNodeTaints
                - RemovePodsHavingTooManyRestarts
    service:
      enabled: true
    serviceMonitor:
      enabled: true
    leaderElection:
      enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
