kind: ENC[AES256_GCM,data:uH/+PKJs,iv:GYYdiYh1YYfxwS5PWdCHgHri2T++jaVPPcyub38CV2Q=,tag:Xk4HcC3jR/SYg0euP1LeEw==,type:str]
ansible_user: ENC[AES256_GCM,data:NSI1Sws8,iv:ZmkeVgXzdAtuqPH/HevanQK1cd+31IdkXGu6UgPyfxo=,tag:m9/pgFpnSv8BAd+Hv4YljQ==,type:str]
longhorn_host: ENC[AES256_GCM,data:Hg5oQfAEJw==,iv:LWW19O93hpG47zo3JkcMDt51Wb1oj1tc2SAIQGRNI0I=,tag:VfRIqmfiOQB1lyJMqadMPw==,type:str]
longhorn_user: ENC[AES256_GCM,data:RjPfLmI=,iv:JOaBBGeW4X1mG4Z8CHUeS6zSSYTAYe7swv4DjKKHnk8=,tag:66XXdJHO5OLe9Tn0tcr9gA==,type:str]
healthchecks_tokens:
    longhorn: ENC[AES256_GCM,data:6lvLtxiVSW/5W0e63GcNZwtqbSmyeIqcW/c8o0+4AbEt0a7Z,iv:TpROP0bMm2w5+VyZS7H+NBJ21VcexygvIIRNUcoHybI=,tag:4hfLY3lq9MMzRIwdbSXtuQ==,type:str]
    immich: ENC[AES256_GCM,data:VG9o0tQkMTOfWpH3yqyhh7XjL8QM25CrdWrpV2/TtAXueIeE,iv:yitA2Zur2D5gsACVvnSrZwBZvo49hOyaKPIUSL/UHXM=,tag:kjbfFq19JjCBOG2w9ZzUsw==,type:str]
    photoprism: ENC[AES256_GCM,data:QI0dtmOUgW3rfrCaz81n/rK71Hn1CpRP5GvBkPk4AWbVqTUW,iv:4kd1IMne9JANhSubISFVsVwt2E7m91XNbE+g3+ARqzI=,tag:d5kXzseaD8geU4GF8T8kVA==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPYWVGeXcxWVdaTEFxeUd2
            cE9hdllPeTQ1dTU3OFg4YUE4OWdVNU9Kb3pzCnpiVnJzQ1M1T1I0UHRjR3Rid3Rw
            cHlUSDhKbmt3NVVrdmJtRVJ0T0NocEUKLS0tICtXZ21IYnFINnBDSzFERUNhN0VC
            UWFGRUh1YnlXNlZycGJYeWVMeXRsTEkKXYkoqz14+UAKK8krsVL/1H03OVDURscv
            PHkApxQ0D7hsIE67ibwpJWa7/srQlMdrGYuRpOO538bwGJ99r87Niw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-21T15:48:25Z"
    mac: ENC[AES256_GCM,data:Ni69Mqy+3Rf/zAtbeoyBML+WGINlILRCWZh9vFoKF2cVjEvCVHJ1nvXtlv2zbThWjOdhreLoeDqqbu9WmD/sDnKlzndTvWjAqkb04iiQJj4Niy61LxzOgtixPM77XUnZSdp/d2TSMj4dbx6Fmj/wpYUeXLtEcNQfId7pMtng6uI=,iv:bJsVGNooPMQuB9bo9eXtOan/MTom3LwrAaYj2n0NLO4=,tag:RavtOxxLf7bRUtyK6Hrhog==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
