kind: ENC[AES256_GCM,data:WEaqBQGT,iv:rj8zYnO2jakELgAIZ82BxrbxP9e9w1aA3+CJNvzG/sE=,tag:CEsnAXT4yXv/YfB/w/xhDw==,type:str]
ansible_user: ENC[AES256_GCM,data:IiI/B7o=,iv:YDXST70uCb2xh1BylbshxniYxTnloSPzBEXYKSgHQvg=,tag:PLTGmwt7RHzCiIVsNCtLtQ==,type:str]
longhorn_host: ENC[AES256_GCM,data:MOCtrKSzLA==,iv:Pe+WnJdq1LEvm8+qhC/l617/IANwa++ccd8zclpaCtY=,tag:A+aRw9Cews8U03lXR00X7w==,type:str]
longhorn_user: ENC[AES256_GCM,data:rhulmqU=,iv:tXF35so+slKS6jKosodJFsxOdA/YNUQpKp4hts3W9ps=,tag:FkV83Mzk4LNkgNSiZEwh4w==,type:str]
healthchecks_rsync_token: ENC[AES256_GCM,data:kMepS6hE6T3Eb28IhIcuysieo+qNevunsMQr1A8kzdzTDnnl,iv:y/cbFtcTLnwZpCsOnulrrhz4FAokC5ipfUB/M3tpH6I=,tag:MWRNg485QJBLsGJsa3iOog==,type:str]
healthchecks_tokens:
    longhorn: ENC[AES256_GCM,data:8bkWCp0S+vKamvlhDkZtPFCi9qI7mF+uuFKYfoHvEykt0L+6,iv:BnAP3lC473Nk+WoYxwqMxzHNN4X5E3mVt9bhGE8z9Oc=,tag:6VE0XtxSwO30YJZgzZi9nA==,type:str]
    immich: ENC[AES256_GCM,data:i8pnLNLRXeaQL3jN3Zw2HnGTkVZB7wTBtgPp21fAxCcfKmxY,iv:MWTSPcKtkW7/hwVStig97fyKGE3xjuCsLsxDX44U854=,tag:6RXkjB6CrNEdgSxLXenGCg==,type:str]
    photoprism: ENC[AES256_GCM,data:Z96rtkae+wnVh566wm+zAwQb94mmWALNALGsZ4B0tv5EdsCY,iv:y3DyMfq5JT4qIY4AVKyQWlWZ572W5fy9v6Ak4CjPsYE=,tag:QD0tplLwjm1pq6AE6Zh7EA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1T0pkeDhIVE9rZ2c1T3F3
            dEJmekZPS0U4ZHBGL25XUWNvb3AvYTBka0dvCkVEN2VJSWpaZ1VFa2UzMGVGN1kx
            a3VDZW1OOTFBaTk2THJkN1FvcWRTcU0KLS0tIElmYXlEZllHT2cwb29oYU4vdUZl
            RHhDMTd1b1VHRGZxUUJ4U3cveFFPVncKBKIp1fmoDYWeL7UoWOqdWfPcXQ0N25PL
            3gpLLmBnDZCKIm3bok/NyRfwseszpxngTViLan+6fzxhGHfkGqmZHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-15T22:28:57Z"
    mac: ENC[AES256_GCM,data:JnIVVkIqBfIUwpQ6E5g4IX4a/A9IgriT8nyz0aqHVAhLptYTvAjuiFwtvxn1KZg6af0XovsPJOldTqyjW76iSkTJdks+kQjQ7Tx/gpAgwlK1Q+BjJU22mZ5TmDW/Clc7N1R9OkAIGhHhQOjlvQ2nulEb1Knqb+zYaxt0bjZRMdI=,iv:PllahkydHoK36mklDj3dLYiz4YPUM82kTMxbzNu+Fwo=,tag:wU6UbC/9kfB91vdna7MeWA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
