kind: ENC[AES256_GCM,data:jnt1cBiJ,iv:z9huyuIQp7QrHaLZCgLtN2soaKrVou3/Gg+t957mvB0=,tag:V+PPTly049JM0Jt8oMn6qQ==,type:str]
ansible_user: ENC[AES256_GCM,data:uhnCGK10,iv:qOrqy7oCRhb/eIYXl7hiGnNLdOArI8v4HgNgYgchCHM=,tag:/A4ZEyYXiQagD0VoiQF9/A==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBObUdEMWNSTVcwaDFUcGVB
            ZlF0emk5M2JId05zQVQ1K0FFeVJCVTdxMjJ3CnIvTmVaTWRNM2RnbzVkTlRNb3lY
            Umg0eEd2MEdKWGFXMFhHNGN1N1lkS2sKLS0tIG5uSzQwbkdCWjB4ZjB6UjNVa2I0
            ZEJRRmlFQ0ZUZEpMZ0Ztbm5IZWROR0kK62iVB18iYqmVfvwPoe7u6UVelWILbj4U
            eq1fycNaGz5/5s56PQqxPqvZOENf3WzUxrdNV13bRJLLz9zQxweNaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-21T15:48:31Z"
    mac: ENC[AES256_GCM,data:KbTfyAHa0azOhekk9G40jv/6Z2r23KD7v/qhH9uqbdg3JZ8kcEAhMTQ52JCxxTRV7v3QqjdD1A2AZURl+1bcd6d14evDaWh8YPdx3SM61aEWjqguEZCURgMB3VuOANlmeVW3OmBTErSngZb4y6QkBV0r1ENfDIx6+454/wy8WCk=,iv:UoRPqgz3GKHMHqw5pgHTbdVVfEGv/hgtTPAJyKWWEdU=,tag:eacszaHpPBMn3Ojk0AjNjQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
