kind: ENC[AES256_GCM,data:E8Rr1CTF,iv:9LUjqKM/M6XeP13igJXD41Lh0lbu7dz8NCqKLhNpCms=,tag:oJsyTL+Wx+njXA2IrWy8WA==,type:str]
ansible_user: ENC[AES256_GCM,data:LNEizIbS,iv:gj/6+oGSYn1445cqmI4SHvz4x3KJ45A8kIzzGiRZfPY=,tag:UxPUqMs7JYHYB/3W6KRoSA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:v7M5jdxKIzp/tg==,iv:WWbiyeqpc9dIwcI1OqnR++pO9raCRAivuAbaRG4xI7k=,tag:fLd7pqqt4o8jx4U8sVmZqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXd0QwVzFQck5qWFF5a1dy
            b1Z2T2pnYkdXdGg3TW5hQnEyU0xsOTNEQ1FFClppRjJPZmhBNWUyMDJXWFFHVUV3
            YjFuUW92a20vYTExekVEcCtVaExVNU0KLS0tIGMvcDhMY2piWnA1RGtqZWtyeVJX
            V24wQ0hLbnliVGlENks3UWFKUmtiY0kKcJ0WzzdeAT2IAdcBNxZWYuuWsyzhUJ27
            8XUs7weZPD03WjfmcCuoCOqHlBDKSPKsNED1bjqw8tbVsawimHwBsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-20T16:27:27Z"
    mac: ENC[AES256_GCM,data:Eu11y4z5RBaK0k7wOG/OkItqPmASNJn1iyy8EKq/fU6dKbQ6p+7kq24QM5Md16X2TCzV9V2TTV2YzPohBRyrubgF/IiVOT3TVV7yoU/Ym6uhaCXqwxEgoew2KDs5oZKZuCFnPhdJpVt4+By1i2p7Ay8rGv0DosNFpaJSc4CcSCI=,iv:cKI+AB0xIoUaN/AADiT6q0iOGtugbO59B6axhQIL6s8=,tag:2eO/fob4SpZcaPnVFNjsNQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
