kind: ENC[AES256_GCM,data:66T6zDl7,iv:eGnCROJeZlINUOdUlsgSQC8wSjMwZgB65jqpZkqwtqs=,tag:5L5btk29IWzCtacr/mh72w==,type:str]
ansible_user: ENC[AES256_GCM,data:Zmz0beXq,iv:7hUW07ZAPCG3+Tj6vggL8mCij+qZV8MbWcPKfoC4xA0=,tag:3Y2mpckdIQqON8mKb5A/fQ==,type:str]
#ENC[AES256_GCM,data:u/mrQgAF+xtISIus76befKJ81kDGXON3RTKoauAxjUZn8lblZR/53qjDUr6PWhVHM1ta3V9hiDcwV3HMpNjVe7KwCk9Egg==,iv:T7apIdZmCNvBMpxCDUHrm0VdcP5kQFTitKMF6q7M3x0=,tag:3f5tS2cOpxYX/CnWR+eXEA==,type:comment]
#ENC[AES256_GCM,data:xxB3cogSkucfNANqLHm/eH2CxATvOmR7qfCGoMcq+LDBSg4yoiSA6H8AnGTnqX1MFKQ0j0hGmourjKwh3cBD8x5MEf+mVHf5ybw=,iv:8Vu16GJUtdDuxGusxE3Fch2/Mt2WvXX0/9ZYjweyl4w=,tag:3LVtQeraZKSVnpSpRy6y+A==,type:comment]
#ENC[AES256_GCM,data:QI3qtyWHv2E7BGwDiT5+ErT3PobOmoqoricvkZyZfjE0pOT2vaNnLkQE2DmFg3RrS6K6RKV1wnieC97QYZxeUaw+tCqHvg==,iv:kDZqLc6g5Eip1Yo71Na4SakpbHSX+r6/rReAnDpaask=,tag:bcW6WgagOGd5tb/CDFDyFg==,type:comment]
#ENC[AES256_GCM,data:W6pFS5SGxRv3iEs8H44mg8qA0ncCHfK1puelBlbRYks=,iv:/1HEyudvMaJcb11JnqtPiPHYlrRG0Cj7Sjmrm0jNgp0=,tag:a32pVvj0efxAPaQjSZhLqg==,type:comment]
k3s_server:
    node-ip: ENC[AES256_GCM,data:7QN4ResjGBlKaZlM+G5m4XeE,iv:eJOKH5Vo1USNpqw76nEIEjOHsArfVM7h9URh4Rv9ARw=,tag:FM7ZqLRdsKtU7RoZTN+CkA==,type:str]
    tls-san:
        - ENC[AES256_GCM,data:ApjOROJEW505osUFt5HUUUu/kKFE,iv:Sl1Lq6D834tNJmlMkUd5Z77pWkAQQI0yhvIt0uTFX4Q=,tag:3P7+LV6dT7r18NacKwgNZg==,type:str]
    embedded-registry: ENC[AES256_GCM,data:1PYnUQ==,iv:7iqGIMEcbnX6NJhspepOb9DaAo0y0GV118Mi6egv53A=,tag:8jJKWOnw5DxkAaDNFPAYbg==,type:bool]
    docker: ENC[AES256_GCM,data:LJS1px4=,iv:SsIl7zNpYca5V0qnFkdxCoir80CgcCvThMiZsMQaAI8=,tag:4iEtpTvtWUbfH6t2rU1EIQ==,type:bool]
    flannel-backend: ENC[AES256_GCM,data:zZDXsg==,iv:y8e3IbnpLCQIFoAO7XUSyNva05z1Z7VauhoR1ozPt38=,tag:mh7aSpfGnM78FIXgwPpOsg==,type:str]
    disable:
        - ENC[AES256_GCM,data:RHBkPBVmtA==,iv:sXiINb5ab4YyRMyzAGqs+aBH8xzOSnlexT+vo139DiU=,tag:Qlv5LnUdK+LAkhzaKMtPbA==,type:str]
        - ENC[AES256_GCM,data:hzldngulNt30F1sM6w==,iv:hkJk9dQfrodg2d2Pwa3wFtlO5FlxDdSZHVhxebYCJnM=,tag:PcG2sz2sq53M3KOy9vYjQQ==,type:str]
        - ENC[AES256_GCM,data:1qMAvdPCb5n8NRRBRbI=,iv:qYbkVW1WHyE94UdKZcNCMITSbfPloA14PWYa2aCGdbI=,tag:xIzBpygiKVomYzWwTxzgqg==,type:str]
        - ENC[AES256_GCM,data:wl4op0wNG2po,iv:HZVABfE214pFGp97Y14izKuxsSkC+ekCKDzdKlGq4Nw=,tag:xOkGlCtSQcI09ovhSdtoLQ==,type:str]
        - ENC[AES256_GCM,data:HPddv8Ku2Q==,iv:BCPIXyRB7XMotAD+Wv2PywJDoNkDSYvFlhrIBBIwtVU=,tag:lrGtgJ6QW6YD9SG4z9AZrw==,type:str]
        - ENC[AES256_GCM,data:OrzLfPcfaQ==,iv:A5fcc5Wtt8799FhB4Ngp9oWJYIqLio4+6YY0gZkMv5I=,tag:P0pEK6gwgbDqZnHOwkfLmw==,type:str]
        - ENC[AES256_GCM,data:qljyQd/eSOloKQ==,iv:Qw8KCu/DY9PM3XULOiMAsAKf1c9fHnPAIOHyvm1auDg=,tag:7FIV8T2hCdhrnrexXx51sg==,type:str]
    disable-network-policy: ENC[AES256_GCM,data:+HVi7w==,iv:WCEDwdKLypNnBLyHJ/2ahenSCb2HCABOjc1dFc4gZLY=,tag:j2FQJnViqYGqPPIHCXnXfw==,type:bool]
    disable-cloud-controller: ENC[AES256_GCM,data:GxGBGQ==,iv:mxhWE+/QX4QtLP4wpxegZOcWP0ycPOQSC+oOtj++E9o=,tag:F4RO0Tg3onavWhIM7gga+Q==,type:bool]
    write-kubeconfig-mode: ENC[AES256_GCM,data:Nrf9,iv:rzGk84s1hmIyobBLUufh9wmc1wmEKaX03+2utGjy8k4=,tag:OrTbSP8xnrBR1WlL7PqhSg==,type:str]
    disable-kube-proxy: ENC[AES256_GCM,data:D0de4Q==,iv:PID3CbMvM4ESHQCMo5SlX/4jA9qQZ8S8wfjpSmv3fmE=,tag:G6D11KPQS7lg7YZjjmrKdg==,type:bool]
    cluster-cidr: ENC[AES256_GCM,data:77QMrTCSqWk2PkbB,iv:/IU0iUmKHrHdq6xejSVi2DeaxhBiqDnlNMrr9s858wY=,tag:SlmDjvI18KmQ6J9g1pU6/g==,type:str]
    service-cidr: ENC[AES256_GCM,data:WTle4+9qJ2ztGzu+,iv:TyRe3icYGCNu/05QwAvjDnMOjkmSBfZ65y+axe2vkE4=,tag:44j0tr7RpLzgNO5hPDWbyg==,type:str]
    kube-controller-manager-arg:
        - ENC[AES256_GCM,data:4XrHwYrxF8vTTSUrBljp5WlDscM=,iv:8iarEtOBfmDsToo69+u+rbmH+Tx8R8cZErYqVo4a+n0=,tag:9fieVNPCy+lYPEYmwRVl+w==,type:str]
    kube-proxy-arg:
        - ENC[AES256_GCM,data:hJbep9H3Mte0+K7uzZAR/fV8mOEEIjWSTVvMSA==,iv:my8+0MnSv98DnHi7qtWUurxFEX2+6ESRDDTiRTESAmw=,tag:UensclVi65a8579dK9F6aQ==,type:str]
    kube-scheduler-arg:
        - ENC[AES256_GCM,data:/hv/03f1zKXO4DMJzvlKFNirZOc=,iv:+ZR+U7fqMItMdXxjevPRXroNqKYz7VcyV1VAD1dOqtQ=,tag:/A+jzdZBOTdKifoBgJEKdA==,type:str]
    etcd-expose-metrics: ENC[AES256_GCM,data:9j2xOA==,iv:9R6EBdBrUrSZpPSBArXvrKNCos6eXOI28oZsPmyabrc=,tag:tBrYspAikmCAW5QJdYMRnQ==,type:bool]
    kube-apiserver-arg:
        - ENC[AES256_GCM,data:ZfI/o2ftGILY6G6i+FLJiA/Ryw==,iv:/4vkHQp22MBRhTag/2FSTBWwlYG5hItLKxU/T8BsygQ=,tag:6HWyBBWrJsKpN/4u/mp4eQ==,type:str]
    node-taint:
        - ENC[AES256_GCM,data:VYKJ3YU/gOyJAPRsa/hgAC41XIHy4LAjdDFHK5zLtNj4w96stWOt9g==,iv:iJn0HxTfkhB8icjhXeq3rTw/VOdeU+PGkowFOfYegwE=,tag:RG4ArRxihqVPUC4X/Vr4Mg==,type:str]
    kubelet-arg:
        - ENC[AES256_GCM,data:uQsZozrebnKV4LGyiWk8TmAVO4hGFc1FZNkY28aJ10fF,iv:aP+nRLHImpsnO/EHZC3/KQLeMg3zVepQAE1jv792TCw=,tag:URgMB64qMsVclPciDO1u2A==,type:str]
        - ENC[AES256_GCM,data:21tmok+DNCDNoa6V4X0A/HL3qtJY0pUyTf8Ggspqxtw70wO1+A==,iv:1qKrHhWLe5Z9j5gTJ22lqaMfwS9AebVh+L2xsXlb8wg=,tag:jn36Z2aXSCFTmYeJHx3oQg==,type:str]
        - ENC[AES256_GCM,data:s5SHZ3Ii94cbSU5mFvFjVT41jmiJD7Av5w==,iv:n514ftROty+vjiww3Y35dSkjGHnpX3gIBvncJlT3WIU=,tag:pTnGwXYD/KVDKqCzvGJIGg==,type:str]
        - ENC[AES256_GCM,data:Mq2T58dVwSa/MSTf9MNvP+rKUZlAPTkdfhQ=,iv:pJIGmQNkFsQ7qViUOYXn6Mf/aCBcAjYYm01xahrbTUs=,tag:TqXC3jEvIchyU+3sA1A//Q==,type:str]
        - ENC[AES256_GCM,data:db9wum8VIm+5ZN7omi7LUjsBKpFfus8f+8PuVPhWZle2J9Z7rgyNBSuCX2H2cUXqWXecxCSoHzS7,iv:a3Q1woXrkNOlmdtJEuWadMlwhk5lW1FeX0NP2vucV9Q=,tag:ThwspEeYWVUQLLB7ldy3EQ==,type:str]
        - ENC[AES256_GCM,data:ddw1aXfuFR0i9b5Qbm3pZJ8TtCa3BOk6RX1p1uz8kGAWcHWxAM/bdwEsxd+cLibTY9TiISkLqmsh,iv:1cnzzzQ7h7uwaaNDVHNSp+rIJktsD6JNgD/WiCVQ61U=,tag:eHWFOIWK5V/97xLuEmCFJw==,type:str]
        - ENC[AES256_GCM,data:cLX9ZzxD5sDYEQXqz5tL+vqraaJYEfFIyzRVqIhhRaEhFnhQwOhgT6gITPYpYlWOP/mZ+7t/sftGHFJFICk9D6zM,iv:3JCumiYw4+Yu1yKYZ9ycLuls5qESo9JdZ39tooWihjw=,tag:JXbFrFPqUPnf4tQAEcnT9A==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAya05WMW9SSG1TLzBVWDhh
            THZIb3dFNldZQzI1MG9OeU9SWWdHb1BHWmcwCjJtNmFQM1grdithZmEzN0tHdk9l
            RXJQeXZBSkdBVmw5TkRENE8zVjl5MjQKLS0tIG9oYkIwb05zemhyclFIMVFhaU1o
            U1BKSU03REo1UmNvNVhrVGZoelQxOVUKT2Y7yahXhpKzPyzrtXvL2YLXSkSpOPX9
            Wfu7zP4Kf+oMFlDTYGBVw9eXZDWNP3qOR0ler1yLkw8/+T2E9Ne9Gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-21T20:51:56Z"
    mac: ENC[AES256_GCM,data:n6kpTV4WfqEYgS2uLDnlPkGtqG0qmuIidl3q8hdtUhlmsu0VPIA7Iu8e6aS5y4vtTmN8FcU1XJT5qgd/RHL/n7WgSlS6alA5ynE0/XnTBOhzBjqTc1/ockuNIr+hW4QrX2Gx2xnKCO6tMsQenM7Hr4rb3O6rmV3fz/jd9eQR2ME=,iv:zwIH+uaVOip8Pk40xsysLza3dGQyiljQ3tZQDQRdwUE=,tag:aoGOLvhmXYvjE9iCZG8FPw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
