kind: ENC[AES256_GCM,data:xss+P/jW,iv:DeXXyJMxvgjNyIXJ82o25oNX8Xqmys/VL3+mFGMus2s=,tag:5P7uHZKQbYTMJm621FWXyQ==,type:str]
ansible_user: ENC[AES256_GCM,data:d3yiMD2y,iv:gcaFo0vzRRuUrcBunMID2H1FJQXydCqSD0w/gglNRBg=,tag:meoviNkj1hyj0dDq+FNXbQ==,type:str]
#ENC[AES256_GCM,data:Qaonqa3ngBM36SecLETp84YhFLZ3tApQNjhUz6NlvcdoV/B6N5x2n9MKJiLOVf8bazResI8xOYzlP8KDyesA6n4SGE24lw==,iv:Fxs+tyfOV9VQWBqngEVW9pV1C5ogu1H6dMHqDQFjK0U=,tag:LYdB6Z71Pi3o07KhW7/e3w==,type:comment]
#ENC[AES256_GCM,data:68liZKLYlDNChoN8aeHi23feoUDT9BNyq7Lz9Bd3fvN0d29qGXJkJlB0SOOevCXvlzGyBqg3ATMbmBQzPAWsQJcjuk+lhMb+Mr8=,iv:v8ROeZN25t2vbinwMjQ6KD3SRYFbKv4iR4TBIpcTwu0=,tag:pU93FX1HgmlCBiG5MAXbog==,type:comment]
#ENC[AES256_GCM,data:FvL8S6JT+NU0DtwfK2s2FOHqYq86trCmxyhqNtIWfEdQWOYDYgvpN4ej+Jsu8ICLRXW64c5+POZOiPKGgLgKJWBJs7IgkA==,iv:rhaG+fyi6fS/skIardhObnh9Qya6LWdEaRmzY/FPmR4=,tag:V+6h9e95n65GqbAokZLY6w==,type:comment]
#ENC[AES256_GCM,data:Z/01ONXWupipXXsSH+p0Ul+GGXA22kvx8MSj+WYkVZA=,iv:SAnthGh+WVjI/QvMQTsHCfgFiB6/IzGz99sEGxrrl0g=,tag:ZgLkMDngR67zabSGATOmlw==,type:comment]
k3s_server:
    node-ip: ENC[AES256_GCM,data:jGYCOElkCv4rrgz46SOqf4fR,iv:QgpGgtc3Ot7bHM9L31eoShkk8PdgBET5GlPE0gfeUe0=,tag:3YRBNhzrveBet9/LeoaohQ==,type:str]
    tls-san:
        - ENC[AES256_GCM,data:8ErBR/cvixlQcwXnf5DB2mxDxJWs,iv:if4zsuptXfTADZAPscuv+qhgW8YTfRe2M95SFxvM80U=,tag:WAz0K/AT8x/5ziLwW7G9+g==,type:str]
    embedded-registry: ENC[AES256_GCM,data:bZUZlQ==,iv:1dkpKdSd9JmLS49kJFyc7y4X3raBYhL5cJTqEJQD1OE=,tag:QNlwN8h6+kcTCEprqNp5AA==,type:bool]
    docker: ENC[AES256_GCM,data:33uRqWQ=,iv:OL2QD/os21kKb++z7jUoVehcwXF2ULwZUiJBBTyYdUk=,tag:6bnDjxpu49KasFZp3MLmRA==,type:bool]
    flannel-backend: ENC[AES256_GCM,data:fc3OzA==,iv:WN67+z9B9eycDwK/xPpK6fZbMbO3nBfwGwXsVLCBNOk=,tag:9ptwmG9R7Q+B39DUmaAkPA==,type:str]
    disable:
        - ENC[AES256_GCM,data:FttXJg1ntg==,iv:W/XDIkXIwLhLwFR5p+wIL5jE6FxX9JO4SPIiztDjL34=,tag:ig54rkg9vGvrexj5agWqAA==,type:str]
        - ENC[AES256_GCM,data:6nhXs9GsO5rBAWyKfQ==,iv:OrZNSiRqGN9SYAl09yrgQD8nSYv6RdGiVQKyMpuqc7U=,tag:Qj2pfJhV103/q5KT+MWKxQ==,type:str]
        - ENC[AES256_GCM,data:LnpActms4kLMQDmIL9g=,iv:M1Oktp5EpCiTP4bP50Rt0uPgxIFxecFabxCpHW8Chj4=,tag:1mFHrn9UTCNKQqu6aAFi3w==,type:str]
        - ENC[AES256_GCM,data:11CN3otANFAC,iv:XLfHD7qGBVpSGSOA0564dRTyd1FgkmS4rhdKRhzDIjU=,tag:5+qfXYPPPQKWCdSXuBUq7g==,type:str]
        - ENC[AES256_GCM,data:jbs+Ns7UvQ==,iv:tcfwequpRZOs0UM8iR6ziKCGp6lMpiMGxf3eZ/0GjqM=,tag:MLrngUBU0keFEw2zBwEu3A==,type:str]
        - ENC[AES256_GCM,data:Y51epVpkpQ==,iv:RZnDBmu47R10hbd8Y+q3EdgSMXSefDUBl5xSeu80/3w=,tag:E6Kq4Xtnx24lLewa1L77XQ==,type:str]
        - ENC[AES256_GCM,data:GH8sxzea3PRRiA==,iv:fTwsqzR1kdg3uVlI5lyTNqUzKu6+GeGMX4L42cTVjDI=,tag:mXgUDeueFs1/9Me0XDCFcw==,type:str]
    disable-network-policy: ENC[AES256_GCM,data:IXM7ig==,iv:EyJQkmUuM8tyPiWeGW1QeZ5FSMzp57s/69Sdvk3uzaM=,tag:Vwy57m2hYE2ejxDNdiN2Yw==,type:bool]
    disable-cloud-controller: ENC[AES256_GCM,data:vTc3Zg==,iv:cOE6VvLElJZG2htqmmQjYCC56rWhz7ItjhFEdq8NWL4=,tag:6mcm71KeEclfVMO2AuGQjA==,type:bool]
    write-kubeconfig-mode: ENC[AES256_GCM,data:pJcN,iv:/VYaHh3zTguLRFW/5byh6s/sx5wGNEu+LeQCpI+OeDQ=,tag:Pb0LJDMh9ibUY5WsviDbLA==,type:str]
    disable-kube-proxy: ENC[AES256_GCM,data:vAzHJw==,iv:5bZ0PdlN07Y7ODphZQ+qf7APSIITWRLvabdS8iBYnog=,tag:W5xsAQ+HW2jKU9PIQeUBAA==,type:bool]
    cluster-cidr: ENC[AES256_GCM,data:5Bt6a72cFAGbGFi7,iv:NfaLDbATcPFZSMtTytpnDACLWqF/IuoqfsF1cCsy1Lc=,tag:Q9f4SmK31LJz4PjY3AMnhA==,type:str]
    service-cidr: ENC[AES256_GCM,data:vhHbSsEXSMXkpv1E,iv:9keeVZJ4dTpfcsxW/90Wa9rWbeKjlRbEsXvhLoHAaTs=,tag:Qz4hxKLh44rxmoY6qm1MGA==,type:str]
    kube-controller-manager-arg:
        - ENC[AES256_GCM,data:3l2kj9FATnncNq7sisLfLw5tzH4=,iv:vkgD4420oti7uTp+i4gK88Ca2DcaK0QSeaCfLTqCvrA=,tag:L5gaS0d/iNf6ekq8JVDFvg==,type:str]
    kube-proxy-arg:
        - ENC[AES256_GCM,data:AjHs/ll4CwlGP6rQX3Cu8mdlj6N79dd8hLjwBQ==,iv:irCuPcZI0ckMwaJmqiE/3cLkZNan8YsbrQi4ayBhHRY=,tag:ZyLGssa6Czp+hJYw3033kA==,type:str]
    kube-scheduler-arg:
        - ENC[AES256_GCM,data:QgRE8Hhov1UPu3cirzSC8HEeWQk=,iv:akEtDQd/EiXPPsV+9ZMpmnUgcYqKo3+QT7oUpFoPJkY=,tag:WPIVNKencsd7abRhmJuusA==,type:str]
    etcd-expose-metrics: ENC[AES256_GCM,data:Nj5H0Q==,iv:TxNcc963ylnowWEiQYd6LNMozQ/BoxxfOukb2jwVE1E=,tag:taQSEOycoknIpayptUQYHg==,type:bool]
    kube-apiserver-arg:
        - ENC[AES256_GCM,data:8Uvg8xeucapOyah/iJmvmKsbqA==,iv:60/3BZx0t8sNUL+zfA1qhn21yrje1JHZEdwTWFW4rJI=,tag:h5HBzHa5iOm2mEBuy2xCcw==,type:str]
    node-taint:
        - ENC[AES256_GCM,data:SXirkprhDiG4tCXRp3OzAR1e1geLsV2or+lckDz4YUKlvsm02VBdqA==,iv:xwcciznK+bNayfSZm9HjmGdrciG0KoshJhYFGKfi5tg=,tag:HN/jbYr3YSIECbM51xzBSg==,type:str]
    node-label:
        - ENC[AES256_GCM,data:Iggc6Z+kMwvEuKYvf/+kv78fwlqXyshmLGA1McsV,iv:c80p0ycfB1h3aB2tYVyx7vwSrGm0s1hk6nAWJX/f6Pk=,tag:kqtnXGCWdvQ66xdXGx3snw==,type:str]
    kubelet-arg:
        - ENC[AES256_GCM,data:qg9LX8z0c1oC297MRqWYWsXC4si0tq0/zCOCbpLn4Qwq,iv:kamL5q10O+4XDy5kgrKuIg1vojocyJw7pm/d6iz0iBE=,tag:32Xjx/VrMO7oXyCRiO6jSQ==,type:str]
        - ENC[AES256_GCM,data:vGFDUOTxI7gdM3UzDF3mBgQJZor3G8P4FXHyyTAnxwPzoCCHjA==,iv:P9JtSsDeMkJz6wAnGtFnedcvE0Ox+7Pu38QjF1GvHDk=,tag:V6r3WwcEmfP7bTJ0pXQwaA==,type:str]
        - ENC[AES256_GCM,data:TqA2HPRBKv8l7kxrYBfmSxpjLCMC1LGTQg==,iv:w2QBUBBKHvKTN/vViUUaurP0Mj3VnxLqvjj4P9PfHZs=,tag:B4Z45etWG0rdXyXN7T3i3Q==,type:str]
        - ENC[AES256_GCM,data:LmwDwxtE9Hm0rd/R6Dmy28nX3+jRgLupyVA=,iv:AafNVfjBG5WfUSh8oxjWquLJhnEWbvooGPHwN+yvt+8=,tag:R/qhzdg56rPgKUUDr61lLw==,type:str]
        - ENC[AES256_GCM,data:v2FzG3XN2RiK9BuDnFwIN+Rw35+a6ihLh27Q5Gv3lhVx3LqRB7/0PqgG6x/lBvCoXx4bTIWsWbeh,iv:7F10iy33Gq0U4qkw9Wiplzqi1cahrRM2SjtOpHTiKvE=,tag:EtGHwYa2QZklYb/I9z5c/w==,type:str]
        - ENC[AES256_GCM,data:n6s1nEnRzr/U7F+W//I/waQqYO5EtwyInaFxRR6VP4AgM3J7dfDi7N0VPFsI98vQUT9cVo5Aw0Pc,iv:JQ1rMx8hZ0vwqOeN7nD8SzZy4iueuEgl/3NFArKDqOk=,tag:gj+2TQbcRHsUsfloNrIYVw==,type:str]
        - ENC[AES256_GCM,data:J/EF7tg8sOacDo9bw8I+HxrYZetk4TS6Kan90Ov1n95q66lZ4BjrM4+3pi64ldoD3Rh7OWyaFl6Eo+BbJPus4Qhn,iv:eHnZprlrjc+XzfRJwh+objSwy3XhWZDrWReFy6w3tSQ=,tag:BDHJ57XbpZV969bh+Lwclg==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUUdkd1FDUmJ1dXltZ1Zm
            VG1iZE5JdlRXVGFjWFZqTllHS05yZUJrWGdFCmxBd3h1OWE0aXN0bjRCVG5nMXRO
            am9kSGJMakJHNHVuNXNhcndVYXR2ZkUKLS0tIEtSaElaL21peWpTcm5WY2YyeTIw
            b3U2b3dndE5MTUtMZm5iMWQrVWF0S28KEmdKWx/avXztsYpe51PQZT377NxLOCmP
            Hpd3gqhel+lYqAPHISMiRme3TUWI0BRs698dorQ61h6ljs6l0ZHoOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T12:29:39Z"
    mac: ENC[AES256_GCM,data:8g3ixbETeop9mr2wzilAt3weKQUMOH6uDtzsnp/3t0mv482aPGGUP3QAwnCE8K7jlNA9AftCNaDSf2FArAxG08pzbUhHjPL87kVa3e6LDJpJoIyS+X2DAye4yEWktezeQZDqSZsXg5BooeG8W4IewGc1uh14qGM6EOMu4hvdMY8=,iv:j+1j0pjFA52QFYVRbxvDU2qyXJxjGeFfnm2cTKj0UFk=,tag:3d5ZJliGuuouOzWujTNIrQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
