kind: ENC[AES256_GCM,data:MslEFCWe,iv:C/VNZJvG0N0GBeKysw3o9Oxi0C0raCbaYaFwKYIfyAk=,tag:7ao/svB0VPMg8JYFofF4gg==,type:str]
ansible_user: ENC[AES256_GCM,data:m4zhO3LA,iv:YYs9dnOzFjSc/jftclXvbnNTQL1swORvTOUzj+xPRjI=,tag:XJh0d9wTOU+9zrS/VA4Taw==,type:str]
#ENC[AES256_GCM,data:X4Aqm9rsGlEOt8bp5fRvL0OaYB7IjP0HOunWEAIFPy8D64N9/9Q4ipQ=,iv:lADEg0cLlvUfbo5yk3us3U9zFZQbGChPyaT+nC4ENSM=,tag:S0piUAIoe75OxpOtll2nFA==,type:comment]
k3s_agent:
    node-ip: ENC[AES256_GCM,data:AXUEggVQ2dhxiVLCRUn7BvGY,iv:SGOc//TTYpGNxZWLZGAer4/na4JNdiYL7Vi7+vuRJ9Q=,tag:zpvKxAaBhsug4drYun/z2A==,type:str]
    node-taint:
        - ENC[AES256_GCM,data:Wr+0mWlcjUgWyhIOoTUa4cvsW8Z+UwMeTzsAe1hpeZXAsTHqchoGAQ==,iv:UlV/hRjEE3vciaz0SDmYwSGgcHFUiWRIYqCN16C9Qn0=,tag:DZe/HRZAKg+xnMjMssVIbw==,type:str]
    kubelet-arg:
        - ENC[AES256_GCM,data:2KsW6rr+FugJZOod7x0KVsVQ0fz8te+uRgT9SaXQWA/Swrc=,iv:OVO17jBzmt3PrcWW1x8KloZsKy3d1PGC7x5kddvDy08=,tag:kEFmUn32AKQAWOLFAmJjqg==,type:str]
        - ENC[AES256_GCM,data:Vt4pVIbvOZlqBW5uWuqpFp17oixDKL5dgUIiYFBtep1lnHNNeA==,iv:1Ojzyt+szgAh7Y5D5iDRfkYuxZFLVmjUa+tQpNm7jmY=,tag:l0zsob8ZdV6HS1txPJJHZQ==,type:str]
        - ENC[AES256_GCM,data:+oD5MLHlkR/EyvxJtWkpQGECI2+2WFijxw==,iv:buUO3Rh8Usn9I9iDfE+xRESMb22KpTSPjI8crSB7bLI=,tag:MyfGtx5q25iNJ0FShMvqSg==,type:str]
        - ENC[AES256_GCM,data:YlmD+4tIFtV1kDX30MEtF6q8WJIeuUApB/s=,iv:Gzt/j5B7THfHFenFhBfyawMIeccFq9MG0mtsc4aRMEQ=,tag:Yycxafd5LRYZQx3LPtSl3w==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1TzNFbG9BcXpUazQ0blJH
            NXdSN2lsS3ZxcTA1R3RuZ0J1Z013aXdTMDE0CitIUHk4dzRqcjBlY0V3SjdwMk0z
            SG1rNEFzcDV4a0tLZlRnZGIrRkI0bUUKLS0tIDFjeloxQ3dyMGFhdHlGQm9ITDd0
            RlFqSDFvckRHWmZxQkV1aEp2Wm9mL00Ko9elNL7xu1cZHnWYNbSeT6WadTg/OdXC
            gdxm9ZLXS3h0F8+B54tSfOxERE2PxXwr/UQV471ZbKP7uesGqUNRtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-21T20:52:39Z"
    mac: ENC[AES256_GCM,data:UgAiycu/xhK4d61nzgW6Q2vLh5qHOlSQWTBvVShjLp34N8hwJUNLcxIVMJ2jYb00J4pylWQSpVBr3xsJ2hFrxGWoc3klCdS6OmWYaZQi8Q5gCB9cKeWbveyTDMJDL+bqOykSj3Bpmp64N4erHw2omkd9kqXJ4mycjoa5LF9VSEg=,iv:rM/xPSRR058t5Da67J5VR3jP5TKtVGuLUtx6PPeLp2o=,tag:ldH0KO/cxSVCTIUEYoFCkA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
