kind: ENC[AES256_GCM,data:sfCVeJCM,iv:3XjqdNMhEV9UDX4Qx6BRddRdmg2IOWWc7lapLl83o+E=,tag:csE28+DmkMwxc6URlIhgZA==,type:str]
ansible_user: ENC[AES256_GCM,data:izRjFj1i,iv:TBTD3dGJj2jTelUEqC0d9sISBPVFIMkXsPuVbyWQ3ds=,tag:ydgYZHaDqJoS4i4cvzduNw==,type:str]
#ENC[AES256_GCM,data:lXB7WT6Nl1NoP/309ItTmYxwmEu9wYMKdcoLHLXHBitjjh1iMtMf77c=,iv:9KUxYDVkUOt2gjGS2O6zBGZFZsN4gp2Df7upqwXrPDc=,tag:wgs3IXrIP8c0eyYGqJYhqQ==,type:comment]
k3s_agent:
    node-ip: ENC[AES256_GCM,data:1AiFMbdUR3xzsRNtWA7ZvMNl,iv:KysEAy7Eqa7BvWzVPgybov9PQ7SU+NxBogJtQKRWtXg=,tag:kpg+ichXy4SqN5pkE15Apw==,type:str]
    node-taint:
        - ENC[AES256_GCM,data:GJXh6oTE5ycVlc4d/fsenmeckjx4d3er3GwE5krUcg==,iv:yLAeZEqSLP4U0v13UbTd9zgVDPgnAm7gsjKH4l30FCU=,tag:N3DTg4FVmGQb/W0UjAAtqQ==,type:str]
    kubelet-arg:
        - ENC[AES256_GCM,data:/QzSWSafix3YQgmGXO4k2ojFVsPd1nyvjGJEFUKkYVx6Xdc=,iv:Om17Onez/HsZOZmsT1hFYeGCxShMD2mpos6eJgBlvC4=,tag:whRikKU06Thll2i8lWCBDw==,type:str]
        - ENC[AES256_GCM,data:Flicnx9qTxPhfYljEtHPFRR3KRUIWgVzLlrxa26Ib+kMcO0Thg==,iv:CSxPh0QC2/uWq9o7rJcTDbakYpBqHwdzbKtPPIxgyso=,tag:YdW0Xhl50y1Wp6+NhUtoAA==,type:str]
        - ENC[AES256_GCM,data:Nlf08fOtTRzHnTN8hpEanhqKDaCwjB4j7g==,iv:2y9G6utxN3oEw/Lx+AW2MmO1I0bML6zJ1oCZe9rSHGA=,tag:28CsiLXTDYPZqaaYNWcm0w==,type:str]
        - ENC[AES256_GCM,data:5bEuGZrjXtTs6IJPNAHHA6H1VhxoXeQ0ip0=,iv:indfMDavmx5pltO5pFOIdubjYS9/nVaN5BSNdzDAI0Y=,tag:ufYaI+pWFFhChG5588RSXQ==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRitnYkZDSXhYN3I4RkpM
            UnhibHNlaFJ1MXp6aXVIc2JWMkNkcEdIaG4wCnlYd24ydzI3Tm81aTNlWnZ5d0JD
            bHI2eGI3M1Rxa3VES1VnZ0RxdHpBYk0KLS0tIGcrZzdYcTk0SFpIWmk0bDFjbWtj
            YjF5WUNIWDQ3UDBoeFVMWXZFWk1VQ28K2n5g3Iu25h6WHvVCz2N1qI69D1pnmoiA
            KFjyzaOo7EUD7rBkXpNK9Jk6bR6y4v3Uj0BcD4fXpuZx4i67gSgLUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T11:05:17Z"
    mac: ENC[AES256_GCM,data:d+DyWp8UyVibwojumWorIGo93LkLeDyL4F52LFtwtRu6sXmcyDmmPTHhk1tk+vGQS/qJH+m5JgO0QSfj8nGtHuzKOQtcw8J2/qomDAVqyhQdXJV2IqKNoIJ19PqF2gxRHrJpF9e5i24zprkw77qRiwp1ORTPWLJwBRXmLZs35lQ=,iv:IKiOrq+3KNqITJxG7PkKR2p1oJ2TbXV80uK8SaXRzrs=,tag:Ak+3Z9YjKie1BqgTMteAqw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
