ansible_host: ENC[AES256_GCM,data:1Vo53StyLZOY+lPN9w==,iv:m6CiLYT+myEsVNI22ourdNfz9xmOdDjc4jKfbWnffE8=,tag:33N6q9nQd6VZXoHvuLurhw==,type:str]
ansible_user: ENC[AES256_GCM,data:0VOJxg==,iv:ZfKYzkPAcyy42afwTAaxFwPJUev5kFwkXQuk3ydfQug=,tag:XUBjqJf6o91Wz9BIjQHJcg==,type:str]
ansible_connection: ENC[AES256_GCM,data:Zr0QvjgYNGrI5pLQp3W63L8IuPUBOUpnByGHLsU=,iv:QDKBYSLF9lZq43Zbs6SkCeje8Vb5yRaR6dUIJPacay4=,tag:0U/ixqj4tFtSt/8aF1/bKA==,type:str]
ansible_network_os: ENC[AES256_GCM,data:meReGoP+TNFSDBTmQARAqTSZXH8yTOYboA==,iv:6r4WY3juKhdf9kkUQFZ5S+xjgAkm4pfXCDiJjvSGE1w=,tag:V4l6BDpyXW3LucE9AesbRg==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDT1EwVFBZVUFzSVJITmtZ
            NFdmeWhDc1VhcG55bzNsdFl1MEMzeHJCblFzCms1QmVRV1Zyd3NjcXRVSE82WnJN
            aWlWRHBQM1RpaWZxVkZKeFJUcUoxZmsKLS0tIEV2RWVQdEZ1Ym9aNTJjN0I5a2or
            WWZSNjFJazZydTlySW8va3V4cHVTb0EKb2un29bHd5BzQUm84iRK2NyomOcMsvtX
            +rywQ+ZbKO9qJVOO2Da8r8BvzLTxsRzAqudXw1Ecjb7CdFd7C4ycDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T18:14:01Z"
    mac: ENC[AES256_GCM,data:wGqqI4Fltf12tkYeP+SbS6aWUKA2V63bel05qEpyetczcfDQLuDgNjqBJzmXKIk8mknD9rnFnFa3k5E+JhEjZA/nMIgWGd7nQpEDZCqDgIujQasDqm9P/seZMxRIB0kjeygCF5FvtiChKXuVQQoOeNzD76QelA6rYB3wBoRo4Pc=,iv:58Lt41WLFeaDniwKWf6YBLCDBYLYxWerQkOGMYQY+eA=,tag:P24iuRghEupIRdvMiukPWA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
