ansible_host: ENC[AES256_GCM,data:Zxkh5bWplFQhXNAbJA==,iv:+6UWdQe5cJTvNSjIDLDoHKWsbhjAmZSS9diMtWg/x0A=,tag:+dZUsrk2wwYL6B97A1MbCQ==,type:str]
ansible_user: ENC[AES256_GCM,data:LHORfg==,iv:O5rhriuhiPThIVFHrhzGeWurbXSN/pdb10hQTTjUQb0=,tag:U0ErNIUUQjyhtjVdiwdTiA==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwNUROOUhRaGlpUDRWNW9r
            Wk8xSEtzUGhtTWdHcU5KVy9tK3hrWFRSbTNNCnBSUDEvM0cxOFZzdDI4M1BTSEdN
            bzRVTTVjWkF5ZDQzZ1V3ZU52K281MkUKLS0tIEloaCtPc1ZSSk94cyt0L096QWRX
            Q244ZmRGZnVIMUE0YWN6bUFCWHQ4YUEKbNHwJIGavw+wYSGQ8NHt9ztlUd6JoKxA
            eLkWsPw91Niswt6jQUbDcNsV1JP7+uTYpUaDqZiMK0TcQuUvJXryOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T18:29:55Z"
    mac: ENC[AES256_GCM,data:a+yJjW6XDSdd6l6mGnZhzpDT1NydEXKM/NAsQIl4QbRVIBHXgzeQ093HH6THXhshp7yBmybcukpyjJ7QvwWd2E6rCkJwuFZ77cyxOHVYXDrqTX4NS9jjMt4tdqdW5d3aJn3kwcZ7onSNdG5+QP3C1fwEInmdI8xhAN+jumGE1bM=,iv:mv2lLK8WPBM0xQqbBxDPuwNY1kn6zjPZCAiod8oXzjI=,tag:mBP0CoaVYxo2EYTbwXStZQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
