apiVersion: v1
kind: Secret
metadata:
    name: mimir-secret
    namespace: monitoring
type: Opaque
stringData:
    BUCKET_HOST: ENC[AES256_GCM,data:/2WqQWRA5IVWTQ5XC7RlqttKOCs9P8Utiu/VQq7o+j1ScqbSceTyVg==,iv:FKKTcs5nOLbmCISKclZbtv/E/GHTkLqdYRkRgNMzGHE=,tag:+ehFMaSzBMlOVCwqvQ31fQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:HLnBWLk=,iv:XEHTbvQYhrq8Z145E3RM+XH3oRtuo9QM3jTTqs0Vyrs=,tag:OGmfsSmM3VlWxJ/VPEdl4A==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:u3YFL04+jUXDeQKvexOQkItKLbRY6Y80cgjcGuG6E9PIs1QcdZX8VA==,iv:MWjwN7LaliKn2o5eEebJb0X5knehLO2WPecctPGmOwc=,tag:HDSyin6Jd8jRaeNYa4xutg==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5TUdLbUw5RkpSNG5aNUR1
            bm84emMxZHUwNll5VlFMNU9iemY3eEhZaUhJCkZjb1RoZkVQc1JGdnVlTTFCYlNo
            Ri9vRXB5aWVQaFhjNW5oZVZqTU9VQmMKLS0tIHI0Z0k4b0p0YWllVVIrNVl3cmd5
            R1V1aEJNeHhMZEhRcW0xeEY0SmdsMFUKCUcz1ogHBhdwDQKxDZ2xqnTKFgowK6oe
            GI6GCptgQBtg/TCo7AUyJvi+Hp1gkMc/6g3odD5gh3kGdK64nkqcgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T23:27:22Z"
    mac: ENC[AES256_GCM,data:2KeiOdK8oZZcEhUTJmaaqAmtXgtokI7ntEiFRn18xKZ9jFXNvewTs/kMsfXpKgt0zFZjQwxCzfNk1FlRRlORgQyrKX+atbg07tk597R5Zb+olDn5CABYgjqDYcmKGlI+dqFv6C4NWdIah+5lhRAF70Wl/Yuue3SxBtK+BubD0sg=,iv:z1AcGcOH78a5e21Gaf/d6ALRFvjAKfdXpO5y7GxbN9I=,tag:G6k+nWI1JHcA/Hlnnnuy2g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
