apiVersion: v1
kind: Secret
metadata:
    name: mimir-secret
type: Opaque
stringData:
    BUCKET_HOST: ENC[AES256_GCM,data:NYFuBjTbXA8C40YXnkN89HItbQ97X7SeFZKi7w==,iv:1LsoYIDQb2dJNkHg2RXVjvaQwpHcVM3UpRtgOJfpGUk=,tag:Gk/NDppMRjdDvxGypuINQQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:KPRP9+ZL/pY+X8OaqKV4h2eiLmo=,iv:PsxAmXLoncWudAS5t+apaqbLPy4aMPijc5H2b5HLozw=,tag:EfmwAVMb2p5sTIYb6VqogA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:J8ujtun3WX1n9ZbE/Vw9FZ0MDHhMt9t5tjmaD6HsVbtt0G6T1dXpUg==,iv:h66+N7Pg/F9mhAtxJhLS9VKLOIzZZ/w/rB2UjM49q4U=,tag:1WzV6suhqBVg3pFGxlWyDQ==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFcW5rSXY3UmYrOTdSY0Fj
            M29lL1FERDNqZXdhWHVac0F1YUdhN0lEQkJ3Ckx4WEZrem4xMkZ4cFcyWUlCbHRk
            ZUNRSWw5TjhaS2hRVFB6RTdkRlJxQkkKLS0tIEJCYklYYmFTS1lFN09jUm1iaVBP
            VG9LclFzTzk4THBFaUUrbzZnSlFqNEEKJOCMvJD2F+ujlx8/zA++LY6/aTo0dQXf
            bOpEv8PH9VdsjdQVRNi5okjELcMPRJXNZLO5Osgtau2fapkVoTpzjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T12:28:26Z"
    mac: ENC[AES256_GCM,data:x9pkOrilfKDKvKtNvShOeMmjN1jk5XqeBo5BqPQ9gUA46EG2m+11hxob3hTEmc+wImnLfyx3MMw3xp3nTYgi811Mknn9cbI/WZ76Z3CQq2FAY27vPE3+yLrgaxfSqL0Sd7pw4Q5y4ofCPieYa3IdjSHP7Uf3mXliEJcU1QSMGnA=,iv:IQL11qTPavyebldXcKCYQqwCU2N+YwD/sNL/ntqygjg=,tag:z/QRO252WtPcFPQGJSdJXA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
