apiVersion: v1
kind: Secret
metadata:
    name: mimir-secret
type: Opaque
stringData:
    BUCKET_HOST: ENC[AES256_GCM,data:VVvzj9/9K5ojMdRXUvkcjoH3IbuCT2FWVg9qIsMpwMPO8VKI,iv:+xwhf/qUicT376l2zdug5J1r5u2cLX06kNRIB+4P6XU=,tag:wqQiYMAondU5aEDdtK8Q+Q==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Zovnjk5A5i9v4WTxtnGNcEPMz8I=,iv:8ggwrQy432CjrfT7yDq+zngzcjqf43qwqIzUNJweuc8=,tag:fobu+Ix+/PDq2j1ISDe38Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:gCMF0G+XAgAgA4WuFyr3nFvbPfyKlHtEQdCOykZN0wp5JarHTx5xdg==,iv:bH8WNMe4pUqyMaJ5ZT4eImtC0UIWzVoxSyL56VkiqTk=,tag:LoQoUOmN6Q6APm0TFSHHBA==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMT3k0bHpkbm9lQ25hYmFH
            Y1IrdGVMWW5VS3dIbys4alJtYmtZWkZkR0EwCmU5eTJ3Tm1KZGliVG5SbW1TblJY
            NXIrQVQwdFJKZTkrMTdFVUFoempDa2cKLS0tIGJkb3RJeGI3TEhVMy91V3U0ZmpX
            OGQrTmJYN3QyczNYSVc5MWVKMWdET0UKD7P7jg2y7yFteEh2QkGn4guu12lBWYWh
            2eForDGjKyf2DHtpi1VRTzsbyKyu8OiEfInxVLINh5lzNYfiI68lLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T08:40:35Z"
    mac: ENC[AES256_GCM,data:TDJrY9nBKMfTQzTyXEii1FOvl8KLKCPIhrcjf0uD2j7D2zxoI3B0HlcKHMHlXCLXEM3XP/hyrELm/qpax9t1yQLRn/zLRAcnS8JpiM2wmICTFeHSOntyFAXNbgvL/DBJxqdGN5Pnpute8dBMyVBCkF6/ldHkZ9v//YimUHDyygU=,iv:mQ3a87w0emKqnbcVeSK/soJnbCajhwQWY04CKodz/ww=,tag:NFAkwewF9L8QFzDJdbqJ9g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
