---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./angelnu-charts.yaml
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./coredns.yaml
  - ./descheduler.yaml
  - ./external-dns.yaml
  - ./fairwinds-charts.yaml
  - ./hajimari.yaml
  - ./ingress-nginx.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./kubernetes-dashboard.yaml
  - ./kubernetes-sigs-nfd.yaml
  - ./longhorn.yaml
  - ./metrics-server.yaml
  - ./nfs-provisioner-charts.yaml
  - ./postfinance.yaml
  - ./prometheus-community-charts.yaml
  - ./spegel.yaml
  - ./stakater.yaml
