---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    hajimari:
      name: "Rasp K3s"
      title: "Rasp K3s"
      lightTheme: tron
      darkTheme: tron
      customThemes: []
      showSearch: false
      showGreeting: false
      showApps: true
      showAppGroups: true
      showAppUrls: true
      showAppInfo: true
      showAppStatus: true
      defaultAppIcon: mdi:application
      showBookmarks: true
      showGlobalBookmarks: true
      showBookmarkGroups: true
      alwaysTargetBlank: true
      defaultSearchProvider: None
      defaultEnable: true
      namespaceSelector:
        any: true
      # icons: https://materialdesignicons.com/
      customApps:
        - group: Media
          apps:
            - name: Kodi
              url: http://mibox:8080/
              icon: kodi
            - name: Deluge
              url: http://storage.lan:8112/
              icon: download
            - name: Transmission
              url: http://storage.lan:9092/
              icon: folder-download
        - group: 3D Printing
          apps:
            - name: Octoprint
              url: http://icarus.lan/
              icon: printer-3d-nozzle
            - name: Obico
              url: http://cn5.lan:3334/
              icon: printer-3d
        - group: Monitoring
          apps:
            - name: PagerDuty
              url: https://smoothship.eu.pagerduty.com/
              icon: alert
      globalBookmarks:
        - group: k8s-at-home
          bookmarks:
            - name: thiagoalmeidasa/homelab
              url: "https://github.com/thiagoalmeidasa/homelab/"
            - name: Template repo
              url: "https://github.com/onedr0p/flux-cluster-template"
            - name: Helm charts
              url: "https://github.com/bjw-s/helm-charts/tree/main/charts/library/common"
            - name: onedr0p/home-cluster
              url: "https://github.com/onedr0p/home-cluster"
            - name: cbirkenbeul/k3s-gitops
              url: "https://github.com/cbirkenbeul/k3s-gitops"
            - name: bjw-s/k8s-gitops
              url: "https://github.com/bjw-s/k8s-gitops"
        - group: Tech
          bookmarks:
            - name: Hacker News
              url: 'https://news.ycombinator.com/'
            - name: The Verge
              url: 'https://theverge.com/'
            - name: MIT Technology Review
              url: 'https://www.technologyreview.com/'
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: |
            10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
          hajimari.io/enable: "false"
        hosts:
          - host: &host "hajimari.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podAnnotations:
      configmap.reloader.stakater.com/reload: hajimari-settings
    persistence:
      data:
        enabled: true
        type: emptyDir
    resources:
      requests:
        cpu: 100m
        memory: 128M
