{
 "title": "Jellyfin",
 "tags": [ "Jellyfin" ],
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "5s,30s,1m,5m,10m,30m,1h,6h,1d" },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(jellyfin_up,service)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(jellyfin_up{service=~\"$service\"}) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Movies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(jellyfin_media_count{type=\"Movie\", service=~\"$service\"}) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Collections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(jellyfin_media_count{type=\"BoxSet\", service=~\"$service\"}) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TV Shows",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(jellyfin_media_count{type=\"Series\", service=~\"$service\"}) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TV Show Episodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(jellyfin_media_count{type=\"Episode\", service=~\"$service\"}) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Now Playing - Movies",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "max by (user_device, item_index_clean, type, service) (\n  label_replace(\n    label_join(\n      label_join(\n        label_join(\n          jellyfin_now_playing_state{service=~\"$service\"},\n          \"item_index\",\n          \" \",\n          \"series_season\",\n          \"series_episode\"\n        ),\n        \"full_name\",\n        \" - \",\n        \"series_title\",\n        \"item_index\",\n        \"title\"\n      ),\n      \"user_device\",\n      \" - \",\n      \"username\",\n      \"device\"\n    ),\n    \"item_index_clean\",\n    \"$1\",\n    \"full_name\",\n    \"^[- ]*(.*?)[- ]*$\"\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Now Playing - TV Shows",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "max by (user_device, item_index_clean, type, service) (\n  label_replace(\n    label_join(\n      label_join(\n        label_join(\n          jellyfin_now_playing_state{service=~\"$service\"},\n          \"item_index\",\n          \" \",\n          \"series_season\",\n          \"series_episode\"\n        ),\n        \"full_name\",\n        \" - \",\n        \"series_title\",\n        \"item_index\",\n        \"title\"\n      ),\n      \"user_device\",\n      \" - \",\n      \"username\",\n      \"device\"\n    ),\n    \"item_index_clean\",\n    \"$1\",\n    \"full_name\",\n    \"^[- ]*(.*?)[- ]*$\"\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(jellyfin_user_active{service=~\"$service\"}) by (username, client, device, version, service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User Activity",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "max(jellyfin_activity_count{service=~\"$service\"}) by (username, service)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}