---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app vert
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  driftDetection:
    mode: enabled

  values:
    controllers:
      vert:
        replicas: 1
        strategy: Recreate
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
        containers:
          app:
            image:
              repository: ghcr.io/vert-sh/vert
              tag: main@sha256:6492f2a88e977e7ce82fd26f49028a17575fee8cac38604f585bc5773298cbc8
            env:
              TZ: ${TIMEZONE}
              PUB_DISABLE_ALL_EXTERNAL_REQUESTS: true
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/liveness
                    port: &port 80
                  initialDelaySeconds: 15
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness: *probes
            resources:
              requests:
                cpu: 25m
                memory: 256Mi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port

    persistence:
      cache:
        type: emptyDir
        sizeLimit: 5Gi
        globalMounts:
          - path: "/var/cache/nginx"
      run:
        type: emptyDir
        sizeLimit: 1Gi
        globalMounts:
          - path: "/var/run"
