apiVersion: v1
kind: Secret
metadata:
    name: convert-oauth2-proxy
    namespace: default
stringData:
    OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:iU0r9RHlQA==,iv:KZ5pu14rIf507SkfgHBFoJxqshOgBKRBmKXmv+LHE08=,tag:VQ28ZoJF4BjVNrK1zbhdhg==,type:str]
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:baeysiyIlTMHfcFDHnThqg+0iYWxSo+8QE6YSU7Ssy4=,iv:aPdiqWuYhfaIZwawGAerZRrHrImLqN1pdmSn2wAu/3E=,tag:6NQ2PSGQU2XnnDiAdW5Ylg==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:GwoC0YXDo4LpndLGp9CdTL/qOgBM3roNhpQOeIuJciTsLXbbF6FRoMMMTqs=,iv:GrURW/Neogh/falZhb0afuAGOAD8lsg6aI2DRO8w3Ck=,tag:8o8HY73wBYEpiJ+Fqmr7kQ==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUkVsazZuY1NsS2Z6ajVM
            VnF4QjEwVHVPQUFUKzRMd1EwUDkxMWFpWGtNCnBtOXl1cWxrMUdtdnNzTDdjQzFZ
            QVdDT1FRKzFSNUhaZ25pWGp1MDhoTWMKLS0tIGR6cjJVV0VMdnVLOE41OTJuY2hL
            SWpqcUU0SXd1NUpra015ZTNCVXlZZnMKAxXTDOcV5MlU210g9VZ+GpctgtYC4yd9
            J2B4M1hkokC2B2DO+cCJbKnnCTX1zBP9UG3IM7qVxht8nDwKSTKkZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-31T16:35:33Z"
    mac: ENC[AES256_GCM,data:B3ZqyZcXyTux7gv2HcgJFtVEXTikjqVB83R41a2/iX6xCrr3U6F7CykUjgFp+j6Ix1wp7pRoA4jQLxjsVBoSiffDpSSlFaylnq38WNdT7VFiULfklAmaxQmEi0FA6+Xr6cTBD501VB9BmyPBxVjrjlxfap4V/07HFvDavJVhLQA=,iv:/3PHaZX8re0HSQskQ5rQQGD6kKY8h0gSgvCzoU68d2U=,tag:l3/Q+liyj2+4Hc34k8CZxw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
