apiVersion: v1
kind: Secret
metadata:
    name: smtp-relay-secret
type: Opaque
stringData:
    resend-api-key: ENC[AES256_GCM,data:wsZGda3F5/58iIlMVFtfadEuT9f9vVSQObUhkPbM4efTtA0o,iv:Yn1iYKzVbGAXY+nWr+NRBgkzsy4BiEsPY1/5EdEEJws=,tag:8SxmOo5rFbS5V0/IeI0EEQ==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNzR1RUJyMGhqNzl5Uzlm
            WWxyclRiRDhGdDJCWkJmaHNxdWVzeXBHMzFrCkdVd1QyaHNSaThtZytVWm1yY0Qy
            K2k1VS85RGQwRWZUNG5nK1U2MFBGN3MKLS0tIGZTeWN1Z3NYWEg4RWtzQjNCemR0
            eUxkaFZlWTd6dGNDYUtvU3JpZ0t2SHcK6fmzULWyMrdePmqVqqPsv84Gx4A+flDl
            fyOf7XjFlBLaCsr4z/EuDVQEQ9pd2Dpe1rpOktdBcYE3nJ1NnhC5fA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-17T23:23:59Z"
    mac: ENC[AES256_GCM,data:YIAoY3O9WhrJZY7cal0MzIHaDQ/ldwm70z+gANy1eKp/e2WaMBxxFc2SdYhBlF3fWvJSlWMHp5MeqvRBd1Bp6LCOiofS/Yet+0DzrDdhKW6kmTquj0nV8sBX0Yh71njZWIpJsuh0kXBX119SBFyx/Ii7l8sMeFgdVp1+PW7Z10w=,iv:shs+TEzQf2mGVyPgYxBbYeNbt/66LF2WiP3CXlgizyw=,tag:oxJp8F3Ca01fu+awGbzvdQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
