---
apiVersion: v1
kind: Service
metadata:
  name: smtp-relay
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: smtp-relay
  ports:
    - name: smtp
      port: 25
      targetPort: smtp
