---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./service-monitor.yaml
  - ./alerts.yaml
configMapGenerator:
  - name: grafana-dashboards-longhorn
    namespace: storage
    files:
      - ./grafana-dashboards/longhorn-v1-1-0_rev6.json
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana_folder: Storage
