---
# yaml-language-server: $schema=https://raw.githubusercontent.com/JJGadgets/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app goldilocks
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: *app
      version: 6.8.0
      sourceRef:
        kind: HelmRepository
        name: fairwinds-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: us-docker.pkg.dev/fairwinds-ops/oss/goldilocks
      tag: v4.9.0
      pullPolicy: IfNotPresent
    controller:
      resources:
        requests:
          cpu: 48m
          memory: 105Mi
        limits:
          cpu: 48m
          memory: 105Mi
    dashboard:
      resources:
        requests:
          cpu: 15m
          memory: 105Mi
        limits:
          memory: 105Mi
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: |
            10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
        hosts:
          - host: &host goldilocks.${SECRET_DOMAIN}
            paths:
              - path: /
                type: Prefix
        tls:
          - hosts:
              - *host

    vpa:
      enabled: true
      updater:
        enabled: false
      recommender:
        extraArgs:
          prometheus-address: |
            http://prometheus-prometheus.monitoring.svc.cluster.local:9090
          storage: prometheus

    metrics-server:
      enabled: false
