apiVersion: v1
kind: Secret
metadata:
    name: cnpg-auth-s3-secret
    namespace: databases
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:+lUk6fX7chMvN6gTPwx9h4Qq2IcQD7z5ySQG6+htd2j8,iv:W6WUeDFU2TA8ey7dRD9DqHqk1c0IFW6vJG9LIdIJVRY=,tag:y53EZ2cEb/9Y47Dq0iDG0g==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:m7JPINFynPdjHucJDV3g1P4wH7UM9Epx0A/IViEvGAjTkFX46A==,iv:9mMYLa1TKyMhImzsprZ9qvo+uS1cQxSYME7hC6TT4QY=,tag:AHNmkAj4wC/aK7GmOv6RYw==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbXR3Wmx6UWw1NU9zVnVT
            MVMvWW5pU2YrSEg2NDdjaFkxRUNLcW1vRXgwCm5oN1hyR0NlMUFTMjI5TnRIYlFF
            elp1aXE1SWhNYUNNMFJlMVViNlhiS3cKLS0tIHU3bndRYUVCVUNUTURrZEorSTBl
            VXd6Z2dJelRjOENtV0cwZFlER0VHRXMKcp3GhrH1kbnOY6aFEL53uvB6NIZ2qU9+
            sgTvUx5Kg+yqiBlh3+0OYuVr3+NFrsoeqvCTLZwIeiaEqKGKsAoFLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T22:45:17Z"
    mac: ENC[AES256_GCM,data:2bpP2ttawJ8b/gOP6KADTVEZ1KK6jXvk4nUueAMBTNUX+YSJStgQaey63D0WeyjB9zLsklsdl+6ignHbYBTa1taoaB3/vtS5oGf9Bfp7h+zVkCJ1QlGNEyR0UFREUF28Yc51YTSDPUYtofJlLCw8eM3vox78AQjMpswwgO7pPUs=,iv:a9HyEiw8DmRbhrUbp6NIfZkyHkK5wpS4ja5Kptc5Y3M=,tag:2fgdpvIv7BNXvPZ7TWveLQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: pocketid-credentials
    namespace: databases
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:tynVev9cuoU=,iv:BKI5CbSSG31KMNx2wZUtKlFhZYKNTavl/D5/RGvdod8=,tag:dhcEgr3TzeNhkAvnH3aEzg==,type:str]
    password: ENC[AES256_GCM,data:uPt83NfY6Ka50tvFeM1G2EskLWfqzzGQ4GB34VM52JiS91TzLlEOIaCUrS46z2q0,iv:+CGkblay+1YeSkLxunh4k0+uctaCaf5HUg/J1FqpldM=,tag:1VjSCdsFbQLwf7vEb2+iJg==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbXR3Wmx6UWw1NU9zVnVT
            MVMvWW5pU2YrSEg2NDdjaFkxRUNLcW1vRXgwCm5oN1hyR0NlMUFTMjI5TnRIYlFF
            elp1aXE1SWhNYUNNMFJlMVViNlhiS3cKLS0tIHU3bndRYUVCVUNUTURrZEorSTBl
            VXd6Z2dJelRjOENtV0cwZFlER0VHRXMKcp3GhrH1kbnOY6aFEL53uvB6NIZ2qU9+
            sgTvUx5Kg+yqiBlh3+0OYuVr3+NFrsoeqvCTLZwIeiaEqKGKsAoFLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T22:45:17Z"
    mac: ENC[AES256_GCM,data:2bpP2ttawJ8b/gOP6KADTVEZ1KK6jXvk4nUueAMBTNUX+YSJStgQaey63D0WeyjB9zLsklsdl+6ignHbYBTa1taoaB3/vtS5oGf9Bfp7h+zVkCJ1QlGNEyR0UFREUF28Yc51YTSDPUYtofJlLCw8eM3vox78AQjMpswwgO7pPUs=,iv:a9HyEiw8DmRbhrUbp6NIfZkyHkK5wpS4ja5Kptc5Y3M=,tag:2fgdpvIv7BNXvPZ7TWveLQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
