apiVersion: v1
kind: Secret
metadata:
    name: cnpg-auth-s3-secret
    namespace: databases
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:2IQdYxFnxBRG9wg=,iv:rWAJ15+EkxWMpb8yfu9E4zelS78n64mRzQxx30pJy6s=,tag:UY6b5ZLb5BDOJ+YR0cS3Rw==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:X4/M63tCFqayo6MU+ib2lmibJRL11T47siEYUjUf6hu4RwUbMbDIKQ==,iv:kujzdNLMawyApIJ5EcEBUxoSkOTyIob8QAdpTFB2WkM=,tag:DQCdNrFyq4fUjLBLyjnjTg==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUFhESEFta2F0TTZhNUIy
            cWgwUnN6c1BhQUJjMVFGT2hxNXJTTy9HQlE4ClYxWXNwMTVIWnhTWHFUVllsWXlj
            ZHVWclovV2J2dGkyTm9DY0xqUFBrdncKLS0tIEZReGtOQlR4WDRwZzRldU9KcE1h
            SzJwcUFhWE9lVzdvR0NqVzBWMzRiSzQKmIXuZ1GFq6VfwfKWMA3HHhZcnvwV1u94
            AyaFc+cfY5NcAWXtxeH4oPIzQa0PiloZc7mI8jml5JH2grj3xcfIRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T23:28:39Z"
    mac: ENC[AES256_GCM,data:HeddJQtQXLrURkcc13QS627cXeHPolU9C4IUFbG6EukCVc/6+ht4ocFYsrQfZMqzZoMg+4sYtfyd6woVeyvBP/snCMKUuJ5rFWt7RyVhgBegcHVcFjjH5Oej6OLrdfq5iIgtzBH04cgqAiqIh5KqGDbEXfn0ECA8cNBjNwzUBJ4=,iv:oKN9RQOE7EyrXmbvPI6a3Fp3F1u3JzhPi06H7ky7kMc=,tag:0wNnQDNghQagp/ebiSR4Fg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: pocketid-credentials
    namespace: databases
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:FgOTUL3JTLY=,iv:W31oPbNh0v5SjbkOEiU50v70U0YU+By9737VumyVw4s=,tag:5iCJw+YnSXRVAU03CZWAIA==,type:str]
    password: ENC[AES256_GCM,data:UqXEaSaEotQyQsH/n1AkPdX/1/4cL6FzvcnTmBJIl10ufGnkS6gWS5cpu8yW4AZy,iv:vmcomLC+lTvILOLHpygc8KOX1EBmnWs232EB3KhxRQo=,tag:baq0lv1c7OO/OfQ3xciDJQ==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUFhESEFta2F0TTZhNUIy
            cWgwUnN6c1BhQUJjMVFGT2hxNXJTTy9HQlE4ClYxWXNwMTVIWnhTWHFUVllsWXlj
            ZHVWclovV2J2dGkyTm9DY0xqUFBrdncKLS0tIEZReGtOQlR4WDRwZzRldU9KcE1h
            SzJwcUFhWE9lVzdvR0NqVzBWMzRiSzQKmIXuZ1GFq6VfwfKWMA3HHhZcnvwV1u94
            AyaFc+cfY5NcAWXtxeH4oPIzQa0PiloZc7mI8jml5JH2grj3xcfIRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T23:28:39Z"
    mac: ENC[AES256_GCM,data:HeddJQtQXLrURkcc13QS627cXeHPolU9C4IUFbG6EukCVc/6+ht4ocFYsrQfZMqzZoMg+4sYtfyd6woVeyvBP/snCMKUuJ5rFWt7RyVhgBegcHVcFjjH5Oej6OLrdfq5iIgtzBH04cgqAiqIh5KqGDbEXfn0ECA8cNBjNwzUBJ4=,iv:oKN9RQOE7EyrXmbvPI6a3Fp3F1u3JzhPi06H7ky7kMc=,tag:0wNnQDNghQagp/ebiSR4Fg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
