apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:kP9cugb2GPWNvf0j6q7fAwf6VM7USLo9i9BHOqXZCJpbXRHNgxuAjA==,iv:w0nV23jN7YT6fjCaUNCHwJnSeFvKkqA/Cz0h1J4d9IA=,tag:2n0ELyxHoKyFyftlNR7L1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTWdaTnMvZWN4SDJUR2lW
            bnpubmp1cDA4QUZ3RldNSGVTWXorSzlENmtzCldZd0hHdCs5RTlheloxeHA2QzRY
            YUVuWmxBbGlueldGODhuUUtVS1BrS2cKLS0tIFNrVlVOT1oxZ1doMkcxZ3NpYkpo
            NGFxNVBkQUxhbktGSjFxMllsSkt1WUkK/ElvtHWO1d0L9bLHpZBpqbBKzPtGV/tl
            1ssEY2dr6AGVnFk6gxoyXV+GRa8o5ZKCJtJsHafOi7h92rrYCvVF+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-20T16:27:27Z"
    mac: ENC[AES256_GCM,data:6KuElA+gbTdiADHl8TORkRZwMR/+hSYZ1EPyiJp/mwcH++ue1KAMCpKnDLRL5y/3/pKr5VwPe684FNUuPEOT7BRF+JjBU4dzN57eXzEAaq5iCqKe1g3Mtv755v0pnkDPHM5jgI0MyIkZ9Ia5Gp17qgYejVDdmk1yBcyBnY/b/DM=,iv:s2enfPiduTu86WUYVeFzWq+YBmtnR8lyAMPJuPhY4qQ=,tag:dti4vTyJQu5YSzDVeEqaGA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
