---
kubernetes:
  children:
    master:
      hosts:
        cn5.lan:
          ansible_host: 192.168.100.105
        cn6.lan:
          ansible_host: 192.168.100.106
        cn4.lan:
          ansible_host: 192.168.100.104
