---
kubernetes:
  children:
    worker:
      hosts:
        cn4.lan:
          ansible_host: 192.168.100.104
    master:
      hosts:
        cn5.lan:
          ansible_host: 192.168.100.105
        cn6.lan:
          ansible_host: 192.168.100.106
        cn8.lan:
          ansible_host: 192.168.100.108
