---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ./podmonitor.yaml
  - ./prometheus-rules.yaml
configMapGenerator:
  - name: flux-grafana-dashboards
    files:
      - grafana-dashboards/control-plane.json
      - grafana-dashboards/cluster.json
      - grafana-dashboards/logs.json
    options:
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
      annotations:
        grafana_folder: Flux
