---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres17
  namespace: databases
  labels:
    recurring-job-group.longhorn.io/backup: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
