apiVersion: v1
kind: Secret
metadata:
    name: readeck-secret
    namespace: default
type: Opaque
stringData:
    READECK_SECRET_KEY: ENC[AES256_GCM,data:wERnyxcoCfajJ5HZUAlsunZYLgdZ3UdUthfw8OeqS8wvBUygQRhUQtD5VmYEs1ekjfPJMNJJGPcjz7cdKGxAZQ==,iv:uNdseuty0lGUf+eHnlOe+GTvJAA1tnBoWnYF6pPP/N8=,tag:NhGu1KXJt3MdAfNGjfR0WA==,type:str]
    READECK_DATABASE_SOURCE: ENC[AES256_GCM,data:NL/z5DIRAhLx9MLoyMa0xwHP5B4G6A/YzviSvWdg97OH3xLlKyEOd3QPRmZ+21glXGQ1GpBrPGna/6sGI42y//T5aAgEL9Js600egtS68N6p12i69UuDX0gOFtBWdirc3w5M32O1kF70aiRwsOreWd1BSLcv5E4zPST1,iv:HlDfL2ZP4A8i+4bsig4uD3dlGodQQ7fvouJhNdQ4Ctc=,tag:k2f9RyRr0kvJstTwiw0Vdg==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Y25tOWthQ0xSNmRyK1kw
            UTEzeHczUUFxQitpNUo4NzR4cGU1b1JDODBZCkM2ZkpRaUZBUWdzUHNxUzQ0Ukgz
            RFpLTmErdHRqQ0lBQ3NWeldKa000Q1UKLS0tIElhSFhXc0lRMUhzUnpVTFNtZ3NC
            MkExREExdXV5T1VMUzZ6TlBvcjFJb3MK1MP2kju4FEeIxuyu0ZECtibOdhsoCBiv
            IooIgfdVKD0+q5O385PnhcrOGIV9P8WeKxyqJRfUcKXSzTA4oXc5VA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-08T07:36:10Z"
    mac: ENC[AES256_GCM,data:R+POLsDOLgUK+m18iJKRoDt4eRIlCGBgIweD0vEC/s0rTmmiwQc2PnO8XQ9A/HMSlg60SWrFbNTUbl6Yn4Em4PxQloNhcDgqtWPYMayYW22CmnL1q2KqUecKEpWsY5tlIMAZME5GeT4LdufVNSp4i0tmouvhzuBtAmBpBf+efQM=,iv:uHtPmlOibqxosdzkeWHwiOwYmo4vzyatZsrnqo3u/bg=,tag:uO5fYVACrdqo+WM9HlJwiA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
