---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: oxicloud
  namespace: databases
spec:
  name: oxicloud
  owner: oxicloud
  cluster:
    name: cnpg-default
