---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cluster.yaml
  - ./database-hoodik.yaml
  - ./objectstore.yaml
  - ./podmonitor.yaml
  - ./prometheusrule.yaml
  - ./role-hoodik.sops.yaml
  - ./scheduledbackup.yaml
  - ./secret.sops.yaml
