---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/barmancloud.cnpg.io/objectstore_v1.json
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: cnpg-default-object-store
  namespace: databases
spec:
  configuration:
    destinationPath: s3://cnpg-backups/default
    endpointURL: http://minio.storage.svc.cluster.local:9000
    s3Credentials:
      accessKeyId:
        name: cnpg-default-s3-secret
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: cnpg-default-s3-secret
        key: SECRET_ACCESS_KEY
    wal:
      compression: bzip2
    data:
      compression: bzip2
  retentionPolicy: "30d"
