apiVersion: v1
kind: Secret
metadata:
    name: cnpg-default-oxicloud
    namespace: databases
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:CG1gv/uX7vc=,iv:ZRxr23A6xoZKJiEMi7TVKg5xntbK2o6qWTxMMY3BNrA=,tag:ZfEKgKo71nlc6bDLD0EDeQ==,type:str]
    password: ENC[AES256_GCM,data:FpzeZfvsScScllpf54+X0JQSWzRnRd3kPrWO4MnwVFL1AQ6CM7SOStW9aKLoUnSM,iv:AbAWYUXCmMz/wD3mVqHY2w/fuCtTrLQNUYYsGiEeE4E=,tag:qkALNk/BZGDvuorO8V4Rsg==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWXNTWXlKY09EQXZsK0x0
            MmFYdTI2TjN0S0RhZmVXVWY3RW9IaXNGcWhJCnd2Tkl5OWd4L00zTDkwTno3cTl3
            ZDlNYlVnMUF0SkFaZVNzMFVVclp0UmcKLS0tIHZpTlJHclZoekd2RmVzQklEQnFQ
            Qk90Q2FjODlCaytTVXNNd3RSMFZ4S1EKmq71F7MbjYKmpvQp0Nyn62WtZWeKvDbL
            GOGU30fRzxPZxs4shUnp8eFz7YO5x6yUGGkQd7eb7EPldtWn7r+rQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-30T06:35:02Z"
    mac: ENC[AES256_GCM,data:aS2lLb5d4LqXK55N3YjezJcnXZb6ImTLkwUrRkDaqV0FLHn/7LZdWnrevSKkqDZcuM8ai/gwmus9C2EPrDtNjgDPoki9585jZPSiYkoHGOIFj7i+08JBqjvea/NvLA3aK4iMGUoHX41kvr8m6NsrNCXKL9pIhFEd4UlwU4MtK1U=,iv:72gzYCmGskzNljxKKt0FjXeAwcxTVBVCv2LIR2hFAmo=,tag:KnvR+wtQ/byeMg0leWC4Yg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
