apiVersion: v1
kind: Secret
metadata:
    name: cnpg-default-metabase
    namespace: databases
type: kubernetes.io/basic-auth
stringData:
    username: metabase
    password: saihee5esh5OhzaeSae0liew
