---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/scheduledbackup_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: cnpg-default-weekly
  namespace: databases
spec:
  schedule: "0 30 5 * * 0"
  backupOwnerReference: self
  immediate: true
  cluster:
    name: cnpg-default
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
