apiVersion: v1
kind: Secret
metadata:
    name: cnpg-default-s3-secret
    namespace: databases
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:umkeT1Dm4JgqsDoC/I596BeoQUY=,iv:cKFrbw13TpnmPiSx+L5WC7iAqFlIJLrzC2rWps+B01E=,tag:C3zaXza8XBLzre3ksAgZmA==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:b/NRy7Df4EKyy/LlCx4PuGNbYXll+4Z5Disg/EXCsSc3Xq06sk4WEA==,iv:6m9YmRXe7+zu4ymaOeQHM63+kw1w3Jw0XisTDM/9tkA=,tag:K13e4QSr/B+6UV4bDyVwqA==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaMTdvcGtjbDJZakM5b3VB
            TjhzYW9EWlJ1cFpBaHR5OGJtRkRxWWJGU1M0CkFmRk5XUlZwVUlpdy9FYVlPQ2lN
            V1BzMUVDMndXWDgxRkVYbWw5T29VblkKLS0tIHhIWDdHbDJDRWY1TnNPNlBTWFVZ
            Rk00T05mbW9EVE12RmxnUWxPOHJvSFUKliRkl5cK5c71JWodPuSlyN39hoIzhjgM
            arb1+wofiFm4P9qoit/Vc53WR4D4Gk5s58efMuVZH5RD5AqScJolzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T18:23:06Z"
    mac: ENC[AES256_GCM,data:uEZkDBECy3lULeabRiZEV9fJxdGZhwD+rWJVqVH666ZSC62wf2LQrWhJzriPSxVDlu+KoRrhm7zfB87Ddc10tpUuyZxYlBNYkw5xke7xy3QVU5sEy+xTPmwyEN8NOirkxKhRDjCLPpgKHHUhQxNWE/g3oPkMf2ZhWnuOvB/Ukk0=,iv:MBvPW54zlCme5eHkNk+wguKlZG/kczEdRXMAMUtvC9I=,tag:dg8gUadOVxcxMGIT4srjtQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
