apiVersion: v1
kind: Secret
metadata:
    name: cnpg-default-s3-secret
    namespace: databases
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:afF/1fCeeoK9Aes=,iv:ohiaB5GQbsAVfG8WgUxr4Gi/SLWd/DxJZ1s6rvVVUIw=,tag:ge+lUZp1aR0M6WilQQIetA==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:el855Zh3DqSiE/ZHGH4z3VqqfeONpfgWxZ+1ip7mK9g9M9KS5fvXww==,iv:GDrDM6wHy2L9NlYB9V389IHL2MmLT0Z2vtmNd3GfdjE=,tag:kWRtWIV9I/qS75mY0M6Jmg==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNV083K215UTQ4N2JhVWpr
            K0VqSlFZWktObzk3b2ZRZ0xKZjRMZXNTVlVRCmpIVm9lSE9QZ1VmN1ZtTVFqRjhw
            c0Zxc2NZcWRuVCtYSWRpdzBrdjVuSzAKLS0tIGhPOE9NN0U2L2ZiUkUzYlo5VWIw
            Z3FRYWlsTXQ2cTJQMjNMQlhRb0NkQ28KU0nMA/Ph97IqWDpYf34tKRhUybgNS82i
            k9ErNIJ7ewSNqRxss05S+E9tvkE1XeqKeRVOLNOIJWlK8kOfBHlvFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T22:36:07Z"
    mac: ENC[AES256_GCM,data:2W3LgUlX2ruHc2jm+oVGYmI5Rfz0XwP/unhunW2Dryk2IiIe/vgTEd94TiyqfaMIOlDTr1Nl8WcXek+PPwk2TT6ipY7SLXg2vILvkIzzuItawjuJWr9BhjLiH37GdMWngQPQhJ5FU8CzHOi0zZ1tGW1kj4KwPTguoAWuqVdDwtQ=,iv:ci8/xNprJ2YnR1cNZ5W4QbgLcp8k+iDCg/SFcItNwoY=,tag:/rwxPM3VsYquUeaRIq+lGQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
