---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app seer
  namespace: media
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      seer:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/seerr-team/seerr
              tag: v3.2.0@sha256:c4cbd5121236ac2f70a843a0b920b68a27976be57917555f1c45b08a1e6b2aad
            env:
              TZ: ${TIMEZONE}
              LOG_LEVEL: "info"
              PORT: &port 80
            envFrom:
              - secretRef:
                  name: seer-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /status
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 2Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: {type: RuntimeDefault}
    service:
      app:
        controller: seer
        ports:
          http:
            port: *port
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Seer
          gethomepage.dev/group: Media
          gethomepage.dev/icon: jellyseerr.png
          gethomepage.dev/description: Media requests
        parentRefs:
          - name: internal
            namespace: networking
            sectionName: https
        hostnames: ["requests.${SECRET_DOMAIN}"]
        rules:
          - backendRefs:
              - identifier: app
                port: http
      public:
        parentRefs:
          - name: external
            namespace: networking
            sectionName: https
        hostnames: ["requests.${PUBLIC_DOMAIN}"]
        rules:
          - backendRefs:
              - identifier: app
                port: http
    persistence:
      config:
        enabled: true
        retain: true
        storageClass: longhorn
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 4Gi
        labels:
          recurring-job-group.longhorn.io/backup: enabled
          recurring-job.longhorn.io/source: enabled
        globalMounts:
          - path: /app/config
      config-cache:
        enabled: true
        storageClass: longhorn
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 4Gi
        globalMounts:
          - path: /app/config/cache
      config-logs:
        type: emptyDir
        globalMounts:
          - path: /app/config/logs
      tmp:
        type: emptyDir
