# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: seer-secret
    namespace: media
type: Opaque
stringData:
    DB_TYPE: ENC[AES256_GCM,data:hp+wYU7ekRI=,iv:L+9GzkU0gDlXaDkbiOk1ZLx/5RSflwwAZT2ZPY5KLWM=,tag:XGIx/AOHfYX79bn25nUFUQ==,type:str]
    DB_HOST: ENC[AES256_GCM,data:KBMtTMM58HlpgASKFXWUMDi16lP6jWUHZ2uUMCKkV7nxkTd4yWeZciQ=,iv:DNEdeOVbKU3jMRKfaCRPbPTAvcnz4Tub9WffEmSRIQc=,tag:G8rbEhO68EkIDUHAcJRp1Q==,type:str]
    DB_PORT: ENC[AES256_GCM,data:h9OxKQ==,iv:JGyh6TeOHBiGddu4YB00gFWpT5CBD8h2fs77c0IadaA=,tag:R8PFGdgwvvKse4t+l4RjXg==,type:str]
    DB_NAME: ENC[AES256_GCM,data:h7GoVg==,iv:5IGt4oVzdyN6C6LxpdaQay70TTya3GIV2RK5z8Q8Jds=,tag:wg3CphELE22XDv0MRlvahw==,type:str]
    DB_USER: ENC[AES256_GCM,data:7uVS4A==,iv:i9CCiWQB2XrqFxZUdACD0t0sNq9IiBQh1/4zoXViDoU=,tag:xJSFCZCpy0l/GNkqLEbKDQ==,type:str]
    DB_PASS: ENC[AES256_GCM,data:GWNkbmqKAnHw5kMVuSzpgsPJoSNM0J1G/9RuZDOHfxk=,iv:UhhC3e+3qXSzPJO6uUqAKNgT6aChc8GiZL7RoscLjAs=,tag:1nyjbO2ygWiPjyiJXiPQeA==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQXN0b2JicTJ4RlozbGQy
            SHE0ZThNYWZtQW9hZE5rR0RzeUVDeVEwbzFBCmwrSkVNMXh6SUN2YllPRXNBV3pp
            amN2ajJ2THNRM3FmbW04UkQxKzJYT2MKLS0tIFFxKzZCNzR1L3M1clltK3JncG16
            bWJvbTZNTHJFcHZqaFhHUVhNMTRGOHMK71ogvCubhb7npJyHcmJ8V5a9As9dwigZ
            paKHljj48wTX/BKLTS3tXpFUgs9XGeagYsxpFJAUB5RZ1HudtSBZrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T13:30:41Z"
    mac: ENC[AES256_GCM,data:yZrIbJFWjS89gnG84loezrNqOukRXVRwgvgszLNs/Xq0Nvj6CUzKybxAyf4CYsCSSVRKdokGZEsRDFTQuKNiel17u4m3TZe5O/7mJx+riiC3+J3mJ75jZ4Pd8OUWVQPx4UqE8/OQvyNatJ6+1GXvlmeJtGtpKPtYqhQ4p1A8F9o=,iv:TqHAExixeCyL9EnT0e6HEm4FqVkrmQ/NuwL5VtOnHWc=,tag:LeyF9VcNzjGcjTNcg/qkxg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
