# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: seer-secret
    namespace: media
type: Opaque
stringData:
    DB_TYPE: ENC[AES256_GCM,data:ALwpN2sgsiE=,iv:2ZNnFxBkbUJemvd+MqngZj5A2k+2hF7hP9kYkHqFNcU=,tag:7ZXrbGypew20Nc17ffXK1g==,type:str]
    DB_HOST: ENC[AES256_GCM,data:RakjwR1GpJP7FpdOmj9UQ/0DtC9TZTO6OjKVg+cGStixtAi2BoWlcT4=,iv:liEb1itt/prLqjPcMUuu49tLJ73Otgra5aCEP6Zxgec=,tag:alZ4cD0MWG2Ms8b+RJlF6w==,type:str]
    DB_PORT: ENC[AES256_GCM,data:egG0eg==,iv:PW2GcyA2BCQZiu8FKIXGe8J69WA8sMin7Y/ANw9nFyA=,tag:GfgJKUr1QTc73hcYDF1k1w==,type:str]
    DB_NAME: ENC[AES256_GCM,data:Ga9JBg==,iv:2BwCMropZIAUgeTZh1kDXPcp04BXiM1IaO8ky9xltsU=,tag:ofb//UW2F6P/4yRQdxunjA==,type:str]
    DB_USER: ENC[AES256_GCM,data:257PLg==,iv:w6qEJbzRtwSHpx1xQIe28OdsJopd4dwfNgXoLLuZ2Bo=,tag:EmasYABBYstXg3c7J+0Fvw==,type:str]
    DB_PASS: ENC[AES256_GCM,data:XfhrYQ3qtGTvER4g9JR+l0Ekpslym8LAx61whtSgTL0eoVZL6qNNATPHgH823ETfh7k39GJqCnG3K7glYOXI8w==,iv:aOMQKLnGdV4HrKL9YxNsqUBmS/FVvyNLeM6H7udh868=,tag:6DP7afBW641JRTLvQVcUng==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaNWFmQitlSEtlQVllQXJH
            ZmZITVN6MlRxaXNHY0l2eGFETVl3VDI3VWlBCmpZTEM4bi90RkxCdmVNempleEhP
            YnUzSk90TVZSNndtWC9pZHNQMVBsS3cKLS0tIFBtZlJBQWJKa2pLS0pPZ0N2SVBl
            OUY3aDFaeFlsRjZRajU2U2ozWTdtMEkKbb2vpyvAqIgvIgA8D3sIf1uLxJjObfgx
            EX9yOTt6XLs1xBMQGj7F6/kJ296JAacr9PW/MZo/dTQ5dqsRwz/OuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T13:31:11Z"
    mac: ENC[AES256_GCM,data:7cbHWabrcjMeorT7dW+wxPbqqoqEgrpI7WtRD7pjDFFOagZaFM5Vo+a+IkbcpwCL18P9iCeL+c91+aDAYqYvyUY7Z6icSMqI7egEL/XlRIB+Osx+TTLggwPcocdwFkV7y2off0bHoGncKx1DCLN53+XH6C4fxbOtJ9wwA4E4PG8=,iv:IdGSPE+IzXPfTwSFFUc+GrOSUdl752pIsNps/g3KQgc=,tag:0CGBStj/W84a9lu5TzfInQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
