# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: seer-secret
    namespace: media
type: Opaque
stringData:
    DB_TYPE: ENC[AES256_GCM,data:hnwZJh/JOBc=,iv:/aUp2glKQR+PrrZgdIA1HCdRdhkA4hqTYwP/Lx0mTXk=,tag:LEMcuruqrKvj8FKUkTT2uA==,type:str]
    DB_HOST: ENC[AES256_GCM,data:Pb8xwcTLH/m3Qj8EScluqntkn66nPmHf9RYOXte/Oi2ySXfj5gouV9k=,iv:k/+xrMTFXVBRDM+XmUXOD9ULA9C56RRBX4PC4EF+eLo=,tag:DxOWw6wcBvU4cfmgXJeqmA==,type:str]
    DB_PORT: ENC[AES256_GCM,data:BSVIuA==,iv:UWMdXiAfYg+y2QSara0/no2yJQt31wnztz+TXClKxFE=,tag:iWPeP2d5jzuZ8pdKdkf6IQ==,type:str]
    DB_NAME: ENC[AES256_GCM,data:jkkgwA==,iv:hPzynv1IZohShBJdzTfpZGMppjRaf42uGZNUic/DYK4=,tag:32Hmm80KiyIPicERjwClEg==,type:str]
    DB_USER: ENC[AES256_GCM,data:zY+9AIT7UXE=,iv:V7jUuPLBQ7mXIKquxCldYoWDtu1R/cmVkzzGuzdK4cI=,tag:yxJAy2O6hV8zFz7czJot+g==,type:str]
    DB_PASS: ENC[AES256_GCM,data:6cJ+Gg+KQRs9qORrSsafPRNjcZacqb09lNQib1ctBCkdnrtyIyjkmAcVyXv4OHaANgD/6xHR4XKwcQ0kVUFi0g==,iv:8tBPpQeXpjzj10IAG0I2vCHkf2uWUJiH/MZnGWvtzTI=,tag:unMlXL+S8Vs8pZWeauyBmg==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3eWI4QkpyTm03dUtGRUZK
            YjRsVWNmOVJTR2d1OWNUWFhPV2MzTGZuYnlnClNOdElFa1JjbG9nNHcxdjFqblpW
            bXhFREg5ZXFVaDk1TzU2VUR6MVNLdzQKLS0tIDBtRUJLZkhIUU0vbjk3TXU0Rk9j
            bEtzUjRwTkIvN3FUdWcvNFM5WERla00Kh8EGIi4yJYfXjLTJqTmQ6pJnxmeUwlM0
            Up+VtIw1FUPIKA61RiGyuxbTqOeoM/uDTcSNlQFK0ouwkWLav9V5Fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T10:25:17Z"
    mac: ENC[AES256_GCM,data:YFhXDI2oqq/YwzI4cya0dSGCJKWDwksacRxkpRtMNppF2nuvINFfKAcSrR8D1jIgmpEDKTvOfMXQVvn/FR2NRS1kCBMZhbW9uoBwGvqJZcZAtqGCsgb0whI2IObjYbkF+dCXv/S0mQEwJ4LoR59+eXYzMsTbRB5JmIq+YPR7+Qg=,iv:KP5HsOzsujUZabAVV4AcKKHnjCl2b382BORCj+4wFsY=,tag:qNqicIBcCxApCVw+lzO2fA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
