---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      qbittorrent:
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile: {type: RuntimeDefault}
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/qbittorrent
              tag: 5.2.3@sha256:4fcf15b7f265c2c8d7bc2a7e13240a07e0593c326f3cf3b5b9bb69eec5b79299
            env:
              QBT_Preferences__WebUI__LocalHostAuth: false
              QBT_Preferences__WebUI__AlternativeUIEnabled: false
              QBT_Preferences__WebUI__AuthSubnetWhitelistEnabled: true
              QBT_Preferences__WebUI__AuthSubnetWhitelist: ${LOCAL_SUBNETS}
              QBT_Preferences__Downloads__SavePath: /downloads
              QBT_Preferences__Downloads__TempPathEnabled: true
              QBT_Preferences__Downloads__TempPath: /downloading
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            probes:
              liveness: &probes
                enabled: false
                custom: true
                spec:
                  httpGet:
                    path: /api/v2/app/version
                    port: &port 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 100m
                memory: 1Gi
              limits:
                cpu: 500m
                memory: 2Gi
    service:
      app:
        controller: qbittorrent
        ports:
          http:
            port: *port
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: qBittorrent
          gethomepage.dev/group: Media
          gethomepage.dev/icon: qbittorrent.png
        parentRefs:
          - name: internal
            namespace: networking
            sectionName: https
        hostnames: ["qb.${SECRET_DOMAIN}"]
        rules:
          - backendRefs:
              - identifier: app
                port: http
    persistence:
      config:
        accessMode: ReadWriteOnce
        enabled: true
        type: persistentVolumeClaim
        storageClass: longhorn
        size: 500Mi
        retain: true
        labels:
          recurring-job-group.longhorn.io/backup: enabled
          recurring-job.longhorn.io/source: enabled
        globalMounts:
          - path: /config
      downloads:
        type: nfs
        server: "${NFS_SERVER}"
        path: "${NFS_MEDIA}/downloads"
        globalMounts:
          - path: "/downloads"
      downloading:
        type: nfs
        server: "${NFS_SERVER}"
        path: "${NFS_MEDIA}/downloading"
        globalMounts:
          - path: "/downloading"
      movies:
        type: nfs
        server: "${NFS_SERVER}"
        path: "${NFS_MEDIA}/movies"
        globalMounts:
          - path: "/media/movies"
      tvshows:
        type: nfs
        server: "${NFS_SERVER}"
        path: "${NFS_MEDIA}/tvshows"
        globalMounts:
          - path: "/media/tvshows"
