apiVersion: v1
kind: Secret
metadata:
    name: recyclarr-secret
    namespace: media
type: Opaque
stringData:
    SONARR_API_KEY: ENC[AES256_GCM,data:P8R6gYbI+ln8sUKSkm72LUlgZWgZp/dwoBnz/sY5mQs=,iv:nKtDX8HZ9q1V7phZEZKue8DfG2AlsBoxvGusXIvDsAE=,tag:eXE57xfIspRTa6seke3/BQ==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:f72uFLAxPJyYR2rGvVRMtr/CgWd6JF+ntGzakf2hdsc=,iv:9lFO1xcbQzOCVhREOAO/VyFZCOnc89kttX6OJ+mpbac=,tag:16sFAhgAun4PWKaGKPuMiA==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibUJvb0VQdXk5MTl3d1dy
            eVJUMFVHU1NiQ0tZMFRaaGNnYUJwMHowNUN3Cm5lMEV1VnM0QzBUL3R2RkcxZFNu
            Z1pzSnpseHBmenpFbXFOVi9jMGE1MXcKLS0tIFc5QmgwUGZBWXd4OUpGVzdNNWhB
            dkFoTUNqeGpzSXAzaE5mNTkwZzJ6UEUKMCyuSKjRDHxrQ6F6nMGVek5++2IrTsSK
            Mq3DkatTr/HhPqknNLrFDvUM/keVIlKhiSk3FLPHIYP/LkTh1yYIfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T19:48:31Z"
    mac: ENC[AES256_GCM,data:OzZCnrgW420UETPqV3gYHDDjDXfGyVz6iT3AW+0SxvPULhTT5dkDruvXOWepJSQ07kXZdjY4AgKrhSQgmHkW4r+7XhvVm2l9RhQ1Wq+eEPTn4uQEu3Mx/mm3s5FZ4B6eyhucrih9hCd2DtwjQDHTU3rg2r3AuhgBJfcJZLXQL+0=,iv:A2vxdF7KG65o2HlF9rJNDcHq5ZF6xw5C3rvxep83vJ0=,tag:QzitgROjVPT69ho16ha1Yg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
