apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secret
    namespace: media
type: Opaque
stringData:
    SONARR__API_KEY: ENC[AES256_GCM,data:1qClg5CsQ7VqtryvCw8zpYH9IpykkWnujwvr0XRzwZY=,iv:tHLUnIf26IVXPgXqq8jyQY3G/2u7EHwOPEf8SZ1j8eg=,tag:30FmgXA0iwdci+iGk2G5Pw==,type:str]
    SONARR__POSTGRES__HOST: ENC[AES256_GCM,data:VzzrvSoTqIwBCiYZf/fOO2xQSJNmYzUUI19Xz6XdrTp842Ie5/miuiU=,iv:xZ4BguI51p8iV9BJIxhgbMHm6V0F2eC4hkq8posi0Iw=,tag:ZxtNEz1ptZ/U1So3v1dnHA==,type:str]
    SONARR__POSTGRES__PORT: ENC[AES256_GCM,data:ZILv/w==,iv:Qgrgppf2f6uh5QklTETGmUn/etVIrCD//YfkbarZ5c4=,tag:h52AlArFncQrH4JpjNIyJA==,type:str]
    SONARR__POSTGRES__USER: ENC[AES256_GCM,data:RIcspTTf,iv:fvlfAuib+qJP/ZaXJ19LgnikfaEeDRyBO1sBtrr3H8w=,tag:n11bTDkWpCTC4wJSQzg23w==,type:str]
    SONARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:UyrlNhXkfxENTmik5++mtRC2XOPlyZ/f2gXTWYOEruk=,iv:Hque2Vw03jLGeDfl1RaQw13P6SuMztHn22IPYFn+48A=,tag:LQATu4NxGua9nLGOIKitFw==,type:str]
    SONARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:BcsGATavRUCBvrQ=,iv:omtjSgj2az0vfT4zgZqKwJxO41gsbfej/hfss4WrIaA=,tag:gEGFVJwyW6649VHDc6sp5Q==,type:str]
    SONARR__POSTGRES__LOGDB: ENC[AES256_GCM,data:3N+t3SPJyoCjmA==,iv:VHHEZTGUKt6LREI9ec9AFm5zyEiNEcT7kWbeQ+cjchU=,tag:sNLlynXQewXUOyEbwhMcPA==,type:str]
    #ENC[AES256_GCM,data:yvbVSMDd50+iYHUgHnM=,iv:RbdDQ0YFfp0yIl9Zjd9r0akcIpgdCPPB5TA9iDXDeUc=,tag:EqCfPvJQmUY9hTSYgEax1Q==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:85QpJ6vH/fEhisu1G91iKk8Th19lPA==,iv:u72vk2OZBiOSOjBx4m8Xm4yarhqn7O21ii6NspXvyTo=,tag:mes9x16SMmoNAuM3EArtRw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:jt0mG5tds9mqmRlW4TbMqLWE0Lbkwh2UCLlmXm+Q7zbPQDOL5IwaJE4=,iv:w8k5ZT8n/8iY9SGtLQ0zwll3VHqLbDebHO7swX13sss=,tag:elPug/M+byd9gzEjTllY5A==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:Qf2HTJB8,iv:j1AQcfwhAywBTVgqzpzO9q1jOnVhCUUPIUOUHBGaEEk=,tag:WJz3VOH89+c0HKBU5vmFmA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:zVXkUID8Eedgm1NbIn0oggVDnAyuv7ElyV6mu0LrDuE=,iv:7xovbsyQr/x7e72URGgQ55ltekdD5DoUGMDSxp15Ssc=,tag:Vw+5gIa0sPo9cmIRWP/VnQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:VatLfKIpEDBfXpDzWz9S3g==,iv:5oo1Klwg1jQBRLvVnL2WfIOJAM/30oPeWPWjGJA4+jQ=,tag:WziQHCybmtYNwSZZ/PvNHQ==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvODlWdmlqWW94cG1QN2tv
            bms1Q0YwdGR6ano1NEsxR25aRVl6dTQvcTJBCmtnQ1I5SzQrdDh2VFhLZENoOFZQ
            bTRBUmIybHNhemZkaU1IUk1PQ0JwTGsKLS0tIDZhRElMQVAxNW5wZy9TSTdxeXhY
            ZXlmelcvZnpKN2t0dFRCQmdjeTI1d00KXuJpIRPbe8tVZog9hx0IsOP92WQHTN36
            X8rHFFdxIc+/oyYIiO09Mc6aiF00yyvkCGolhtsL8WccXWUubDMhkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T10:33:49Z"
    mac: ENC[AES256_GCM,data:u5LxFPknKab8N6lvKI6/Favxrtm3XlkBa8ddiDXN0OSmOCnf+tqvRO4d9h9vTOY6fCZWFHK5SUgQQeqxwDOlG3X96qfaoRaJZKS6FOoMZ6Tvt/ckF2BkkmLcL7MKNtmGeHTVpvBKKJU07oH4E7IbacoSH6Wy7VpBW6KaELh8Xlw=,iv:b4fXuHv6Cp8BOFRGUMQxiztBvL3ZEUv+GgGpZKq1EjU=,tag:nh6J/4OVKYU4buaB0RYdww==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
