apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secret
    namespace: media
type: Opaque
stringData:
    SONARR__API_KEY: ENC[AES256_GCM,data:BN2UwmVVQ1XSzTWmsZti8LHvgJEj//eBbYyJFRcUToc=,iv:iNaxmF9FgLkvDIq3ylxp2H53KDn90KCzJXVfwlWHcPA=,tag:644jxAHx4ztGmdW2UhqnhQ==,type:str]
    SONARR__POSTGRES_HOST: ENC[AES256_GCM,data:0tTYSoBG5M4liW0K7zW/TcRIbd7le5yl2SXoMstdxEGC2lovaFjiC2c=,iv:A0uTuoEdRWU7sy+UaUTD+bjFlP0AQ2j/fZAalSBk5OY=,tag:dINSa3CqJtcVj7fXGZ4miQ==,type:str]
    SONARR__POSTGRES_PORT: ENC[AES256_GCM,data:CkVdvw==,iv:ACj/SamXNcuUX1jQoWWg80AXUFMUdNU9A1QI6VdUEPM=,tag:S4ygSu6LlA8Z54e/vwSr4w==,type:str]
    SONARR__POSTGRES_USER: ENC[AES256_GCM,data:wkADo2/R,iv:7u+7b+4UGDuYa57YnHNx/X/e551jHNyAET/MIYj4TgE=,tag:XJERl0Mh20Y90PorZ821/Q==,type:str]
    SONARR__POSTGRES_PASSWORD: ENC[AES256_GCM,data:mz/p5JC58D5YhZYuzw8gCFLjzYEiWxJTcw07hs4+5O4=,iv:FQP+7dISa+9pwptLxlL3qA7wwSBX4GhqDNNyetOCaK8=,tag:gcvdAgIWPBeh7o7Kc0yqvA==,type:str]
    SONARR__POSTGRES_MAIN_DB: ENC[AES256_GCM,data:vK2Zokltw4/ie24=,iv:bV9wGNemKsKA5zPsE0Fb258uO4pDGy3awvAwmwbHYH0=,tag:IsUHQFe6JRm2d5F8UfkZMQ==,type:str]
    SONARR__POSTGRES_LOG_DB: ENC[AES256_GCM,data:pPhQVwhK7nuerg==,iv:1PMDMiCY1UYZD7JPFi+U5KWoywevXPUfFchFtDL5Pg0=,tag:CMtQ9dTM4aTvxuFfRPxLzw==,type:str]
    #ENC[AES256_GCM,data:bvkjc813WsJVqfP4/FA=,iv:GK77fSlkL4KowZw/cVJgha1DT6zyXYI5MgRSDrUt/sE=,tag:Fqss9OcH8LR9l/Mh+8I4Yg==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:n3KWarSE6vMoj3D0RZihfoUMzJsLgg==,iv:r+oyOy7yloTJzcfkt1KiETE6pmS7n1/ba7JgtO2vmK4=,tag:J2E5HOzdoxjzztc59O+Gnw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:BPSeUI9HdpTJGhJnO9e9zQf3mKqRp/fSDcInYr4secLJ6MRhtGry48U=,iv:099/6y1vkaKCno6Xh64Bw4so42WviCmAdQTDukf/Fgw=,tag:3KtDHQZWj6qquTkWehB4+A==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:72cpxmSJ,iv:Q++RyNo6TJtB5RBTLQSpFgJGF8hlebu0avxA7/H0pHE=,tag:EEi8F9BpXKan26CmO25DXA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:kpFtVbRx1tMCJmzdl2Mg2u/hUC51iwYgFPN2I2CM7Pw=,iv:CCV3v0gTa8JKXLkIjqjAYNgWAjtOsNChQCQoekGfpjI=,tag:v7VPL29Oyip+LQW+eiJQVw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:wyNHaZfBvMOgNc0hgMRDxQ==,iv:2F2hRsYARFi3lBB167G3gR79f4kJwJrjiKASsU2CmMM=,tag:OieyLZtynhJCYfUr+ShORg==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSUGpSRjc1bDRWYVdGZU9q
            MUJZdjU4RTAwOWt3Q2VEUkVkTis1b3pmOEcwCkFOdFFWWVRlQUV4bzRFQWtZZFlh
            NzkxYWwxL2hiM3YvTXRYcHVXK0U1RncKLS0tIFhaaVVvYWhUUDRtZW9GdTF4VHBG
            bkFuQnRUQzZVbGJQVStISHFvUkRMZDgKCkmFd5zSYTBn6suCLh720iFyN+YXjeCa
            wAaGHS1CH2v0cplK4uiL1DF8ps5f06b4MeUdBdtz6qmD5/XdS/ex1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T09:55:11Z"
    mac: ENC[AES256_GCM,data:TEXG5qXCMnMrHqnGNDLkgsWsNu1APVaPYiHN/tE7gwkhZYJ5LBmgHcWqGMB11YV7cfumAAywjoxTHvSLTbSOdznUdC8oAN9EMBoRZK5BeJO+C0eX7d16M+bozX4E6vYYJr1hirk5O9FAJ/WGPypGefE96Wab1FbQ35DIWvbjPNU=,iv:h5XcU1mVlaFkhCrobSMIinLTdRXnSh6ahEcLwv/xDfc=,tag:o2m2Tpaar7FEhq4EzsJgKg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
