apiVersion: v1
kind: Secret
metadata:
    name: oxicloud-secret
    namespace: default
type: Opaque
stringData:
    OXICLOUD_DB_CONNECTION_STRING: ENC[AES256_GCM,data:hjPaLzOurRuFENTDpMazbRLSyGhzrRxtVkXqP+4/j2J0Bp2p+l+LHvsVpbyWnxpQTu4vKjalHcEHnZnEH/SHL4Y1VJXOq0I9s61cIUQyDZF/BUngQI19awydN3sgBq1elpksB1K8saQNH78nd/F5X2Mszb22UDJwu54cI/qF,iv:SKfMIFujAKCUo5BQtPWRz7w1AN/9PNyDm+8fec6R4tI=,tag:Uvqv1U2hZ4KokQMUh/zCBg==,type:str]
    OXICLOUD_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:F2DSu+TzydtzGmlvYFehJKjj/JKgKOby6488CI7V2TE=,iv:xAiTe31ypRpjQIjKp4dbKc1iUO77CiTYJp0KMp2Cak4=,tag:07xauNxaEsMTOD2CB2mouw==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5YWtpMUdlVEpoUEs3SGlV
            VTMxTnRmZ0tKd1lOUzFlaEYzeEJzRDd6ZTNRCmZSQ2RBekgyWjR3WGlkY3hYMEM3
            R1NDSjhoTUl1ODUzQ1gxKzQwQU9GcEUKLS0tIEdGQmhtOUJBb1Y3VlNDQXEvSzJq
            NUtzV1BsZjBUU2d2NlFmdmx6R1NaVmsKTxbJbl0c0Jc4i9HLwTW/WwQU0ouICOu5
            ugu53Tn+LE5VEr1Iip9eQXvbsBqDkQquDD+iRxWCB8wVvBYKDNE+bQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-30T06:34:08Z"
    mac: ENC[AES256_GCM,data:R8AtqJN5ZCLKazSAS4Ig57hkiEGeZ1TWE9Gfw9BQQ3TnwTd6CQFETyEbRXxj3H0g0KPrIGtPOB5oyuwLn5SaRqB5Y4qA7g2ACtJulG3v/OQBM1lt9ZFF5DMDltKTaQVasYktUgLWnrSdjTmKOceVnZYySS5IGEn4X8hOHUoAguw=,iv:tVksHvC4rspZ2Vnix+lWCiVdjWrnW+pckC+4PTjieNo=,tag:PVKBRvNmKIlkdWPAngxtag==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
