apiVersion: v1
kind: Secret
metadata:
    name: oxicloud-secret
    namespace: default
type: Opaque
stringData:
    OXICLOUD_DB_CONNECTION_STRING: ENC[AES256_GCM,data:tKS+J1RsrwvawA6Pa1Zkb5XcRVGDYvVYfITm2mDO7nQGGQPXEkzuKS14CXB7YHwwvMeWpHvEsqkPZNSFRc8cKIj5s5pDOCkXS9SPvzDWMo5oasyUqhSIjv/KsJXhE/gRDhK9hwOecXzrWwHSaAZGXQYaOC69qP8NpOqS5hTZ,iv:ugbNsfLscOMe1Zetr0MvgzbyDGmmZbZh3Uqz1zpEx4o=,tag:TB9jE10EBoS3mfDAylLFWA==,type:str]
    OXICLOUD_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:nOFJE+SHHgIm/IPVZr0DpM5vTpfYW+IYC49oufZ0PXw=,iv:1POPnkBMXNK5d/ii2nv67qy8SmSMRjGsy5hzpgYev/E=,tag:z3wuG76qjusICdR5lxKcHg==,type:str]
    OXICLOUD_STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:zUq0SgCupWJ/5vOOb7IKJrKjMQdkXZsAuvC9ltLb3drTjhUJDVfGJY78/0Q=,iv:C0HxdWOsfG7caz6LVAUd2oy3fczaxjjKewWwtaXjaVw=,tag:mrYCt2SaF1TRrr4/FPnglQ==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUS9rNGNGYjRUeDEvL3B6
            SktjQVVwZWw2WERuNVJ1KzdLUEhvWjdGd0JRCitmTWpsTzlEWExIcHkvQ3pISXR3
            c0tDTWc4N2MxclFBTlcxa0hPcmZmMWcKLS0tIGFFelB4eHRrUENSK01jcVdFNXdE
            OTRia1JDU3JTby9pU2lmNWRURlRsaEEKqe8XkNNXPYRYy7QAWy4gx++JVcXpicY2
            2IKAIymvEuDrQX1MbUyl+mgBg2bXJ0NR0GEfcpfwAUSTxbhQPs15cw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-30T07:49:00Z"
    mac: ENC[AES256_GCM,data:9+xHFWIffWzhq2teDgqUf39TWXt2uoHQ2Z5TN2uVVll09CyD5SfJO9SgLPq8DZpzJCJFXNHMSVIYtT28wDjbmslAB5oLlsYSOjUYprdOEH6wSWPfLfjTZFbYppTpvcoFZkJ19a1bOOL/6ExvfpOdLnovCPMcnh8zjkYdO4mxv6k=,iv:PwRItHN9mX9x4Grol2794U+1EHtAsBhPfvI5ZgIhINI=,tag:VqCmODK3BvRK2xYLG0B1gA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
