---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dead-mans-switch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dead-mans-switch
  template:
    metadata:
      annotations:
        configmap.reloader.stakater.com/reload: "dead-mans-switch-config"
      labels:
        app: dead-mans-switch
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - alertmanager
                topologyKey: failure-domain.beta.kubernetes.io/zone
              weight: 100
      containers:
        - args:
            - -config=/etc/deadmansswitch/config.yaml
          image: thiagoalmeidasa/pingcap-dead-mans-switch:latest
          imagePullPolicy: Always
          name: dead-mans-switch
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 300
          volumeMounts:
            - mountPath: /etc/deadmansswitch
              name: config
      volumes:
        - configMap:
            name: dead-mans-switch-config
          name: config
