---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dead-mans-switch
  namespace: monitoring
spec:
  endpoints:
    - port: http
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app: dead-mans-switch
