---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dead-mans-switch
  name: dead-mans-switch
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: dead-mans-switch
  type: ClusterIP
