---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dispatcharr
  namespace: media
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/backup: enabled
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
