apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:HbM5yp2XUuovCjJv1O+Yb/EzWBlMzbDWSLCjxsWrU2VhNStbqw==,iv:sCYAZaSUabBx3yCxNUJqoGB/ESb6H1vn9+jkbNZh0nA=,tag:Y5Yq4KtjTsjsm0kIbXhOSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVzd2ODJqdGE5SE1UTitk
            RDRYeWpsT2ZHRmkzaTVnaCtYcE45M3paQkZjClBISnVLVWp0NU9zaUNlMGhIM0VJ
            NmNYQmdVNUtCa2FmRmJhaU9UQ29BUXMKLS0tIGlpUzRLT29lNVl6endGbkR0OENL
            OG5FUHM5bkNQanJuK3FKb0NTa2lxVHMK+xSCmKlDXwg3zRml3fykoYe+UrDNyyvA
            +n8JIilQRt7+tUnvC/7VquQNYpcczUcib/4botl85PD8RjQdBkyvGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-20T13:22:33Z"
    mac: ENC[AES256_GCM,data:ocYiTGv02rbA6vuELjrRytoPrcIDY4BaT0DkexK1ZFm7BGQ7rjcPB5zJklpQ/3A3s0yWhhBY46Jptjf8yNKFioNFPt+OWCBkuwJXNZHpoKBEk2ec+rq/flR9Rv0KORfmO0s+bQ32ZM4NfFyBUZaHvA6UuOAxoA1Yygr1WPd7Dd0=,iv:C8+mKvuXGd60AecYztRhyKgOXOoecngYnytn2qtmTXg=,tag:OTrMLPG9EjPW8pvq2uMKqw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
