---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app pingvin
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      pingvin:
        containers:
          app:
            image:
              repository: ghcr.io/stonith404/pingvin-share
              tag: v1.11.0@sha256:1c35387f112570e51cb9541b6653a3d59b5082f8d9bbf475299fde4c27555e82
            env:
              TZ: "${TIMEZONE}"
              TRUST_PROXY: "true"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: *app
        ports:
          http:
            port: 3000
    ingress:
      app:
        className: nginx
        annotations:
          external-dns.alpha.kubernetes.io/enabled: "true"
          external-dns.alpha.kubernetes.io/target: "ingress.${PUBLIC_DOMAIN}"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          hajimari.io/icon: mdi:account-arrow-up
        hosts:
          - host: &host "share.${PUBLIC_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      tmp:
        type: emptyDir

      data:
        type: persistentVolumeClaim
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 1Gi
        globalMounts:
          - path: /opt/app/backend/data

      uploads:
        enabled: true
        accessMode: ReadWriteOnce
        storageClass: nfs-provision
        size: 20Gi # ignored
        globalMounts:
          - path: /opt/app/backend/data/uploads/
