# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-secret
    namespace: media
type: Opaque
stringData:
    PROWLARR__AUTH__APIKEY: ENC[AES256_GCM,data:xAbj2J5pv0lAH/x6YeSRMh98I7QuDW8stLIm5kyrF/I=,iv:AIUcELh78+u+2E4pODuEvstE2UDGsEJn2tiZOm+rKgc=,tag:Z8/nsLogjLImojgB4E/1MA==,type:str]
    PROWLARR__POSTGRES__HOST: ENC[AES256_GCM,data:Oa20MP1jbwy68SB/+nJ5TVASUNaFMg2GDDR42OS1R0PlNs6Ia/C5KQ==,iv:rQYq3t8i8w6uEi29xUg4pQ+R7mnkHkKaxxwj0WpBZMU=,tag:vP33bHl/od0ZkXgkzXTHWA==,type:str]
    PROWLARR__POSTGRES__PORT: ENC[AES256_GCM,data:VTRX0g==,iv:XvVDcFAO8I3zFcsZGEpbayrN14B8j7Ai9VcB313jG50=,tag:eL8UWPVILlRA8l5wHWbVkA==,type:str]
    PROWLARR__POSTGRES__USER: ENC[AES256_GCM,data:FnKgoup9MSM=,iv:3qVzCuS+H2Ag3OxPQJHYSBsreiMoz+3JTt44YhPynqw=,tag:upySL/+YZ8XRGpxFfBUC2w==,type:str]
    PROWLARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:wjQejhIDSTzCMl4Q9BGKVXQ6yokV+3gr80/i1asOjtk=,iv:PivauLVqwFxBhxtJKc2scFqQSwldeDoGTUJbfVwCkV8=,tag:QaGp5gxlWcPOL/S9+F+/sg==,type:str]
    PROWLARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:l8FXCNy9AJTjG8vwnw==,iv:fteu7i/Ss3I4sNXrmL3pu0WfB4qLXUYOMP55jHceT1c=,tag:jotf2qLBRTcmR83EHblC/w==,type:str]
    #ENC[AES256_GCM,data:aBG+9/f68YpXwTduf8g=,iv:uk7Pz16IPnEGmgT12AvPOmnhOqmSjsrzDiRNzTvozJw=,tag:f5bxiKxV4E2VmOqMR3fnqA==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:Dqn0MuPXV5uviWPG8w==,iv:xBRJ9vYepMI3KG7uTPSB6Zjohs7+TRcHwWQjtM4rTsI=,tag:6hGZk4v4LVuoloRH0w/neA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:zUfe+XxrowaOVWVcYRrW91c7+s6aa2YcJgPE6cWa6SJn+TSUqe6m4Q==,iv:dD5omSy6bJk7cQ9pQV+ylkvqACyWcN6SDNe/c4kFQNU=,tag:9hVuYafAYRDB7pU0MRpLUQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:kG0bi5heyvk=,iv:yK8tjjHGnzNI1m7ReBTXO+yTCMBQleeGbQiKD487MHs=,tag:xTf8OK+y1qY8XAw1WeAHfw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:p3jgxq2kAcZEUGEDokxrp22Om4LWFvTjZoZqyE/j/E0=,iv:RGapU6CGSb3is8KcYZgqQxfqIAmx9nXv9stsBaPMIgs=,tag:9Svsw7uQpqouRXIVNwitMg==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:UJcgPbUbGXfk9dvsMHz5BQ==,iv:37Tkmwzhgh4YfPPfLUTieqknABAn9MSKixhVSe4ivXM=,tag:V+vczY27tld9zE/7qmTfnA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKYm95ZFV1MU4xMFFJNTZn
            dnMxUUNDbGxINUFPY2R3UTlqaEVneHpKYXpBClZKeWdLNmxiazVyWERrOURuN0ZT
            YkI2NDlNUEV6NDhPaTk2OVZEUDd1ZDAKLS0tIGhFdnAzUXRoUEphSTc1R2ZSeVVo
            VmRGeitKMUpiRmVtYjhsSE1EMkp2ZVkKU00Lg2Ilgwd3gDy/tu9QAA2LlPGscsfq
            lqymord4g/V/G4I4S91RE9L3rKesCyjknS5wOjvVWmLCeLuzGelLCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-22T12:32:06Z"
    mac: ENC[AES256_GCM,data:lGxCmE7SgS1Z5CCg481T4phBWYWFIj+SMUc6jBv8pKXyR12LqrCX7AXpyhitSiOSAE1jboBiHlBUBv/nTY31XC3yYlQpvoABYJ34uHEHfp1L2Le4YLpiyHfXQfq7X0jz8C0PeZrx1AFZSnsarb38x3FJ6EjYkijiVRJeqPeNwYQ=,iv:HO0SVefWsGXKGZ58PSDiZPG3qdYvYgviJuZQ86QEwjM=,tag:MYspPD/4GwxkthHwkH8+uQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
