# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-secret
    namespace: media
type: Opaque
stringData:
    PROWLARR__AUTH__APIKEY: ENC[AES256_GCM,data:Sp6kB5Qam7Mb6Vc3VbxYEqh9DMZGYyu0ARQxbpIGvZI=,iv:aulretQ3F3cwbbzIpa5pJ6LHBNJOX5YXgwFIAkazjmQ=,tag:Si8GNrk/kFHRu/S6ybAQIA==,type:str]
    PROWLARR__POSTGRES__HOST: ENC[AES256_GCM,data:Jhk9SZPJzLiiPIIEj1grdjexasfMumXL8U3SAoXYBAJOaJIHB720W+E=,iv:2CXwcttB7xV5/LG42kj3NJc36qMqNLCS/9sDBMlTK1M=,tag:omRA3NOWgfJOrtRfTtSjrQ==,type:str]
    PROWLARR__POSTGRES__PORT: ENC[AES256_GCM,data:PfvBIg==,iv:fwBMk91bFWF9pXEiBSCyj0hVTp17o0pXUyM5zqKkOgY=,tag:A3GaZiTyiiuGk8+hRAjuTw==,type:str]
    PROWLARR__POSTGRES__USER: ENC[AES256_GCM,data:5bIOhyRGgIQ=,iv:fuB3Q9KwzXmpm0V8CffzSHupJ/Via8u18BWTiqRZ5Ig=,tag:hiU01GC7vLl2EJzGWCbWGw==,type:str]
    PROWLARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:dNhD72bW3GybWP4WD8zmb3Z4i9Ye8pLJIL+q1iwChwQ=,iv:VNikj5tkToAgsCCcmtcfpE/lz6JxXnjd8m47RHe0pLM=,tag:cO1Q+tfcJg57UCqCfn9xXQ==,type:str]
    PROWLARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:D54CgEW8JykaMvwrLA==,iv:Q7/h6d8Lq0uVPF1tXs9MqyKgQb5YXDE/ug7nqkGZkaQ=,tag:4nPiXajYtZrC6FWySYrDAQ==,type:str]
    #ENC[AES256_GCM,data:vsR8Qj0pT4jk6xnVVn8=,iv:Tc0K/m6uiiv62xLoMlEWSsaNc3hx9uJoinNwNa8e5iM=,tag:tC+Dx6Q+Ze8iPOGbJ5MbGQ==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:ldzLBDvSlwrZs2EHEg==,iv:J89HWWF4/mGIeyxAPKDNzhuDSBxMC5WgOAXKUxudsvE=,tag:Zu7vL5E+g2NSLqggnZQ8vQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:wY9Rd4nAgwLk7v6V7uCyvnbh+bQEbx8QM0q3uRME1wvSiznKWBgIzfo=,iv:+9AluKq0FzCqCf3Dk5BoUaMjheuUB2DR9urXBV5oFMY=,tag:7XMi/FuO6l+vgUKMl+G4Wg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:7lj38zieb1I=,iv:K5ikvqePEjzHE4yNSLD6CSo13a5ljGkM3pdm6FFRNuM=,tag:E6aV2rELbH+lTSlGyphz3g==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:U16RuC08qTFL03QNd3dIe+qQd4IkXWM/mXArLGucbck=,iv:e6FCw3NC5R//Ortaaik6jr2WvNb7iZ75wS4NRD9WlQU=,tag:4BlxrmrDn3dqfz41TAmOZA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:KNg/8fu16cpaa6kq8UExsg==,iv:oMr2edctbHAkXQTAxlR79WJ2dC6bjTOF/ZJDhrr/kps=,tag:nk1wBl5sk6xeKvYaMqWUbw==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSmZpcDM0c2o3SXJtZFRh
            bURKRnlZYmV0WDdoRmRwRzk5bFBOWmxERFZzCmxnOWdIVkwvN3Y5citwRDNnenlu
            ZnRXM283RjBFT0tyMkJsaTNiRkN3U00KLS0tIDhoeUh0UitGa0UrUWd4R1huelFO
            Tm1lOTcyVTEra2FhM25vaWQzUUZEQXMKZos+BXUsVyj+6C1/CQNAO9Bl7xe0Fltn
            a+KsoZxKkFD3WRorJQDvLWVtSkHhoRvyAClfz8qyxljCMMqQMYyARQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T09:55:12Z"
    mac: ENC[AES256_GCM,data:arOO4c1IFjIxNOSgWHBwT/NJ3NmcJlQZCQfIm6nCisjhey7skNrbAy+X0VylGaGJwXibyW3lhqW/+avf1aaF628mJ6duEzLZHN5fV/GiVaz4d6BKERA8Rm2x9sx5e8p9Dl2Pl0so35+PvjSuDXzVxVmpn039tkKnKl+GKlajZP0=,iv:dEoQbDDHNzd3kgMmADD3sKcOgLniR+wcQWoZ8W24JD0=,tag:krViFlARgRQyRxplBhZn8A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
