apiVersion: v1
kind: Secret
metadata:
    name: pocket-id-secret
    namespace: auth
type: Opaque
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:vR986hgIRqGdjk7bb5Bo7/LXKAF9jAKv3fXcUE8FEGoe7V0xDeJtFm9N8gE=,iv:olfj5xySLbEelO59N+8Z3TycmYWFwQlPcxuo3P/ntZY=,tag:ymTlAG1g9LVFKJLf1fmfpg==,type:str]
    DB_CONNECTION_STRING: ENC[AES256_GCM,data:t6fZBdvYP8uUXK4HY3YOd9W6L9ZuxtimsLL9xDNp8+BCYbLxHNnp5b1bAjOAx7Pg3Cb06l7b9/RB4E1893+vdd7BRNZrXxHfz8v0pPXigbk+CvTcIQOQxbvRGFPlg3ZX4HAxjS5n3vv+G9UK8KVeatw0Hzex5HmOW7h33CaIh15WFoPri2zQ12My0w==,iv:FoHBZHPmbETh5V6WEy1ZZptLFNqgMUfvT89G+m8F+NE=,tag:Z8Kwave6Wqew5FPtmX2yaw==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTODE3dHk4b3JlOTUrdkRG
            OTBIR1NiRnpXeUREZzFsc3AxV0lmWERIZUgwCi93bjVHajJCN2xITjdraUQxNnZw
            aWhiMHc1enBUQnNXRTd5KzBNV0RjQU0KLS0tIFk2Vnc3UnZtdVBMWWFSKzJUQkQ5
            VE5CZklWUkhUWVQrWE9EUDhaZFRCZGMKPog+MBuST6llfBbOMnv7n6qBDOsdabkJ
            kehpMMeDI7w4dEIDd7ulu9F7wQL0uLjeWlFZxYvYsr4P7yXgXf/Oyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T22:45:17Z"
    mac: ENC[AES256_GCM,data:udPTFAS5SC6EI3ro+JzufXKCCrvSJ/8v531getKLo/9sDXX8a4qXC7URAlUz6gbYRXuCi1dG3YmVk0+0CAdgi7ENNjAfQqlgV7/qLsPehPqsgdlhQExrC4OIhslAHd4IL86MOu9se7NXQsMeD89XWoIk5A4QuelO56Q5rH//2Zs=,iv:M7u8iPcjIwMSXMIwJRRvF5c9zqUE50PdkI8J+BV6V2U=,tag:ID8XR1+RadpFZKmL4EieYQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
