---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app kavita
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 5
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/kareadita/kavita
              tag: 0.7.9
            env:
              TZ: ${TIMEZONE}
            resources:
              requests:
                memory: 512Mi
                cpu: 10m
              limits:
                memory: 1024Mi
    service:
      main:
        ports:
          http:
            port: 5000
    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: |
            10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
          hajimari.io/enable: "true"
          hajimari.io/icon: bookshelf
        hosts:
          - host: &host kavita.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    defaultPodOptions:
      securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        enabled: true
        mountPath: /kavita/config
        storageClass: longhorn
        size: 2Gi
        retain: true
      media:
        enabled: true
        type: nfs
        server: "${NFS_SERVER}"
        path: "${NFS_TV}/ebooks"
        mountPath: /media
