---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.1.0/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app photoprism
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 3.4.0
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  # See https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
  values:
    controllers:
      photoprism:
        # nodeSelector:
        #   intel.feature.node.kubernetes.io/gpu: "true"
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: docker.io/photoprism/photoprism
              tag: 240915
            env:
              PHOTOPRISM_STORAGE_PATH: &storage /photoprism/storage
              PHOTOPRISM_ORIGINALS_PATH: &originals /photoprism/originals
              ## See other config options from PhotoPrism documentation: https://docs.photoprism.org/getting-started/config-options/
              PHOTOPRISM_SITE_URL: "https://portfolio.${PUBLIC_DOMAIN}/"
              PHOTOPRISM_PUBLIC: "false"
              PHOTOPRISM_SITE_TITLE: "Thiago Almeida"
              PHOTOPRISM_SITE_CAPTION: "Photos"
              PHOTOPRISM_SITE_DESCRIPTION: "Memories"
              PHOTOPRISM_SITE_AUTHOR: "Thiago Almeida"
              PHOTOPRISM_DATABASE_DRIVER: "mysql"
              PHOTOPRISM_ORIGINALS_LIMIT: 4000  # in MB (default 1000)
              PHOTOPRISM_DISABLE_TLS: "true"
              PHOTOPRISM_DEFAULT_TLS: "false"
            envFrom:
              - secretRef:
                  name: photoprism-secret
            resources:
              limits:
                cpu: 2
                memory: 2Gi
                gpu.intel.com/i915: 1
              requests:
                cpu: 1
                memory: 400Mi
                gpu.intel.com/i915: 1

    persistence:
      config:
        accessMode: ReadWriteOnce
        enabled: true
        type: persistentVolumeClaim
        storageClass: longhorn
        size: 7Gi
        retain: true
        globalMounts:
          - path: *storage

      cache:
        type: persistentVolumeClaim
        storageClass: longhorn
        size: 7Gi
        retain: true
        accessMode: ReadWriteOnce
        globalMounts:
          - path: "/photoprism/storage/cache"

      originals:
        type: nfs
        server: "${NFS_SERVER}"
        path: "${NFS_KUBERNETES}/photoprism/originals"
        globalMounts:
          - path: *originals

      import:
        type: nfs
        server: "${NFS_SERVER}"
        path: "${NFS_KUBERNETES}/photoprism/import"
        globalMounts:
          - path: "/photoprism/import"

    service:
      app:
        controller: *app
        ports:
          http:
            port: 2342
    ingress:
      app:
        enabled: true
        className: nginx
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: arcticons:photoprism
          hajimari.io/info: Manage Photos
          hajimari.io/group: media
          nginx.ingress.kubernetes.io/proxy-body-size: 4G
        hosts:
          - host: &domain portfolio.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *domain
      public:
        enabled: true
        className: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ingress.${PUBLIC_DOMAIN}"
          hajimari.io/enable: "false"
          nginx.ingress.kubernetes.io/proxy-body-size: 4G
        hosts:
          - host: &public-domain portfolio.${PUBLIC_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *public-domain
