---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: photoprism-pdb
  namespace: default
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: photoprism
