apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-v2-git
    namespace: home
type: Opaque
stringData:
    GIT_REPO_URL: ENC[AES256_GCM,data:mnff6Mf7zrd2Qv1K9kqfRPf1goIRGQEiqp41jhwWp0lXuCE3gC12neJPiXBwplYNt0eFeN4=,iv:/pgTGE70qePVjARgPzMeSJZ6wZqkdTrzAAAFWm4WtDw=,tag:avF0k/gMnfhAhMU/iFJwFQ==,type:str]
    GIT_BRANCH: ENC[AES256_GCM,data:D3Y+1g==,iv:1vQ/WE30TF8+O5DzmF7fGPugwY0jRxYloLYXM+3rJlg=,tag:xKtv1dxOg3LtxGT2cRUR7w==,type:str]
    #ENC[AES256_GCM,data:gL8ufGwx3V/KDinxAMQ4tfqOkPWzqJ6czU87MajsWI/+ANdZ2zlStjAE2aGref2TLYib58Rn+t8Hfxz9mRbX8z4kQzLEdoalIQ==,iv:UQx1TeG76PDRguqjsKbYc4yKKyqdsUvYLOpSeC63I/4=,tag:wR5mzC2/gBuucwuC2hG9lA==,type:comment]
    #ENC[AES256_GCM,data:dkr4JaSSZcurv+vmUptfLbO34/w9UK3qZo6lvCv40Jov9QNhvXIY1xNWqbA4DXc=,iv:chlwVnLEBjYPpH7Hvx2Anpxr08sE7s7p3fXVCZjWBDc=,tag:aK9FEb0GxFjYinXSZMIQBA==,type:comment]
    #ENC[AES256_GCM,data://rOlY4kkT7wEyrFuVR4jiO5xSROhKlnQVMaAJ4tdZrJE8aRjNDzuAbYHjGLgp+StiXQGKXcj276r+m7cwBmrotvUToITz2dp16PPw==,iv:5vpvB4CBV01yA9M8XrFggGB9N2zHQqawbTShbsD7RHY=,tag:Fw+Kl5o8RQxq4n1vX9fHOg==,type:comment]
    GIT_TOKEN: ENC[AES256_GCM,data:tdeFT7d1gc3UiAOtxgpVFSD6l37AMZptekEi+GQHnHry6u+Lr4EXCjIM4jVI9sBx7Wg6atXgXitZYXsM+/YsTtGEzp0P8xRb539LIvsicHUk2+B8LbX9sCHhztIn,iv:8zuVmI42VmfHVWvg8AMLbUv2MFTBwSX1QXDJ931HNoY=,tag:pLGvV1w6cACSmTrw4StVLw==,type:str]
    GIT_USER_NAME: ENC[AES256_GCM,data:bPKHFkJnSFlaJ+Q=,iv:loNVqkYz8DPl2u9oDtmAzxwyUPL9UZirzwDME7nIaGE=,tag:9lufXOw0MvoiGpLrOR61uw==,type:str]
    GIT_USER_EMAIL: ENC[AES256_GCM,data:yTNrrkoKQ0XHc4VNDRoUWelmxWQCHtzTqNeDHcsUtmDizAy8uVieaiFnA2IHng==,iv:OtFh7v2llQII+g+cCdv53RvrBkmuzk9nsRlmmTDuRyg=,tag:KsuXDKzdSUaevm1oie2+wQ==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVa2xrVDB6R2pUbCtTRWRE
            YU9oR2t6OG80bk9uYVlaeGNTTjRLeWZCL1RnCkI3U3dkblJwNkp1WW5MR1QzZFo1
            S255aXRtcklCcWdUa1lqZEJTQkZweWcKLS0tIG8wT0FwdklnZ2o5TzhjTXpGOUtx
            c04xNFBENzVEQTlaTEhRZlRnVmhRS0UK5k7VHzWogObNwk2DtJpWuUdTac32xX/O
            b8YyFPrQ4qMxR6OtEjbj2gp+hUUDBlqoVvSrwRo3Nnpp6ZqMjel9Ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-30T18:12:05Z"
    mac: ENC[AES256_GCM,data:Zze4VyVROkUglOa9A97aO53YTk9UORDVjnv4jshk2eBsx7oi487x03VE492NRlod0MbJd8qBykie7oG/TPXr2gyexB7N83lLTi39IG+OwCuFm/n7RTqfVnslHC8gRK2JetMsymCkBUTFqhRaLi3q5skha7rIqPdcKLqYa7LUX7s=,iv:43oiHyZN+9qvSDTlOB94x2IQvqRkpa8VXmIMSnP1Qs0=,tag:tgDgumwbJ5TAmJVHZBNyEw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
