---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - ./autoscaling.yaml
  - ./git-credentials.sops.yaml
  - ./hass-v2.sops.yaml
  - ./helmrelease.yaml
  - ./httproute.yaml
  - ./pvc.yaml
