---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
configMapGenerator:
  - name: grafana-dashboards-radarr
    namespace: media
    files:
      - ./grafana-dashboards/radarr.json
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana_folder: Media
