apiVersion: v1
kind: Secret
metadata:
    name: radarr-secret
    namespace: media
type: Opaque
stringData:
    RADARR__API_KEY: ENC[AES256_GCM,data:bE5ZWfaa2G4FY/Gtta+YRNxsSR3zzSkONDMlsQ+S250=,iv:k7ujGur0Qol2na+TZLhqQ66kVC6CexcP3+bIb0WmBBA=,tag:dcFxHCo/y18IY8kWUYewKQ==,type:str]
    RADARR__POSTGRES_HOST: ENC[AES256_GCM,data:xL5KILUb5WWJYwFSSng+wdkJQU2QfqnnYOQqa2GnBuFa4dOK4ih1GS8=,iv:7JK6AahrjzkvCYihgzSjIZjPYO5OhAcKcByDApzcXmo=,tag:Nh8OehqbniEaGTBwOmarFA==,type:str]
    RADARR__POSTGRES_PORT: ENC[AES256_GCM,data:jjgdDA==,iv:Kw5Dja9Ttnw80AXMaQ9a7wvZ4lfdDdQMlmA6+sy7WVA=,tag:ELSiN8FMypMx9LhAotXZTA==,type:str]
    RADARR__POSTGRES_USER: ENC[AES256_GCM,data:R32URLmb,iv:fnGedip6SLfaxv/ZLa0tJTRQA3QWvwdC5R5jijCcnm8=,tag:Jmo9MdYYL4FBubKE+Y6A/A==,type:str]
    RADARR__POSTGRES_PASSWORD: ENC[AES256_GCM,data:2AtdfDO7b8yUjEo/MdxV3CubV36SpQKmO72TsIcT/AY=,iv:wgPK6o7CDhvjZHD0Kgd0DmqyF7x7jcJbGo5MLRSwKl0=,tag:hlsJTdCJeqSnT7NeDx5WmA==,type:str]
    RADARR__POSTGRES_MAIN_DB: ENC[AES256_GCM,data:oOOdraGPBSJxNjw=,iv:zDMV9b/6JIg8aFhPCxLKNjnZ57bBpEhJ/vtGEZTBtl4=,tag:alSduoF/ut22Nn+UDo4ikg==,type:str]
    RADARR__POSTGRES_LOG_DB: ENC[AES256_GCM,data:o3RWwiivP5rxsg==,iv:b3BKO11JJDnb6jrgyjVB7besU9ncZyXaezApCkv9V4U=,tag:xV12mRWtjFNulOHY2vVfkg==,type:str]
    #ENC[AES256_GCM,data:PnzOvLBnGDTc0U4Fe8w=,iv:iHlxnUC48CS7acqYkkI2BFZthgIxAubJceJ6GScnSlE=,tag:LaQZ2cUCqlMLJWR7uNVtAw==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:2X5AREMKh5ptPEYdpW7ReowMpDWXTw==,iv:iwEYTEKp+YFz7+pyauqM5wHm2+neJ6vLruLiOHiEERs=,tag:NnDfjn7Qwcl71pxAaFuuow==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:/54tF5J713XF5OHrzo2iu4+3uUpYAr4EnqqcHBH4PnvRU0JbBwq5EtE=,iv:dAwDZ5fDxPvkLhGtQsguD8/HbuSq8g4rgQlq07dnDpY=,tag:fE4sZo+UILr15wCCn4hrIA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:ddQfoPOK,iv:G/0Bf57mr2dSZzDu/Ltw5x7Bt4NUQ+T/aziCvYHORuU=,tag:cJE2CIzNbzuYm0h8izDk0A==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:kv6zWtUa3FXaHaygi2O7Gd04LCIR70Tu5sOsP5Youxk=,iv:+CGHJMl3ezgWFbOyJphG7mBT+Qa6kDqrQ4KuqXIYQO4=,tag:oWF2AiCM1NBrqET0J1q68w==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:08yKeuIbmc4KuWVzi3eNKg==,iv:F10Unr3iCWIKs2PMqFo0hitX1uHnm7DpFZWx/UDdoCo=,tag:5zIvOS2i9zWlPN7eFbXgeA==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSN2ZST0d4SStDcXczemhB
            VUNob2NDY0ZDOEF3cXhSeWhJSCtEelpFVnh3ClQ5aG1icVFEUVZpaUFCRXpzOGZ3
            Y3MwTEN5R3g5eWd4ZmxNUW1VTFdpdlkKLS0tICtZek1Nam5lbUpoMDJTNFJWRGd1
            em9YdXZvai9YYVk5M2xDY0pGenJzQ3MKaIFrxEaceWgB31azhQhSZQ9QSLZaVqgt
            y3dJTyyDOCpm0H215OzsueFHCBLMwdHyq+6i+4QXEpeEeN8kmR+nBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T09:55:11Z"
    mac: ENC[AES256_GCM,data:LRQxVyF2TIcgluMweUbJUemDkiZnxa6JM568CB1+jtv9Wf/Yd5DWBbldea3hr+Cx1U5Ykv+eCrh2QiklM7LZnxyfGkrwiNtUyqG6nMYdxxQ4iwFbdp5obBjFVPSCzjEr2dUAgjLS+AVX7aSc2+8AoaXEiuw1cFG5zGLeupM0M28=,iv:/Qfbt4v92GFyfjtr4W0JnODbYiZUBCS0bNV6TU4DoM0=,tag:BUM/m9lc57zrXgFpd+EfJg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
