apiVersion: v1
kind: Secret
metadata:
    name: radarr-secret
    namespace: media
type: Opaque
stringData:
    RADARR__API_KEY: ENC[AES256_GCM,data:gxbio6fNgsjjz1jpED6w6sBZrgI9L+TQEUVHUK9DB0E=,iv:UyDWx1mSLELFkxyNUrcsqFxdeAuQyGjvWRkCO7MLxeE=,tag:JzKsyNPHPjqLo4VDdm1ZtQ==,type:str]
    RADARR__POSTGRES__HOST: ENC[AES256_GCM,data:2d7EYcXnkie3HoXqcWrTlJrriyTOJvkYkq7zgNJvbqvN04pxfFTS4Io=,iv:uCDH/Z1toCquOVXNry6tS/95fa5VgNjyW3kdNGHatZI=,tag:zaXVZtqbyjBMLUJGVj+IYA==,type:str]
    RADARR__POSTGRES__PORT: ENC[AES256_GCM,data:004hTg==,iv:JM45TbQvPy9ymyeA/m5OXFY+YnuxbZY1jpimuTB7y28=,tag:Zn4FE+iEbNHX8aZBC/f13w==,type:str]
    RADARR__POSTGRES__USER: ENC[AES256_GCM,data:QMvlApJ3,iv:pCgJ5gQ4tSxyaJyhPFll7K/RwtIJFfUKao/PSdHNUdI=,tag:l97KOS52OIOuguwJEMrDtA==,type:str]
    RADARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:/77kk3PCoawt3jlnrnAcGk9e7EllDEURldpyWd79Wmc=,iv:60ZwuD+WMQfDuZFmsTvU3KQMIGWrEdMlzCYI1Fs6ugM=,tag:iDbh7myVXSdK5kxb9VQtDQ==,type:str]
    RADARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:vy9OHghvTbKz9m8=,iv:kouwKFntZBOnUARon2rywO9axF8DQqps8mK//YinB/Q=,tag:a3ZLkPQXqAFGnvvRQhrIJQ==,type:str]
    RADARR__POSTGRES__LOGDB: ENC[AES256_GCM,data:7oawZy6Ol0JlFg==,iv:qyY1+EdXf0oryFv1f2f9Mi2ivvJiMI+yPJLsIslVbvw=,tag:YUP7cmYSqQ9IRrnVWsaPTQ==,type:str]
    #ENC[AES256_GCM,data:8IjUoM2bbXGjzIDqDps=,iv:xqcwPhJxwxqvEnZ3A0Zyjx6BX5lVFFsvdyIWURMWLJI=,tag:10vEZbb1dSe1gwINphRzhA==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:de+5b8g7zYHlw13FFIct6weJosC0VQ==,iv:EFDwohBMZ7HouOwKAAuS1Iw8FmL5pB/r1DSJ51kPBKw=,tag:d3nhYsC1X6oWHPvmfOtwEw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:kDURoiV1nWaKKBTQM/fA74H9UpaeEjVTg1w7gVNjZT0JMZ2RTyvyTKM=,iv:Ynf4nUwLFTV8f/5gAEf5bsjrIIhIefeNb8xGiCFA9gE=,tag:06DGjxQk4OEhtm2lRfrWXw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:bu5+RWpR,iv:YU9VDYQ7UV33IttfBFTjUi2VON+cU9xnhC5Gvyn2B0g=,tag:BsjmFtMxe5Cu/zk9g0Jamg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:P/EJ4Crk+0Un5NXXx7wjOYQYMISMBPC0BaaCuuSWqW4=,iv:bpBRq4jiKObQ9xvDw5qj9XOePlHHjxEvr7XToiImGDM=,tag:z7V5nT6L9Vyg4zwgznm0fw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:UiXIX6v389wgcC3Xe6yVzA==,iv:kRmZpgUdDXAq1/Q3vKoH3mBq8l0kykx3tRrF4px137U=,tag:1Dp2KDRWQ23OYdZD14RMEA==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUWRYS1NYaXRRclBVY2lj
            VjRtNkpiRzBXWENaVDBKZlZGOVlCTWlPUUdBCldIU0VUQmg1Y1R5VXFrT1NCM2JC
            RkJ6VXNvR2xTOTJVeGxtWjZSeXViZmMKLS0tIDdkUEp6bmQ2c0hUeUNHQUtyMnI3
            OVlnbTlXV0tpanBiWENJaTB1NHFxejgKqht9eUnkzA3++H4i1bjhIr1WpePlLGEd
            lJtPnsmDK4iT7oIB6yBQvXPoY7dkd6OAI9KfG1yaV6q7037BJjwdaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T10:33:22Z"
    mac: ENC[AES256_GCM,data:OZlNAc40LYzve9uUIDOhLrpEw2bWIeFRrOtzd0HHL8cXjezUTSzIaXw+zLUL9Qu2PnGWvHyoP4sxREDPiZPPMs1XrC9FEMQgFlt9zHNzNNI5Kx5qHhC8n9Q8THOwR1Gylc8MqsB6qSjnpCF5WmMqRrrcN9H0DjWuImpeBV4ZK0c=,iv:wlBPOHID94UpzZA2n6WqPeJivUru6iDne2XjwjQMxrs=,tag:6ODtmDrTJck8ylJRN4gaaw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
