---
apiVersion: http.keda.sh/v1beta1
kind: InterceptorRoute
metadata:
  name: collabora
  namespace: default
spec:
  target:
    service: collabora
    port: 9980
  rules:
    - hosts:
        - "office.${PUBLIC_DOMAIN}"
  scalingMetric:
    concurrency:
      targetValue: 10
  coldStart:
    maxPendingRequests: 100
    overflow: Reject
  timeouts:
    readiness: 3m
    request: 5m
    responseHeader: 2m
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: collabora
  namespace: default
spec:
  scaleTargetRef:
    name: collabora
  pollingInterval: 5
  cooldownPeriod: 600
  minReplicaCount: 0
  maxReplicaCount: 1
  advanced:
    restoreToOriginalReplicaCount: true
  triggers:
    - type: external-push
      metadata:
        scalerAddress: keda-add-ons-http-external-scaler.keda.svc.cluster.local:9090
        interceptorRoute: collabora
