apiVersion: v1
kind: Secret
metadata:
    name: collabora-secret
    namespace: default
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:Q0goAH4=,iv:h0zkD0bK4q+3S3mD2bm+E2ezA8KgnLUT347r+6O/glA=,tag:YFQGNk4kr0JsEI3CrLZeXg==,type:str]
    password: ENC[AES256_GCM,data:obR1z9RlpiXUlQl1an9erXI86LlbKFjlFpVAoY1w4HkHOaWMKpP1+w==,iv:HZeuKu11bvex0eo/lkkq0XEGrZZtFT1W5NFGD0TMEqs=,tag:RtmBnozvThM+V/XJEoBluQ==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2V0ZJRmUyNHYyMEZUZ1NG
            SERGbTRucGJWSlUxTHVhSWtBZnBaSUE2Zno0CmpMaXhWM0QzZHVpZmd1TzBjSSt2
            alhMNGR4bmZTV2lsN2VzTEw0RnJhVUEKLS0tIC9EenoxeWczZG1NbVpzMFlzbkRh
            cUNFQU1WdTdXbkljNUdzUGVWM2tpM1UK6522yvOYuWIO3PeZ5+9ZiN0+0VzCjAgR
            Q6qkRk1EXfY41V4s+dW2Z2swN6Z/24rd3jFcY2pNMJY+6g1Dr4wtCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-03T16:35:55Z"
    mac: ENC[AES256_GCM,data:xS3Q7uCnaDebqEAizsdIi8zq7g1rIedTY5uazVYetQbymRHMfRtaEJYLglnJIXeMPhMn1DWauL/uMxzxWTtgiJzvPgr7SUD2B00RRqxp1XywHQ+8SSOnV3PB6DE7NxNOJz01iNS1bZHGL/1XLqYqh58mfq433DxtKxs41KR6B0o=,iv:4z89osZhxESp0jCnunt/SbM2RAi7sO9gx6FrzwtI4Uw=,tag:bz27fAJLJhOwMz/mm029qw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
