---
- hosts:
    - cn3.lan
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 5 seconds...
      ansible.builtin.pause:
        seconds: 5
  tasks:
    - name: Setup Encrypted mounted filesystem
      block:
        - name: Setup Luks on sda
          ansible.builtin.include_role:
            name: robertdebock.luks
            public: true
          vars:
            luks_default_state: opened
            luks_devices:
              - device: /dev/sda
                name: crypt-luks-data
                keyfile: /etc/crypt-luks-data.keyfile
        - name: Create EXT4 filesystem
          ansible.builtin.include_role:
            name: robertdebock.filesystem
            public: true
          vars:
            filesystem_list:
              - dev: /dev/mapper/crypt-luks-data
                fstype: ext4
        - name: Mount filesystem
          ansible.builtin.include_role:
            name: robertdebock.mount
            public: true
          vars:
            mount_requests:
              - path: /mnt/data
                src: /dev/mapper/crypt-luks-data
                fstype: ext4
    - name: Setup Pull based Rsync
      tags: cron
      block:
        - name: Ensure packages needed for sync_cron are present
          ansible.builtin.apt:
            state: present
            update_cache: true
            name: "{{ item }}"
            cache_valid_time: "{{ 3600 * 7 }}"
          with_items:
            - rsync

        - name: Setup Longhorn Backup Rsync Cron Job
          ansible.builtin.cron:
            name: "Sync Longhorn backup folder"
            job: >
              rsync -aAXHv --delete {{ longhorn_user }}@{{ longhorn_host }}:/volume1/backups/k8s/longhorn/
              /mnt/data/backups/longhorn/ &&
              curl -fsS -m 10 --retry 5 -o /dev/null https://hc-ping.com/{{ healthchecks_tokens.longhorn }}
            user: cubie
            minute: 20
            hour: 6
            weekday: 1,4

        - name: Setup Immich Backup Rsync Cron Job
          ansible.builtin.cron:
            name: "Sync Immich backup folder"
            job: >
              rsync -aAXHv --delete {{ longhorn_user }}@{{ longhorn_host }}:/volume1/backups/k8s/immich/
              /mnt/data/backups/immich/ &&
              curl -fsS -m 10 --retry 5 -o /dev/null https://hc-ping.com/{{ healthchecks_tokens.immich }}
            user: cubie
            minute: 20
            hour: 9
            weekday: 1,4

        - name: Setup Photoprism Backup Rsync Cron Job
          ansible.builtin.cron:
            name: "Sync Photoprism backup folder"
            job: >
              rsync -aAXHv --delete {{ longhorn_user }}@{{ longhorn_host }}:/volume1/backups/k8s/photoprism/
              /mnt/data/backups/photoprism/ &&
              curl -fsS -m 10 --retry 5 -o /dev/null https://hc-ping.com/{{ healthchecks_tokens.photoprism }}
            user: cubie
            minute: 20
            hour: 12
            weekday: 1,4
