apiVersion: v1
kind: Secret
metadata:
    name: bazarr-secret
    namespace: media
type: Opaque
stringData:
    BAZARR__POSTGRES__HOST: ENC[AES256_GCM,data:FHD7zTurUurdl+PmNw6bZNddGI8luveCHgU++yHoyetAV+OKnMu0Cq8=,iv:T53VLAIQ8SIN5N1pbOr8Oku7y5Nd+1ICR/Mh6du7rOk=,tag:8jCPGDqToAvK5DUVntK5Ig==,type:str]
    BAZARR__POSTGRES__PORT: ENC[AES256_GCM,data:kvz28Q==,iv:DQdmpBrzWvePvnUab6aUgzhh3guMhcGRT5jG1lCVJRs=,tag:n1b4gFPL1c57vAqDY2jhmg==,type:str]
    BAZARR__POSTGRES__USER: ENC[AES256_GCM,data:X7ouPyPE,iv:VMpm7bsLqfu2zE+WGAfOmOYi5HaMbNplrn4+yNtHCjs=,tag:GwUBJzFyocYuEk/nPzVSrA==,type:str]
    BAZARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:vaBVRLBHfjqwDY5d40yprAK/Bz1WdnWAmzsV0LPy0lI=,iv:uACt89/qGqgxRf68U8LTdvieJ//E4vEJOII+9JDg3ao=,tag:UpJ+FwNzRN0vifPJjLf8vA==,type:str]
    BAZARR__POSTGRES__DB: ENC[AES256_GCM,data:ncEKlttW,iv:JKSiW8gmMlYIlTk/AeE0wZqFBCbRYx+MB6JAMIvGOkk=,tag:AxImW6e/yVTWE8EGDfS/UA==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabjVFRENzSFBSUy9EVlN6
            QzRIRloxeEpBYm9WM1p0aHF4NkdGejJ0dzBnClNqWnYvRHlCYTM4QjVnWCszZy8x
            dGduSzc3TUtwK0FQSnJQaWVJbDhvOHMKLS0tIGlQbWpzVS8vbmpXeHNWYjRtcmtl
            ekpMNlZ6Q3E0VTlIUUhkcmdXOUNuRzQKL/yJfBMttZMMtjWQjju2d/tDPT+uw6RP
            fhZoc9aLk/G6QkcfWJTklHdJR/Ri8FgmAxY44G60KaQ3pzvmsG2haA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T12:02:45Z"
    mac: ENC[AES256_GCM,data:tOGOY/jfRvoBuxJflEBUaMkX6pYvdQpro7mzWktXE/uSuYqmWoXFeWF2GPtlcARYxJlIxGRlxqTWBYPkjbXD9JUjYhwVbJuD7SP9TmChtN+Y0voO+gHm0NmTjuMlMbKnVhV2KNZxFdWnfP9PU5UyZv19wZAUZXC2J0sbNG4K8Co=,iv:0TZHmSB0tYd5CC/wJnecymFQXbQnRXQRl4PXOjp9IYo=,tag:jikst7jO3x9XBp64/9gInQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
