apiVersion: v1
kind: Secret
metadata:
    name: bazarr-secret
    namespace: media
type: Opaque
stringData:
    POSTGRES_ENABLED: ENC[AES256_GCM,data:mwVkYw==,iv:zGSHTHe+p1cOEbZi1NRvKqjGN7byc+0E7BnZ9/Bultk=,tag:Nkwkk103p6tcikkqiej31g==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:Il8y/JIx5ARenKdr8nZuAnxdtVcQ3rV1vLb45BnaJzB0TuiJ3BEjSy0=,iv:IP9D+N3/1Ve5D6yfcL48BFNcND/2gpluJLt/tQEohCE=,tag:i748g/ejBWkKMJi1yQGxQw==,type:str]
    POSTGRES_PORT: ENC[AES256_GCM,data:1C81lA==,iv:lWuQjS2dAa6WTbVUE8OyIbsY6yzrVzfsHhTJ7uX85Fs=,tag:yegpSa7lbuEdcN107EwXiw==,type:str]
    POSTGRES_USERNAME: ENC[AES256_GCM,data:85VilK3z,iv:X3quNTiVIxiun4BZpSpvJhdya/CUQfjh6Me9cCwbccA=,tag:cJHSzvO8uI8c8RVbVbTQdg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:hCOcm5hN1zzVElBveYPLcJ7O8i0TBvW4mf8EdvTgwmA=,iv:4MRzOOUccI/93XmDbOdVrlX20LVUkR2nJn3LnPTRGi4=,tag:7Rc6poi4PJE4bsrrSSEPzA==,type:str]
    POSTGRES_DATABASE: ENC[AES256_GCM,data:lZmmzpsH,iv:FNFj/yR5MnHzq6aLBBxYwns0SUWvQcdDlffYD5C49V8=,tag:7c1Rm0WIMjsx5gN8ipQEJA==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1cHc1QlFwV09Dc2VLaHA0
            aStVNXRmcnpsRHFCYVNlVDYvMVRSUkpwUFJzCmpST2lzeTRhRVN5Q3hvdUxtUXNH
            bmdFbTBSNm9sRWdZTEhPNHFaV0piMG8KLS0tIHFHUG5wUTNSK0NRbzY0aFcwL1Az
            OEJ2ZHVtaWNyQW9CRis3eWFzbVh1RXMKE+FjVrOxx6EAAdJ49Y/epHzr+qSR2jcr
            yWlp+BB8eeVvmPmYPrJUHasDAf8iqDxOxvaTW29f0SQDsqEhVtuXIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T13:58:45Z"
    mac: ENC[AES256_GCM,data:Ai8dUk7Nen+gx/N+SVLHIzoLoR+BFClI48ALNxRjTAWR4u1r6SVnmbT104Mz/l/wxlwO9uHUIJ1RIj1+PoczE81mb0Z8rMlgHwSJ5SNevvZCzNX3pwc+dbAaNb5zAvZV9Fk6dlfSCmJZUczvWZs5olvggmQSDrC9JwqIwX8VDb0=,iv:VDacLu5NyfE2GFD3dwQsbQIhD+PeuG1dmvU/k4eal4U=,tag:xhJSnTq/LFJTYxl9H2aE6g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
