apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:r6b+IetsRwQjyYxkrgQtN42RD18MQ4j1nh9+S4w4BbYt8jbrxLd6TEixh6TAydHa+FeBvJ1Qy+xhEgQ7,iv:js+sdYpHQIdObNGZJitHs7zp7DRgXlHPON6PZB4hj8w=,tag:8SGYnjVjIM/VvV3BLITHqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWVdBWW9lZWlOU001eStW
            MTU1TW51Y0JXYkVCdXFWTVN5Mzg2K1MrZHpZCmVueWNJMmFRbU9Ja3F3LzV2d0Zj
            T2JvY0hhbXB6U0hUNlVwRm4zNDFuOXMKLS0tIDVUa1hjNTg0V3o5MXc3NWx2bnlG
            K1hSYzEwVnl4TUpHcEVNN1lOa1pnVEUKG+zyZPdFBtJzmSOgjUctRzeSsp4wGnDp
            CoVOpWaBiHuUI0m4EwFvzbwiuMfynoypwz34QTbJaECLy2Ywl3sFTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-20T13:22:33Z"
    mac: ENC[AES256_GCM,data:zs3WlSyIJyxUcl+iX1Q59xU3dWbivT+S1kXkdHEPtpXahwDV2hmy8DNdmfTzgV4ksV6E526udktA+S42tIWL36Yr2xcaRWlnrkvP1gNBkLmdminWzyZruOEPSfAzPT8YR68go/QGULtAFKCdehNRXla0eXNtxZuQ28Q5X2znCnI=,iv:au82M10q4vcurwqWvijYFJC/f3b2vNdQqfXKjHyDz+E=,tag:X6kTWr3ehX6OYOh7NgflWA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
