apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:2XqD2rZe7TV0WlvREH81ItwNupV4YprKwPb+1TpTv5NFvTc+oZSzOSYmQLB+bs11Kz8aH/8tWnI0XSEN,iv:Q+i5fvzEZGaf0OcNBkDBxkJUPvgqzaHD+KbrXXYoQ34=,tag:XxLM+5MHa7MzFSuGP0WB5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQ0xPaE0vWGE4L3plMHht
            RXA1d3Q5b1ZGV1JwendGZkNXNGxGb295WHlzCjFMZFByTm5HU3IzUDNkTE1HZ3Va
            MlU0TFltUStCZWk2Z0t2MVdCNm1reWsKLS0tIFdUUGMvTVRtTEl1U29HVkpiRng0
            NFlFUFk2SFZrckF4QVUyd1krVis0c2cKjuLDdT4rwCso5H16Thm9bKmiNrblxMAB
            U6fWACdgWfwO5RxDZ4YQDg2J0W49AcelP6qZ084hmzllKSapU4Eoeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-22T20:53:08Z"
    mac: ENC[AES256_GCM,data:TUw9EJGU+X4asa3s2xCg3AbnbFIx28aViMo9x2IM24Ns0l35aWLe16VmGIGbj52GshsAXsdHmw7hYgRHkzNwsOMHmbM//7uGSBvA0F2Vxj8L5fBhR+oT7NXvJ8k+O87MmpZQ9wgaWIzOPsvrFPpmHsGqvZlu3oS1KcGhS6PJqoU=,iv:/I0/oNfBOZ4yoPV1cIedu/2QxwigawTN7zSJBfcRTqc=,tag:zvKTyulXZXVW90KbjfUaVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
