apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:tYpTOx8bsbr9Z+j1xBimThH+2xqsqKAz9l2kaOkjuwwvmYYSj5sPYh9fr1qUtYMoeTXPvAT5kaZlwikV,iv:UPGDGjCOjUDkufXUW3U5yf+Eg+arpELVutgwyH8PfUI=,tag:UplKxpd2fQQaq7JL3R2faQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTEEvb0ZqYm5WM1NFU2R3
            L2ZoODV3MC9ka0NnTi90VGFSTXFnMTVkTFM0CnhueVJnTS9TM3VlVVRVRm1DSE1T
            Q3pIVCtrRVRnTlo4ZzFySjlaNHJBaEEKLS0tIFFKQzNCUk1GeEk0WUNQVlAycGtJ
            Y0dXL2g3ZkFYMEZrdCtrUTg4ZkxMLzgKCxG1IEj89Y/BXLaE2gzRFJ0Invy0G5U9
            lBcPJsmnzaGBzIQqgzuVTMQ68se85MPBykV2nRSCPUBhCqxImRZ0Gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-20T16:27:28Z"
    mac: ENC[AES256_GCM,data:q3t1gRGBt7lvEVMBeATNlVOal/yVl5FwtrJgp4KdKHzsqfmXPhZpGy/Pqq+cFlU1g8xCoy8B3UtgOw0j2C709m+tNwAw9ipwsM3oNDPJevJyBJCcInmGT0zc+DVyslwzRJUpMiC+Ddd0ekGNU8LUcWSkHiW9Ai1md7QO69ZPTUA=,iv:TH53LJSH0LQPu0OJiawMR8E+qyBt5DfX94nwEv/BQRI=,tag:hQ8If5fcrE4KeKx/DAfWkA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
