apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:kieS6KRN1NFl3WCxWwwKPV24APnjX6ROOLDJ6Gd9YbQeB0TLzkU50HjAUxfJRqqhq8pF1UyVz2q8lBrt,iv:DwHXqD8KM9NGwZFUHvCRNQqDuu+BNpZZy3zcPYjwjuE=,tag:lR0WkzyLJkKPjlge1fo/UQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VDM0NVRYTnd6eDlacGVs
            em9LTzBrU2dFbEZadkVLamFETmttOHlBL25FCmZaSXBFSW00b0FSOS9qbE8rcWt1
            NkxZNW4zaXlUK2hXTWFtUlhhdXlqMmsKLS0tIEY2RVM1L0xSL3Fzd1BTRDZ2cTI2
            S2FjdHdKbTVDTFZOejh4MnFGZDM3RUUKAUtYDiwxwNkXLc8j9byA9kKd2FBTtP0J
            60s6J7nVuaJxDO/51xw9NLiGm2+ZMaxdWx8wVu+MqoO+THiTD3Y9EQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-20T12:50:43Z"
    mac: ENC[AES256_GCM,data:9RU+59SXUUBTFAEN83KKHlqIN01Sh1bFx1xlWYxkS5OxSgrpjzRI3itqdLXfCPLRDkx4oxWrtHTo0sNF6xX+9p9BRklrEVz9NOQZPoIjnagOUeobLThbj1VawjGqVD/T8ajbE/UXvvRn+VWGhUqb3OUG83dglaSf3yNKT+qS5RY=,iv:UKr1lPSjUmUQeP3FvRTWFi9I8KkWi5mFO961EaB2mvM=,tag:mSDCIjHHv8fNRQmjyZEPOQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
