apiVersion: v1
kind: Secret
metadata:
    name: cnpg-forgejo-s3-secret
    namespace: databases
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:qQwQyYSHpFpEOIU=,iv:mYrtDJuetzQWAJ8NO41dOho9sw1xHeK51FHMAoMMgZc=,tag:QCwqQCZ1VP9CzD++fDhj5Q==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:MGED+/rSZ5gKLkDHV+Bv1rnqFY+YhFaEGmDvIiQXPxVNi7+VKTsN+A==,iv:aZUNtGc0GVjnU4gT1dGdLqMo6KcfUzukmZp8ILE/MCY=,tag:Dps9rLkFoQxg0X7hdaqxQg==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQL3ZiaHFxTDBrT2YrT3Jl
            RmMvNkwvMENvMzhMZ0YvTFFQam9xTEVRMUNFCm52Z0xPYkY4NHdYVHVwcDR3Y3dO
            SU13WWdxakN2WklTeStWV0hoVWp4ak0KLS0tIGpQN1k3MllTZGpwM0ovYUl3NXVU
            NncvcUozSVNuckJ6ZjcyQUlMcndFeXcKMgzcG7vO1KSe59zmDTtcmAvSvJZZn5Gy
            Uby6o8xBLcm3KRmF5gZ+JepcnghR9UyNbnR4e+SttmQ/Bs/f65V5rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-07T06:35:34Z"
    mac: ENC[AES256_GCM,data:cY07kPnuyDdUk2+PobkErplKks+V3qJ5UQdo5gax7Uc4h/MD5Ynr91J9ZOSf9gobMOmpSKq8OoDiOCIN0Iymo1nICpESKxJ9TAV0J6+4pehn4kyeHuZ8c8q2SrJGgvOZiUwuC+qJAkD+i1qQFluWvdVcGsQ48e8G/cgmDIR4jo8=,iv:V0/mnFvHNz28vdPoVRBHD/NkFLIDM1LvV21SaSfw+Rg=,tag:tYIY7hKVcU2eUaeNgq+lRQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
