apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
    namespace: monitoring
type: Opaque
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:MTwX3lomLk5GByrJpLJ3eb4qmO3KkTyjO6YUQXreajc=,iv:MPHVl7uqGH5ve1O4GV6BisUaA12TyBKnvIBYJqdA4uE=,tag:m5VN3kbJnQlMk/ok0/7/tg==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZU56K1BGUm90REtqcjhF
            Yk5TY1lBUHJNZGpicytHWFJKRFNSVjNqbEM0CmQzSFd4M2JOOTUzVGxGcXJqWENS
            WlIvR2RaSC9aQjEyOUtVT3lrYmREczQKLS0tIGlrZGhyZ0V6bTZvVGovZXAwRHlV
            anNMUWhPM1VxQUhFWkE5TTBSR2pDYWcKxNmCZfWCjSrs1c1A2/4vL2WaUOnO+YpN
            pwVF8IbLwS17iT51yjvKjUYpN/rUvHqlwSGyniCY+n2CuXeOIwZMUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T02:16:40Z"
    mac: ENC[AES256_GCM,data:F7m5ND+Os4lec01BOHRRWaAzrGt0HKUUrUFZqPKfQhoRlKGAiD25IcTa6HdyefRY53IG0HMusSJiGKSckAiut7EcFGtT0CQCYjAbvepPMpfKRt1+UGmskMWBqWcYdmhEzDYkwBwNfh45qzpCSUDd4rTKy93mFmQNwh6TRYAYGQY=,iv:JR3zF8t28vV0dnohV/G4ECuX+WthOm/yB0uc8pmKtJ0=,tag:2/UtPomEX864OnpIzuE1Lg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
