---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: invoiceninja
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: invoiceninja
      version: 0.10.1
      sourceRef:
        kind: HelmRepository
        name: invoiceninja
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      registry: docker.io
      repository: invoiceninja/invoiceninja
      tag: 5.6.22
    existingSecret: invoiceninja-secret
    updateStrategy:
      type: Recreate
    appURL: "https://invoices.${PUBLIC_DOMAIN}"
    userEmail: "thiagoalmeidasa@gmail.com"
    mailer: mailgun
    sessionDriver: file
    cacheDriver: file
    mariadb:
      enabled: false
    redis:
      enabled: false
    externalDatabase:
      host: mariadb.databases.svc.cluster.local
      user: invoiceninja
      database: invoiceninja
      existingSecret: invoiceninja-secret
    http:
      image:
        registry: docker.io
        repository: bitnami/nginx
        tag: 1.22.1-debian-11-r66
    persistence:
      public:
        enabled: true
        storageClass: longhorn
        size: 1Gi
      storage:
        enabled: true
        storageClass: longhorn
        size: 3Gi
    volumePermissions:
      enabled: true

    extraEnvVarsSecret: invoiceninja-secret
    ingress:
      hostname: &host "invoices.${PUBLIC_DOMAIN}"
      ingressClassName: nginx
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/icon: simple-icons:receipt-text
        hajimari.io/info: Client Invoicing
        hajimari.io/group: work
        nginx.ingress.kubernetes.io/proxy-body-size: 100M
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For"
        external-dns.alpha.kubernetes.io/target: "ingress.${PUBLIC_DOMAIN}"
      hosts:
        - host: *host
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
    podAnnotations:
      reloader.stakater.com/auto: "true"
