apiVersion: v1
kind: Secret
metadata:
    name: cnpg-immich-s3-secret
    namespace: databases
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:rwFeYvWhK7+QyBmvALeKstrPJfE=,iv:S7ejgHpVbcCfzGmLJEqG2nLLlJQrcFp2YttFIb4VWh4=,tag:fTQj9WH0AyRhXbWmF/ws5g==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:A0Yk1kUd6Eq1s/ONqtGBCJ4wxBhTdS2iciHvOj2b6GIFUk34Wl7+xg==,iv:ZfkfXO89aV7q7+/moRrEIQyVMNJ5udUodMpkm4KO0OM=,tag:CThhlG1Wk2ahViYRZYkivw==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RUxpTlB5bUZNbDZNZWh1
            YkRoSU5qWVpRZ3RPRU8yeC80ZkRaQWhpNFZvClJ1ZXkrTWxWMHl4L2c0V3pLOW9Y
            R1BBeVQyRUczaWs0dWNJVXcwM0FRNE0KLS0tIG5pZGt4RVUwdFVQUmFyT0w3czNp
            NlNWeFFiL1lFbWlzTmE3ME9ib04yUXcKh2yUOTONRDlagDrfVg6LjgrVYxgctFY2
            y8qSgAdwniQnPJ3QrkkisC86icnXbNW5x2ZEXKqYPdMWWQNfNOTwSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T09:49:59Z"
    mac: ENC[AES256_GCM,data:mx65XTvtfMHExYWad13X/Hkd5TQK5kA6WVeyh8XZ29UMZfmh4dTESHFIVrDK7TlXfdKCdWj+zwIgxLvQkH2O26rRtHtl/BCErO2H5eI9oC3lEMDxRSgsnPPkoLsaifdVrjv9CSLOX/i3B1ZOHYTWoJF4TLYlavs9I7KOJ1aIgkE=,iv:g32MSRggiw4X4LFwhQ4J7jWfF1yfKvki1dGpP9vWpF0=,tag:4J/FE8hBi6Riv1VUuAFVUw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
