apiVersion: v1
kind: Secret
metadata:
    name: cnpg-immich-s3-secret
    namespace: databases
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:pwMrVo/2NRLrt/I=,iv:LVkfiVqDaRYba8XCCr3sLYyRiGEO0eqrYTC3/Oj+12I=,tag:MOOT0+GTihpq4WaVmxp89w==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:S+rqvAqsT2udytyADSLQtcYIlqqbEmvk+r3uD8MaQvbJUGfJWz33RA==,iv:GtxbxMYOHNJMSH/LmLAPUISvcwa3I0VYhEppRcdYd4Q=,tag:DV1fSgId5M7k5x+zhw/egA==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNVZuQjA2bEc3M3p6cTRz
            bytrRnA4SU41elNldUE5L3huZk9ORFFySFg4ClUvbk1reWVVT1V3L1ROT3hxc2w2
            cTlVZnBzSFZYVGx5ZHlBRUNMUFJJK2cKLS0tIGR6MkR2WGRHdVBNQVRFbnQrVGtl
            eXRkcHJLUVpWZ01KN1U4VkNkaGlzb3cKH4LAa6Pm0dYnOFg+8jpP/tjHcI/HAb7a
            p0SYG6YftCufPEi6UNq95KkvfkIGZtebMdaCVrPWYYAoVag57Cqw/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T23:02:35Z"
    mac: ENC[AES256_GCM,data:sE47GlfNvyd6aQlbVVzlJjUxTRVBch1xF8yDNRDfrh013BuuPSJSY8wIemE6frW4uzTFFwUkKuPkid1jWRN4xeJwImZ8TRhqqBx0DOthxlr54y6dka2M4NLZgPBBqRLyi9N4qijXRVvaMzoMF9NuVjOsA/Gc46mvvkf6fXr4PYU=,iv:QfsokVDADEDOjyAAKQB5unjzf5NV7l6DmWZzR03NJAE=,tag:fnA67BKyQH+lP+yw7dKpuw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
