apiVersion: v1
kind: Secret
metadata:
    name: affine-secret
type: Opaque
stringData:
    #ENC[AES256_GCM,data:2m2QNHBFZGwgDjboMHA=,iv:Tb826SHuAKKxDRSwEZCgPAMKJ445yLPRbKeSDxjL7xI=,tag:zBkeEIllbZK+wQ9PhNSWlw==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:zQCtB/wm,iv:auC7grEcVCNSTLjZ4wTuDSRCnl+UTA1OZ5GxNmv9tww=,tag:2eiqT6uMANm2qgyv9WyELg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:IUrwmnADZhguruvFM+veJmu0BbDJfz2Em4bHQhR1yoWLAQBWDE/hPOXxIw==,iv:MmoAdAbRKZ8olq8dSfydT8MXdFt5F6Rld5sJvT4JW00=,tag:t/ABtz6XsAeCK+wm1zVQtg==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:lsqW4Hoj5rxhz8kKGQ3vIg==,iv:ijJGU1hSl6VlSrY3r5gHnxAc1TUDo0/VqkLSHJQuCyU=,tag:655QPlI9nV6x5VP6SFOvCg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:ouYEbRUF,iv:w8FIE2nQXEjQ+HsM99oh4nLyGyOvtgPako3R1w9KClQ=,tag:GnzFYHIy76fVSazpkCf21w==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:K5Q04dAGEJXO4A88iM8hAywElr4Db1lR,iv:1EvV/TWN78JWitWGIY160Dy3V+7//Rz+kYwYGV6A6fg=,tag:fv7IHXNjsyodMYXC90lBrw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:nKUTYXULeFFmN8jR3LzKzWxK/iJoKS4kPRZbEyqjcJQ4d9ZuFEaFjaW7Acbxop7HSYFybN7PdLOXhbUO5+AFMhdEGqD2OzR2EfODBqrSgbc1RGV59uC5R6/42PFKcSY=,iv:4PQbK+n6TISSE+umaF4pCwCXnjEozs+fC7FDcSDt0GE=,tag:ycpbLn1kO+T2kkwj1gBd+A==,type:str]
    REDIS_SERVER_HOST: ENC[AES256_GCM,data:x8TlJvrSSGcRhrRwBp/ECjlpSnknsaaJpVw1PmAL3VUufDjPpgTQLw==,iv:RY2zvigeBvIkLPesEY516IPmNoobSvknRUDnmx5sPgU=,tag:DOHTbig7fTDU12BknRzDZQ==,type:str]
    REDIS_SERVER_PORT: ENC[AES256_GCM,data:r4DBbQ==,iv:HPpg2i3ZUzttK85SU8Q9W49ZoHhxcJVvILpa8OZKJ3o=,tag:0ltdtt6XGq9IE3J72ukr1w==,type:str]
    REDIS_SERVER_DATABASE: ENC[AES256_GCM,data:RA==,iv:UEA76Kx3KjP3FunpZu7gR/djH9jON+G9DahtzlfF1us=,tag:+tjlYgJ9nA+m0HrPdzoR9Q==,type:str]
    config.json: ENC[AES256_GCM,data:/AgZBMfcLx/A1EX0UfGz+dGjxy6y5YpNOgSs8bytVlrRXDfcdibRBQbR0S3seeV2PTcds/AC6opWYb23Bt5iY6OUbkIvMLDn6to0UoAIV3jaGOhLZVrAT9jiuvMYDPQLzfrbxzB8uQu9pUy7eF6/tQ4jH1jglEztF48dc3furDSACUd5vQzP8ivvI6oPYAnaDFIT0lBf8If/k7oinzJKshEsVJcIrKTNwbHQWggAZBNN1ylh84Bb/7INeN0IJ3osvY0z6wh8f+WvoNtgCTX44A53ev+CHwUWpe3bb+rNjusH/YpqJIzKatmHlgMChZM7ZRTk6vwsT4J2g7XhNca+vfuB49Y68EfG8SbUrJ9x+3OBlSoBZfiDZFoeSv0LR1MjmAvaICsZISOCU99afD5avSBdRgvZDjrzwb4iT2rhfsy5EE3X/YHOTnwheePu90VPMMTd94KxRMoLn5GoFig43R9HVK/2X7LLzYL+Yp6V2FJ6OFoA6cif7ffLrihi2gafxt+DxWv916INNaYf7fbtiBHUykuyVBlz/5NvrygIkMIV8p51qRan1rYNMwvKfxnpgiTUvd45HJMu4+OPmaeeDquC1Lp9qdhj4W1Vj+0nY8dbxYS0wpkomsBtqRj3sg7Diss/b6sR65yvcD2fRhvpQIoYudDSYLEQBPCtwn6iEaJbBO/wFx3K,iv:3JSyZDPkArTm60ifePlwCRg5PhgeeVlUESk92T16F+E=,tag:9s/soM5tnLRR1MKfa0As/g==,type:str]
    AFFINE_PRIVATE_KEY: ENC[AES256_GCM,data:kftTJynnXeKsDcF2AP1I2OlSLSR4vTVMldrLmrSzBrVHFzBzWlNFThT1gb+kQWu1KtuBVjXdj84gX7nTHG5vdiIyYLAVflDgXy+Dg9naxoCMiWx64soB/UANeW+YKP4tqU12EHUtmEHYkgWka7wYndMdeTInZjAbNP+IS62yayBlxgy4KdghaN449LTVBTJ4mC1bVt4jNiPQNZ3rHmzo75oL3EZYd+0wlQnerP6Y97grVnagsLE92jes1vEY1iEzzAx91v38ctvFOLhGx2aJXlg0eFN79Yv1C4tZabS67238JtOSifANo8gjpDumL2l9,iv:dbz5Q/MnOB7+Dh5z8eenpE/BjPoRbpJwbJ7rb+T3w6o=,tag:hu2pmsmMKDFDBx/DAt/+YQ==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMjh0dFRpOGVRYmNpMEpY
            cDZUYkkrWjlnaGpKc3Nkbjk4WE56bHN5NGtFCmk1M2tBZS8wUmhqQVQ2WVErRG5t
            UFFOSGtHRTJyaWZTTVRyN21xSjJrYWcKLS0tIGFJV1o4VDgwQjFBSGdiaXM3ZXV3
            c2NIRks0Rmk0R1BPaE9aMGZwOVN3SkEKh8fosrxaQLIoSLL017646S1IR+75uq/s
            5Fk0lJmjk7glNW+4CMYyISh8tqtwEMXrQfJAAAsvIgKFm4iapYQ5Bw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-03T14:21:41Z"
    mac: ENC[AES256_GCM,data:AXojfO3q2OJAa/ksfNPqzbNdHnIfnSXuKKzxTtgvppTBFnS4B3b5nve/otkitb+Bgk/FJmD5ur4ppwQItA1VquZTvzvMlSqamH4oLauZoJN9+aHXcYu76NXPFTUg80BE/9jLhHObkMiK6LXpi7KOhV5aJn/u3vCJVWJHYdKZAsY=,iv:AzU+rJuDGj996795U4r0RWALGQkw0dRvTHeEmH6WBtk=,tag:52/GaWMkBqETNbTees4nrA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
