apiVersion: v1
kind: Secret
metadata:
    name: affine-secret
type: Opaque
stringData:
    #ENC[AES256_GCM,data:tUMpjRtr0qqkxpu3xUA=,iv:n2jT90rxftNosQjpfa/ViNpTa8oO7kYWpdkEmotMV28=,tag:2eQKc1uka/v6GDts6qRo2A==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:ejBuLnnV,iv:1MIH07wQPgYxIqjYLWbfMmC1qn3sq8lXfT78y862nZ4=,tag:l1jCkylwtkwEE5ZeACriSg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:E/iyynthGDviqj2I1T21+GdwFXLj07a9DIAyIotkUL0671qj0I0=,iv:/BLI92/uFGfZAi4q94ksNL2Bl0rV2BhkDnbu7jcPjvQ=,tag:7Os2nsCiFbJ1sPDtSpNGZQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:N1r/+qUva4dqFWoDGtfkmw==,iv:vwFHMHy79SpveUPMizUmDiAYr9ZQx3o3Ai5C+rhUP1Q=,tag:ueuDHRB2+epVmjExUWOJCg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:voCQANak,iv:jJfQfOJ1tRb444TcX7U/eowpq/g5pC/L/kourTenW/k=,tag:+7nYdl4Idap8KwiBwnQxdg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:n6CLbuh3JMXI7oXWlWSqAVcC4mM1WCJs,iv:v7gAYSrW/9o7HHnTDMSWdrS+VGFW5ltGI+SyYPfYZok=,tag:363dLCGyQ1GfDRAry6Y96A==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:DjqmXW7PNbd1R3w/bsAOWPLLqopVVSTJMv0QSylYnnegi5leC6e6MRtYHYg9MCphIX//TRtlZEwNUkfXjxRUtMnCtQMDghiJK0IkgQq+fbi3CQpOnexH/Pse,iv:sTTOCbXGn1Dw3bTo004PN1pNgvW72bfctWbmo5smcL0=,tag:tYtKElx8D7/jL9BIECi8gw==,type:str]
    REDIS_SERVER_HOST: ENC[AES256_GCM,data:axkJTsjwjXuKfP273Z9MQ40AzgzTLWwrZ+jUEwCEfth/ksHQSFM/TQ==,iv:ujmIta/LFJWivqjnLUAK/lqFYI/lam1Xa9k35gmX24U=,tag:J4tWlI/q/8DEA/yK8x9JvQ==,type:str]
    REDIS_SERVER_PORT: ENC[AES256_GCM,data:1biZzg==,iv:FQjSoToILKqEg2kHFSgBsW8xAhogetT59+NMepeDIC0=,tag:GL++hmg20V9xJmwPMvfD4w==,type:str]
    REDIS_SERVER_DATABASE: ENC[AES256_GCM,data:qg==,iv:okuIF6YDj2tNnaSi3gelHX8W9QMUazhG3B1hnHUsVrk=,tag:JeH0VWElqg/m2Xn0VEeTgg==,type:str]
    #ENC[AES256_GCM,data:jGTsebLFQHW9C1+jUQ==,iv:zwgVcAH/VFBOF4n1IxxlUZEfAWuRAxr/R0hBgWWBWX8=,tag:QFQFEYDYKcTyUK9bj5pPwQ==,type:comment]
    #ENC[AES256_GCM,data:WYwThcvDZtWc9oC7wQk3d9YlybxLV2Z0jD90mSl5znOBwEfY5bB8HmYr5HQxucWW,iv:4XlTmkhmDeluv5Hst2cvThj/FUKxnWUL7PwuvHXQgPU=,tag:igO+j0XJLqHrkIjmLui04Q==,type:comment]
    #ENC[AES256_GCM,data:/z9wiA/0JrfTbEp1s69gaQlFH/NXloSXsLy5bbiN6ONkdZMaGarcDa69orsnlDw7SDrvtYhkgJ3t4A==,iv:L01yPnbF2A6Bnu7mM+pO45B2vLJ116hrHfGdXXt5qqM=,tag:KE1sWooPjcylqV7GQXifOw==,type:comment]
    #ENC[AES256_GCM,data:ru9MQJu7yT7pVh4mGL/6fIz4nFOv,iv:edPWoTMfN+h63XTlDncrLf2PXuLKOAr84OuGZTPBkeQ=,tag:lqyYLHA3nvoPB8eqpRKWQw==,type:comment]
    #ENC[AES256_GCM,data:CzYE04fLSGVcHCzh15M1he422m/w/mY1x3IXl1VP2Oo2efSrsoaEO/N0kyi5ei/NPlXgHDA=,iv:7oMM4ZsXPZvpCGSgZMMFg+f/i5zap5eSUbHoHp5IyC0=,tag:5dcSXLge4I90948SQt7gRw==,type:comment]
    #ENC[AES256_GCM,data:sXmE3JcOcdEoBoOACK+WQgWf,iv:TuZ3vPyQuk7tEAqUbXDYsbarf5xZsgwzyD4/UDZ9G2o=,tag:fbH//uAZA4uEFzlf3vZHyw==,type:comment]
    #ENC[AES256_GCM,data:aiMu5yGeeQgk63GTXSkOfaciS/z7uUL2X4z+2KYrKmWgqfDeCg==,iv:xq44Rsc4dMnS+kj6oEJsNqNJ3cuDnuu1UEzIbsJ9YUo=,tag:VVuxTvTyZBZiRGTYg0SmiQ==,type:comment]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcVFvSElIcldTa1hvRjR0
            ZlpxTENmQWNIU1hHMnFrc2kxN3FBOU1uQ2lvCnNzUitrZzE2NktpR0syODBvekhq
            MkhMazVmZ2xDTFZnRUZzanBCeUdtQWsKLS0tIFZqN0c4OWJWWlBlQjhvb1R6UStN
            cWRDQ1lRL2RnZktEbm5zc3FaQUlxQzgKyKyMixO/OXBsp3weCX0iYlIx7KKAjvFJ
            PwHLR2p6ulEpF9fDrxqKM+LC4lzxXf1MGdUbqBy/TxSrmmFRAP6hRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-29T20:39:17Z"
    mac: ENC[AES256_GCM,data:Rww/3C4h3h/GQaU/84/kdS+MTAx8B1Dyi0B+yKikpx7u5ztXc+GgeQhkZNI5NhpeLhu9lyuauCfECFPFb1VDH3DGLrVzG/9mbFJ38Y3Iw0bOWVXEI6M2H4g+tr2XiFECrsLiqlieZHWoAf4qyMxFZS34XQea6WC9/pyieirkE0U=,iv:JSM4inp4QRVSherjdI3/CfTRvz4h9QWZPiTsvG1OfJU=,tag:jsJPc6IgaVj0+ZqLW09G6w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
