apiVersion: v1
kind: Secret
metadata:
    name: affine-secret
type: Opaque
stringData:
    #ENC[AES256_GCM,data:MfvFclY9YC0wO4jULyY=,iv:CnkUghWRuqM2/AHQSJjHmMK+dIbuFw+LMW1p/bEaykc=,tag:tQaFOzT6/wnevTeGEIHM6Q==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:6O/s7Jgx,iv:0qNRCIjCzbGkPnzrn7fOZfMKnunObeDdA7fDQKLdmcU=,tag:WsIVr6tOXLlpKu05SC+pfA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:47ySY8HdxNY1gKXVvo310w1euLGB/uLNsUMcnUu7esuepe4uaAGpYYRNZQ==,iv:iEkxIHQYxZbdBpxxpUSmvLV2UNiL2JJbXqx8+0G3h3w=,tag:xDmY1ZotAPq3R1yDH8O54A==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:TNZYhrxrKKAw/6okuDFJjQ==,iv:DYTOOy1t8JhB/9aXF32e5YuJh01devBYe6hSA6LC4cM=,tag:ekwKGe5oNfq0jEcsLfkFsg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:3BGX5gAs,iv:CZZzmP3xOmGKrLYiYauBr5j4T0C5Pzvb0/013C/exD8=,tag:kaWZLegEvcht8tKanRyclg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:RrSHRMSxIIznSqREPobT9kl2EWilwHee,iv:pnQFn8OxE8+N0vVHc4EJ0rEgczBXmr6HiLUBGZGVFL0=,tag:3Ub0wjtSXJf/EMG5qQJu+g==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:vCSy+eVABAf1FKXtCeF+sqlXQzvAUUI5LwnKRYxRvnz3UxREw7t8Xz3mPNdkRhtExTg8RjaGL9HufgRYp0+oZoMkUSAhjWpM5mYVjmpdIfUo/wo7wKEfiJR9PekqOD0=,iv:HNFoDRghHCPWIITE4NbDuTNmgHDddqMRdupYAsvGPuY=,tag:bweXoQPnEtLqVHZMDnWSxQ==,type:str]
    REDIS_SERVER_HOST: ENC[AES256_GCM,data:aJ6Lv8KPjc/tY5kjUpWTJfzGfBv2eQs9rEInGFC0tmSAkE2I1khKPA==,iv:Z2FWoFxzLnqcg+3/L1l1VPwov8PHwltyIL4PnE6T0H8=,tag:miLxFeZ70CJK6yoO4VP0cA==,type:str]
    REDIS_SERVER_PORT: ENC[AES256_GCM,data:qJN0QQ==,iv:pAzBPyBwEozDuJSuPQPs1eYK7PekswUGs5wm1FoRUqM=,tag:paScwIBEj01llxHVL9DFXw==,type:str]
    REDIS_SERVER_DATABASE: ENC[AES256_GCM,data:+Q==,iv:MqEZ7Y56A3sk4ZUnObT9DyiB1NUflGnWJ/O2Go+oYmI=,tag:ocbMXhamvtjXDXHpF7o5iQ==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVTlROW9mS0dBZkJ1UUFW
            Z204aGdrYkUzenVXV25MY0F3OENiSUdVUG5BCmVJNEFmUzFMNnJtOVRLWlNaMmxC
            aGlFbmlUaVQrQjArTlhOTGE5em9FcG8KLS0tIFErbzN3cTNYTFBobEtqYmZ0WXQ5
            d1NYM3d4eDdaTHVNbnlhTzl1eVlPZE0K9YrQ6+on4WjMM6Nmop7kNHktbC6ZH+yx
            pgPTjOyK9FTizhgUafUWWu55P0qwpd4zCCYop/AuRh4niuj9Xpe6JA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T09:10:20Z"
    mac: ENC[AES256_GCM,data:Ex6cn0hQh/NxUfs3e2rFrKLqmiWBvBkS4Q/VDrE2MaKYFdod3n8UlOVI+FayQkl5gC0EXagCBVqiBj4BBrF6Qj1Ekb15cwQkHaIKG0MwYeH4yLBzNHbqs/OeZPJvPoVDp1/CUZfI3cXQgi7sDqcAmEg+Le1y+7tLrnv7Rjg/x+I=,iv:FT1YnnZoNq4IFmarKd155cwGTgDStJVNMd+DRrsjLdM=,tag:U3PeOKryAGeRfkyGG+ZXLA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
