apiVersion: v1
kind: Secret
metadata:
    name: affine-secret
type: Opaque
stringData:
    #ENC[AES256_GCM,data:Z9W208HaiXTPIUIlroI=,iv:cL6cNFvBlFady2E59AShKQLPe7vm+fhNNkfmOsNkI70=,tag:jvPEQBuG7lf3VX6F77Z6tg==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:wxMhopWJ,iv:3ha+uvN6K11z9Lr+WSQyEMHVb3KmsdIqvZ+D4Fgoo1I=,tag:MKwrPLEI7q8BbzFZQ980rQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:Cnr9qg7KCoiO4HsIqhIKDUHIDd9HuvKzX7+CTq3smR+2AbnTkMq9W+fcBg==,iv:XAYoAVt6GsRnVG7G1tlbj6HfOdMA8VNJ2DaEOmHpgGE=,tag:OUsU6BCt4RJfvMx32lNFxA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:pGdOXlYkgyamcK3SUbaN3Q==,iv:1iBK0M4TKHCfGRRlVx2IruJQMk7bvafvdT/ToZSD8RI=,tag:gX4saIsRS/eRLec61DZBqA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:bHgVj0dE,iv:B84fBz0XSlBADzd9ygct/GeDU1SKSkJr7d7HnOR/E8Q=,tag:b8TVU+dWB0EwRWD6aLcf2g==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:R05O7XmLr5L5jP6P6qTOs13JOF/uHTkf,iv:KAURQOlFHvn1QkOKd+Q2SA5JhCyaXXdMlUxM/VeCz6c=,tag:ktDjmzjs5hQ+3w6tciEt+Q==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:kAjCginxctIxGxCS9XgEIsS73bAQDhA4EUkmbcMpIw7goJ6iYD28fRMYKNO0gfR1/quQbxBfjepG5UkaXbezY5Art/qmrIQOSOP+ezMJXdQCGA9NeiuEwIaFVr+iZIk=,iv:BcAvmC5dSlsyXbKKle3vJ2UXUzjXIz6SUKeLTCzNtN8=,tag:xA65uG3INDFHWG8gtO6zWQ==,type:str]
    REDIS_SERVER_HOST: ENC[AES256_GCM,data:j+KtBEfJjX3aRdvsbXxByNAYgPCKI/Sd3m8gqtdyYh2ZBVBBw3ZpEQ==,iv:F9vMK3YhSibbBooSp8jdLOClQLeHU6UesmXgIIHJEvo=,tag:+h/vI64C0gJyu4uYxkULIg==,type:str]
    REDIS_SERVER_PORT: ENC[AES256_GCM,data:eoIArQ==,iv:n8pfQUlWZBoxIaMxUglg6bO9Pt9GCcvbexuvtwd0Fs0=,tag:+jLRODKXsoHP8LesqC66aw==,type:str]
    REDIS_SERVER_DATABASE: ENC[AES256_GCM,data:cQ==,iv:NuiFe7tVlCCGK++bux1FtqTyX8406wkNsic7pUvT8G4=,tag:4xEVMTYkosTtI/t12uw4Rg==,type:str]
    config.json: ENC[AES256_GCM,data:ID10Jt9tx8YE3TdvtbbZUOZbEqtrQThaHrt23588kO7oNqerl4OdIWk8zFQTCsW/ylgMkFHZN1hnLnNcm46V7Cc5w4SkIw1rVr4iOnl90b3BTVe/LS0R5RbUNTNyi+n5BUzTnKOQnlM/9k8owUAeoHCdX6ZCCNvgwO/wq2CPN3eBOePqx/+tyy93l0jEj5XlkQnf4qvXUnmMG7YX71u4QKSRb/Pf1wHIkw6I812WLbhHB3pSPfU4rwNIvrmrIf74+1iWCeOP9q4WtYHI6+wI/xZe3aRJf6oBpa+08mS8zgtiURdSka2eZBbalrKi9xcT1i8F6hBxSBMRjWdzrYHmVLhg5/l8F7FoCfA2bji9ViimMRfo7C9b6Y7TfMkjycm2qV18f2Sq6KwTCQ4W6VyDR+61tXs/j458iZ664RgP6j5YgoOEBKCabfjKi7c/3ynYm16zGgJsfASWOXAKQXhOnihtstH/uN6+d5lnXUz6UX9xDolJZSB7xuBgyrN6YtwtO7QhUZDT0WbjEr5Wjy2eXhj810slvP9HMslvKmW/FSW7e4OTKV6gdvOZsWXPaC4nBPOGyK7MyHPE9VeKJBcbA6vb059MX58/fKfTnfYjRYs1YLeRHMrOQ/6z0J506U1i26qhwvASXVzTxVmbHnyFkIWq9YqVTzIQrfjaeFxkmYEqLQ34B1A=,iv:ficLreIKX5v31Q7nbLOwN0nRUIlRBXR8muw+Y5fdVYE=,tag:yRHdz8WQ3bq8UHSym12lmg==,type:str]
    AFFINE_PRIVATE_KEY: ENC[AES256_GCM,data:IAnDOiUYo60XclqDTHgXfu7fLRWltoJBpNCdgYHzz/pceHes7hUIv2JzqEgLjHNk7sl+FogM+aGQIdbi69+6vOZyN8U4OcQPuAhM1wcnHEw3ulV+fd5R+EjBlqq+0eqnQhNn6Rb968Ylp5Tc+cQna3nSemdE9xkcPMdeS9Dl10uYaorku57aXQJ60Jl2gntwFA6DRHXrJLYO/eXMfofF19mjPc/1mVn+eFj2wEJk3BSQxBRAS68UsTq8YWjtewn9ztdjP7U9rLqaUOt5v5SMN7E4nYL39RriittNNQTbdQPOcl1jaMOWy1ujza3eR+rG,iv:mtoht7kmLXEbljbpOnawHj8OtUOGU/TfGC39bD27n5U=,tag:tGmO4YD8838loCB31eOCXw==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaT1BmQnA1bkZySkFGNFRr
            YXVOVExFaUY1cFovOTlCaUdDNmo3MG5DUTNJClM4OW5iM1lzWUlSeCtHYlV1c1lX
            NjhKbEpNTEdWeFpoZ0hiYjlKSHN2M3MKLS0tIG54eVk4V25SVmljTkNnRkttT2FB
            eDNpWDJIVmRTU2g5cmNOTVNBQnlpckUKlkMHyQFPr+Ysjd4PyExOTGq2Ty3hMxkE
            m8X9y7UomYYvxZ++lT7GmzBFSeNlBHNfO0Bbut8jLo7oKKBx4LWopA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-03T14:02:58Z"
    mac: ENC[AES256_GCM,data:QKZFkFcCAt2EaUj4dGG1/2BJXBYNcEPg3o64wX3RTcqqVSRdAz+oxxL3yyKab6PGmnxAXqZi3pgBaIWHtaSzEv+Hxmp4ASsc3KESfWeIHn+sNt3cbtZIL9tEZJXcnAHQuMcEPwgqsAgufnbAOAOGd9UNUFFVeLkaltbsLUwN8aE=,iv:OozrsPDUXbFWbUoBCtgqbglnu0M2jwDzm2yiV2jkqTI=,tag:DDHE5XvT82M2V/81DSA2QQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
