apiVersion: v1
kind: Secret
metadata:
    name: metabase-secret
    namespace: default
type: Opaque
stringData:
    MB_DB_CONNECTION_URI: ENC[AES256_GCM,data:JEhY/5qeQFOpuZWSZf3fF9GwrW10tfFUovaxQP78XzNsDPIqULgxcp+eGKwJ1Yj3QepCvPunzORbIizT9G1haId0EhEFhmiAr51SSAcJssq79u7qalqvCfZ+dQahlKFfk332SPX8,iv:/iO3m8WCHkujNbhEWpbuB6p13uqDgIM9yhKZvqjtGQc=,tag:zFf0ofp6Hk2O77l8nMlM/A==,type:str]
    MB_ENCRYPTION_SECRET_KEY: ENC[AES256_GCM,data:qgl4yG3oa2cRkVqZBFwTn9LYBoUuBPmzMNagZZu85VbxNqfkHT47qdUfawY=,iv:JJUJRcgZ+r1YSuavSuFpTK3DZBll7xBO+jb8FF1XhxE=,tag:fqrsMbU97nAWNV4AP8rfEA==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMmUrUlVGM0tuTEttUDBq
            SUIrQ3VIOXptSlRJTFArNEcxRnBDdXZ1dUZRCmZCcCtpZ1pBWjM4NDFGbG51ODRm
            NkMvWHlCeVZLbVFHc3ZEaVBpcjlpelUKLS0tIHlzSVU1ZXhseVFBQmttT1Jab0lP
            Sjc3Z21QcVdNcytMeFhiWnVwNXAwVTAKi0QT5x9NPwsSgZEMZ4KckYKCQicYE8Ei
            AvNp6XWpehw5JTcEAEvsj3d8kd+NIddXOwtC6oGRDWsvED72D1fZ1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-29T07:14:25Z"
    mac: ENC[AES256_GCM,data:SNEW7vIkSWBeHFk+M9KfGlY/qDYCA5HFU5ZiPt9c+51yVVh7j3m1uUwltO6edB7Wcy+JnndqbMXfNYuZio1/EbpJnuZ+SKErk74QAj5R3mtBfXUJtOqek9oIoAZ+CTfeSYJK4na/VCMsjBPRxH6IymDesEG3Z3mjHw/x5OGYDZI=,iv:cjGxRmVnggvqnVQAsBHMIhgARqwAb5CF6tCkp2A6jWY=,tag:zYE7YgMBnYnKR9bCv4alNQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
