apiVersion: v1
kind: Secret
metadata:
    name: metabase-secret
    namespace: default
type: Opaque
stringData:
    MB_DB_CONNECTION_URI: ENC[AES256_GCM,data:MZBvy3YrNQ4WYiP0h6T9kn9c6HRemulpu/g1oGUbTbrRxRlI7ktN434RUwIYYtVCk1GmstENQ9/6PkzMxssE2D+PwZZ9w2/I2vdI3f9wKOxeVqIUJ7sSi7dfM6cNLMam7prNFZWi,iv:owpzj2f+DXhiWiHwFismT3gfSsyR+fyyYMq1dmsv4uY=,tag:GCck45Qf/rjkIOow0NnWiw==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NFEybnZFenY1TTVFdmRD
            WTcwYkE4Kyt0VjYwSEJFbHRDSE4zZXJiN3kwCnJvL2REUU9mTVVrc3NicHV6RkZC
            WW1LWVFpenIzOFVsNDdZa3AxNy95RWcKLS0tIE9idlZ0aTR5bUVwZ1VNS09JMGF3
            V25WT3lwa2tVTW83VENoSklFOHdyYUEKWIqwNRDJ6SqpdWPS2ZdDKwA1sE+Nd2Ez
            xcUlO7D+pCCn60KZN69sUN20V+0dbwAwdgPBau272zmLsepOTraAGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-29T06:31:37Z"
    mac: ENC[AES256_GCM,data:7jYqn9Nk2QTS2wK9wwiRwcc5GgIqDfJV6qpjA4Yvzpm9GpWPt7XhJd5wlxXKRO6DGsJ85ZAPDBejQmanogeZyIzhuK/iWPFTf4Xv1No9sWKWczrE6p9kvZOnupNfsS9MdZwDL7+yE12e+N0O2T4AvxG9ROKUEKLKH0bmtF/F9t8=,iv:uNkiMB69HMmUycnUJS0p+Qvm2jXCEVkoRmmJQ/9QUZg=,tag:h46tdsK9jMaTQj/kGB52wg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
