---
enviroplus_repo: https://github.com/thiagoalmeidasa/enviroplus-mqtt.git
enviroplus_ref: master
enviroplus_mqtt_host: mqtt.lan
enviroplus_mqtt_port: 1883
enviroplus_mqtt_prefix: homeassistant
enviroplus_interval: 5
enviroplus_warmup_delay: 15
enviroplus_service_user: root
enviroplus_use_pms5003: false
enviroplus_apt_packages:
  - pipx
  - git
  - i2c-tools
  - libgpiod2
  - libjpeg-dev
  - libfreetype6-dev
  - libopenjp2-7
  - libtiff6
enviroplus_boot_config_path: /boot/firmware/config.txt
