---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app syncthing
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      syncthing:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/syncthing/syncthing
              tag: 1.29.5
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 15m
                memory: 150M
              limits:
                cpu: 950m
                memory: 300M
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
    service:
      app:
        controller: *app
        primary: true
        ports:
          http:
            port: 8384
            primary: true
      listen:
        controller: *app
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          io.cilium/lb-ipam-ips: ${SYNCTHING_ADDR}
        ports:
          listen:
            port: 22000
            protocol: TCP
            targetPort: 22000
          discovery:
            enabled: true
            port: 21027
            protocol: UDP
            targetPort: 21027
    serviceMonitor:
      app:
        serviceName: *app
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            bearerTokenSecret:
              name: syncthing-secret
              key: API_BEARER_TOKEN
    ingress:
      app:
        className: nginx
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: ${LOCAL_SUBNETS}
          hajimari.io/icon: "cloud"
        hosts:
          - host: syncthing.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        storageClass: longhorn
        size: 1Gi
        accessMode: ReadWriteOnce
        retain: true
        globalMounts:
          - path: /var/syncthing/config
      data:
        enabled: true
        type: nfs
        server: ${NFS_SERVER}
        path: /volume1/Syncthing
        globalMounts:
          - path: /var/syncthing
