---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: syncthing
  namespace: default
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Syncthing
    gethomepage.dev/group: Storage
    gethomepage.dev/icon: syncthing.png
spec:
  parentRefs:
    - name: internal
      namespace: networking
      sectionName: https
  hostnames:
    - "syncthing.${SECRET_DOMAIN}"
  rules:
    - backendRefs:
        - name: syncthing
          port: 8384
