# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: syncthing-secret
type: Opaque
stringData:
    API_BEARER_TOKEN: ENC[AES256_GCM,data:pIEkmQBykJ3/IlNt2kbRq6sS1R21iFisz/u2uayE7Wc=,iv:4pZ/rY35frGWzDGmbmdvAYE31gM/qnxqtIuxVAKKrGU=,tag:ukUMxYH1ZsUnk40UTJ+2Hg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNXNMMWVaZlZzV04yREZU
            VTVVZ3E0VWdLVzJZU0lPaWFZR2s5ZVZCZXhnCkZLWDZUNHpkdmtLTVlienFVdy9G
            cEN0YUg2czdSL2Y0T1VVencrTzlNUnMKLS0tIDJSbHVqMDFnNkxHc2hwVDBYZWFx
            YnhTR0o3bTlqUE5JRmxqaUpieXJjbU0KNTjPBg9WijZIs6eSEhdRs06LuQeuuAx2
            jU7F38RicIQFNAioMCtQqXJ7+FeMExUBkJH4+yL1D8CSQM/WEjkryg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-10T16:02:08Z"
    mac: ENC[AES256_GCM,data:RVTeSk7pWA1IcISgNpx2s2nQFmuvfiQeqjbQo4hxXDZmoLt4BcPS30aBrIOwyC3mZOFC8BS7b0VM1H5hmGdmeDmTHJeWGPayNNB8X9yG0vNgnoQbyUWUE581+bkxIssNOv2CJZTDqcr+HvxG7eGdEd3T79W5vRsUNJODQamti6g=,iv:o6/mqcSCdL0kcrPFL9OUFxNR5Pwq7XxBDExH5wX6VtE=,tag:t7TpiKCPWSO7gKjBzkdCgg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
