{
 "title": "Sonarr",
 "description": "This is a dashboard for Sonarr v3 (exportarr does not work with Sonarr v2). You will need to install exportarr (https://github.com/onedr0p/exportarr) in order to use this dashboard.",
 "tags": [ "media" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Show Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Downloads",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sonarr_queue_total OR on() vector(0)",
     "legendFormat": "Queued"
    },
    { "expr": "sonarr_history_total", "legendFormat": "Completed" }
   ]
  },
  {
   "title": "Series",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sonarr_series_monitored_total", "legendFormat": "Monitored" },
    { "expr": "sonarr_series_total", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Seasons",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sonarr_season_monitored_total", "legendFormat": "Monitored" },
    { "expr": "sonarr_season_total", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Episodes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sonarr_episode_downloaded_total",
     "legendFormat": "Downloaded"
    },
    { "expr": "sonarr_episode_total", "legendFormat": "Total" },
    { "expr": "sonarr_episode_missing_total", "legendFormat": "Missing" }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Storage Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sonarr_series_filesize_bytes" }
   ]
  },
  {
   "title": "Episode quality",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 8, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(sonarr_episode_quality_total) by (quality))",
     "legendFormat": "{{ quality }}"
    }
   ]
  },
  {
   "title": "Storage Available",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sonarr_rootfolder_freespace_bytes",
     "legendFormat": "{{ path }}"
    }
   ]
  }
 ]
}