---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: monitoring
resources:
  - ./helmrelease.yaml
  - ./secret.sops.yaml

configMapGenerator:
  - name: grafana-dashboards-loki
    namespace: monitoring
    files:
      - ./grafana-dashboards/loki.json
    options:
      labels:
        grafana_dashboard: "1"
