apiVersion: v1
kind: Secret
metadata:
    name: loki-secret
    namespace: monitoring
type: Opaque
stringData:
    BUCKET_NAME: ENC[AES256_GCM,data:fSDQbQ==,iv:eqwHLUOQjnbIxsMViz5E5ZBd14YFK+1QTEYpegP5K/s=,tag:7mDv7Gsa9CdY+K9sTFK4eg==,type:str]
    BUCKET_HOST: ENC[AES256_GCM,data:hTxM+MusBduJnP3RHu8rhJuuyaRugN4LZb28v61FPVa4Trzj40O24ITNcOD+BD4=,iv:duRmZK5+Bf0/MTAMpyjZssNoblEJ3SdCBmswG3I+HrA=,tag:uTrrPudunFqIndfVOfF65Q==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:PNgu0A==,iv:Q1I4knCWXfChyQnJ8QWs5GKZHzngLJXbJzywqwVx8iE=,tag:SXoP6yb+QnqbW4GPOljQsA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:9Ue5K3YAQpYz+VUgBbLQFw0MDBKSKLvMkYzzKDnLa2p8NlIJi1yLiA==,iv:LygWPEoO7An9DFjMT7pALKCnu//oqvG1mePajP5BZ7w=,tag:POL2FrwXGDvOXYwDmaQwBA==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxakVlQTdRajlvZzFRSk1F
            Y3ZkVnFVSXlhSUR0UWdEZllreDZoSFdPRmtrCjFBRmJXT2lBN2d1RDFORXN0MkRo
            bWtOQlRtUS9LdEI2NXdxRUpMYmh2M2MKLS0tIHV1WUlOTmRjbWJvcmI4NXl0cDEz
            KzBVWU5YTXBtZG90MHU1dlk3a1V0dUEKPHcp79copK5C9dseYyri4bM69vkM58JO
            LOr0HMoN22bj3sMMIG3462OcPVdZR8dCgWVMHLfM0sAPAtQoOH6WCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T23:27:22Z"
    mac: ENC[AES256_GCM,data:yzsLzejkwu4Sr5Z3pPKciEjE4xsJRctFre6xzEY5ZUPtbkW97Dxo3Du/YTtWJDiu4mgDhuNUjs8iqMQNDuoGNPD5EVNyOBS+Cef5kai0odZT7I+c54Pmt97s3ItcfH3OqF2F2lJuBXgzyMEQJe3e55RQ+R4JJm+sOsQVNJjzaSg=,iv:uanRo7hzWJECAXPY0gLFfcp6WR67VK7kj3Y5YhIU6xQ=,tag:644mLXsrAiA568Iw+jvFeg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
