---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cluster.yaml
  - ./database-dispatcharr.yaml
  - ./objectstore.yaml
  - ./podmonitor.yaml
  - ./role-dispatcharr.sops.yaml
  - ./scheduledbackup.yaml
  - ./secret.sops.yaml
