apiVersion: v1
kind: Secret
metadata:
    name: cnpg-media-dispatcharr
    namespace: databases
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:fdxLfj9t23qpAgQ=,iv:d5GAifZ/u4lPDzSCeAIpAs62DeRyG0qLqbfM9iGjK9k=,tag:OfHNhyrnyMlAyfnbIG9WyA==,type:str]
    password: ENC[AES256_GCM,data:UDysDvlVrfMy1a/mhtb+K89lRRmPSlohgkLGZX19+2Q=,iv:KoDgfF+sBFflR55/g1057qFq2Eb/XDOf5R8sOd13z90=,tag:aYyvXYbf13xqTqRnMtK28w==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzeXAwYW5LTVp6NWNIcCt2
            TWRzUzBkTmdncGNSWEc3NjI1ZVV3bmt2aFJVCjdhRGJBKzVUMVA2MTVZczl1b1k0
            eEFzT0s5Sm00dWxEbDJFY3FJc0NpSjQKLS0tIHNHaWE2SjI1bjB1Y3IvNmF3a2F6
            Rm1TT3Yvck5JZkh1RktLWE1rQTYzdG8KxkHywgp4OHG9uGgQufL8t92BtnHcf4dE
            6ryvpnaaFAIsVWZqlLqPV4g5i8HNnPWrM6LY6s5tTWmqKfda/0yLUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-17T07:46:15Z"
    mac: ENC[AES256_GCM,data:lsiiEg4O2F3zt5RKEQg01Ngr3I1o0IjTi7hFUjixnoOS65eLfXBL8QmEuWzZY9QfyV/GerBGOsmKJvkJokQJyDhb66Guj4Ytbk20RxrGIdPDKkBHiVg3hFnnNwElYIrKob5ZzvWfMgmIqgReI5NVziy+b4VfOqhBqh7KYlUUBoc=,iv:CyVSObmRZ6T6WscX80WQ8rRFQWwDTrVOGRwH8NdawR0=,tag:WNcjMGRLja0RP3hisFUyTg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
