apiVersion: v1
kind: Secret
metadata:
    name: cnpg-media-s3-secret
    namespace: databases
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:yqTfkKJJoGXyO78=,iv:rb1kEX8O1C0MNyG3netUL4h0dLaBC+WfUV4REIy+O+s=,tag:jHybP3LuKIr5LDFGhuCYXw==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:bDk1XZXQnpWQxHquBTSOvOEIWqgpbhwQ0p5llkb5X4P+c1aAI8ybbw==,iv:khizZOePLSWinI1LDxi7OBG5z3RjohavdrJG1D0kURY=,tag:ECt7O0pYnnQrZsuksf8/bQ==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSDJrMTFSRmxwZWJIMlBF
            cTNHa0xJS0JBMFcydzJrR3ZzN215WnVQK2hjCldBdk9QUXZXS01mRVRaVHh4R3Vp
            RlF0WVI4cUZpaW9ndExVVFFreGpWL3cKLS0tIGREcytLaVdpS3JWeHdqSCtSNjZL
            a0FUZlRiU2FQZWpieURqYngwKzE5KzAKnyaiDVMJ0nEfTmeMeOugZDO0qWZvfA80
            5+m0S1MGUeBrcO1LtK8LoHuQX9s1NLq1PQaFLEQ9+sLtUQ7DokhILQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T23:02:35Z"
    mac: ENC[AES256_GCM,data:e+2D6Rl3Lnc/80vRg4pd3/1CxHlmR9cP9yZ0WXZe07OlJGjcObow2mWTifuUIW+CHHE74bwPMx08Qczb1kaQN97kEBYNU3GgOuN4K07s4znx/jwCUAGw+S98cNmlTbaIVqKPOP7hhWLzppkLQWjr6lWtSD8NegPk9cxEKEHvrxY=,iv:t7JCvZlnqChQpunwOoxWuLdG7Gr4BEUYzoyRzXeA9z4=,tag:QTEr6pjKJJUQzEkvcv072Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
