apiVersion: v1
kind: Secret
metadata:
    name: cnpg-media-s3-secret
    namespace: databases
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:SxJ2L1z+Ycl5Oj4DARe0MeVglXU=,iv:eiswsh1uOTPMe2yFR/2O+fr5FhHZ61BSgo6M8N9etgo=,tag:DE5rNyiaFCfHw9l2Zeo08g==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:DIpS41CNz7hSR84GwP1I9sbyVUrK1XN8c4ZT8qf1FN/tUPJKaugMHQ==,iv:dK5aqsIeSw1e64XlPmA57Ex8w917fLI2VCj82GqcbG4=,tag:tZKj1P//f6mkRCnh9rkVNQ==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwK3dvZHROQTRlMWlKNUt2
            bDJpSXRwT3V0c1VxTUFsek82Ui9jaW1VVlc0CnBXdHBNWFJmcndpUXVsY1lielNG
            dzFwR3gyeE1wbG14Yms3NHFhOFp3a0UKLS0tIFRPQUU0Q1owSnhRK0RicUtBTmwz
            ek9hTCs4Wm1TcEhWTTljSmZnUVJQc0EKau0EckvLNa7KOeZBab/87Axo16OC2+ZH
            +zaM02NgXBq+B7rsIF2FtjShcKmq8Ug24k6jRM/FXJ4Ijdp/1Ro20A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T09:50:03Z"
    mac: ENC[AES256_GCM,data:tQTL9sLCiYH2GRi+iBbyI7/wVozdhqiRdtL5vd6SmeB2pCLEcWTO3QwedhJbF/3/vkmjyrC3yc1P4+i40oB7tVGP3cgf5PfepzNLwZXPioqCyd8majZPf0WUIi5RiujzxN4/lbnJ/80j06MB17R+LDHz7Ync7E0nhb5/nIzqlfM=,iv:66dcrFddYXQLXYGP+mClofUfb1T6cwZocpP4fKBocZk=,tag:BP4ejkmKR7b1wTWS+/a9dQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
