---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: databases
spec:
  interval: 10m
  chart:
    spec:
      chart: postgresql
      version: 12.7.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      postgresql:
        auth:
          existingSecret: postgresql-secret
          database: main
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: "15.3.0"
    primary:
      persistence:
        enabled: true
        storageClass: longhorn
        labels:
          recurring-job-group.longhorn.io/backup: enabled
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
