---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres16
  namespace: databases
spec:
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
