apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:q5tG78YCD6msyPXEeiIkiMraCnKnGIwNFAeGeemwODuONy00,iv:buE/DuS2n9WyU72oghQnvwweMISB7225KjI2zZ1KNRE=,tag:XGileSWrqRi9855+k3Yv5Q==,type:str]
    credentials.json: ENC[AES256_GCM,data:o66C7aFyqvqi1V6FalYRcUtob6ZyIsThCt6iE0BRWVrd5paoCWph/heGFTQPRoauIGLrb7TXd65gt4bEvgllPGTTHGUiuMC3suXI1hulI2piUsZzDMqGCLUo+SWw7KS4gIbHjVqxc/tVa0ZjXKZKjSIo0aTud0Ex2AcT3rGYHrIL32xb1/ereW1+TakqTxlFh/bQ5pExoplYb2DJ7eIOHX40PWxNsfdEeUl6g2v7og==,iv:wVq08Xy0zhAOtisF4g7sguoiLCd0RDHUP8uZ/H+FFmc=,tag:IYDX7pfG7hgTC79VZD2dGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldWU1NG5DSmdURUxhUlIz
            TXJFM25uM0g1RGxScXNiMitIZ0h4dHNzM0RJClJCNitlK2o3RW1HVWFrWTZpdWlF
            VzhhcDByVUZ1RnVQM1FIa0tiOUU2Q1EKLS0tIEdwMVhPSUlsUkRFcUZSYlJIQXRZ
            V2dTYmJ6bE1QcDhSS3UwSmt4dlZJZDAKWsnlGwuSET+PgghGwqogSzsyCt6q2drq
            sttyp7n3szruNg619Wfhi5FMBiPsvjVzAsSrrcXOzjRYBWmYksotTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-20T16:27:27Z"
    mac: ENC[AES256_GCM,data:uqoX6orAkugN090nGM8+60J8GzhfLOzOvsciJKHHmrsevZTGbGHBbNlDdsN2Z527F7ZNp0RIFIJudTG7e9koN8RGHxyRDwuBOS5mre6N8tYzRVrJ/ueP+YcBfhiH3DlGlGrordNh2GP/OdN5FxWdGOvc/hv3Ikdklr4503Q6fBg=,iv:G/K1pFcXA7NT1uzr5Klm9fvTyDmPw09imC7LBMTjPH4=,tag:DxXGe7XFLet9N5KZtdiCeg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
