kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: umami-secret
    namespace: default
stringData:
    POSTGRES_URL: ENC[AES256_GCM,data:4L9iCKYP1DUO7uBPizjA329n0cG2ObPasPmM0MwhEMTVGfu1cqRCK9OOUMjp0WkAQ8ZAtThpGUpn/mBCVnr6YAmSEWewwfObMg7jdWPQxf2hgsPWUEUEOsheG2KgF9OjwiQxkslKRK6R7g==,iv:8Hnv7xRimzEtbujZgrnleV25YDjfJSzdL8LihTPSb0U=,tag:B0YVUEEOLyySE2ECBHaCLg==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:BZmWRKL5pPEKUfXpTjp0SJx8z9ju1CfPCv9Po61flNcO+FWlQVD7aVWkHYNRSHsBzcTSg6I=,iv:03RJAl5xW5R9PzBHlncsnt0q41yoqWFpjzOe+scczK4=,tag:T3t7qA1k9v4D1HFf28hmoQ==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsQXVFTlJoaEladW5yZ1p3
            dGdxdGJmSlAySW9UalUrU25zUFRxenBjL2w0CjJMQkl3cExGc0xRelBuTDViaGVQ
            a3F0bDNjaTdxUUJGNHJnRGcybGxPWEkKLS0tIG1Pa0dreEpja2owdVZlMGM5MTFz
            N09uWnUrOG1LTjArZkorUXl0dm1jY1UK8FHiQzW9dOU0UPqq7RFEP98P/ZVzMPYB
            DUXUHzLOXGnxQx9UMTPwA6Soi35uJPcr4xH4fwxwbk2SdtiiWYkxJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T17:36:40Z"
    mac: ENC[AES256_GCM,data:a/QZWe7M6ZLCoyoyq+oMmcfH7686jZtFTJyRxBwwg33UdQSH12UGIQWzl9BjVKEPc8hjzxrvqy+Ao4jkDxkJltKTBqu7jkCC4dwWuH466ymn48dTewNQRmqoOre8RHVz+h80g58nW5et5GSHOKcXE9u3AZTjoAOzFE9JPctL0M4=,iv:aFn0AV3cPg1CHkUXPVSOlKEZLkHWtEsVFB7Cdf/SDv4=,tag:65xQTYbcz77tc9zgeVEWRg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
