---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: kube-system
  labels:
    kustomize.toolkit.fluxcd.io/substitute: "disabled"
spec:
  interval: 5m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.18
      sourceRef:
        kind: HelmRepository
        name: nfs-provisioner
        namespace: flux-system
      interval: 5m
  values:
    replicaCount: 2
    image:
      repository: registry.k8s.io/sig-storage/nfs-subdir-external-provisioner
      tag: v4.0.2
    nfs:
      server: nfs.lan
      path: /volume1/k8s/
      mountOptions:
        - nfsvers=4.2
        - tcp
        - intr
        - hard
        - noatime
        - nodiratime
    resources:
      limits:
        cpu: 15m
        memory: 80Mi
      requests:
        cpu: 10m
        memory: 30Mi
    storageClass:
      defaultClass: false
      name: nfs-provision
      pathPattern: "${.PVC.namespace}-${.PVC.name}"
