---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: kube-system
  labels:
    kustomize.toolkit.fluxcd.io/substitute: "disabled"
spec:
  interval: 5m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.18
      sourceRef:
        kind: HelmRepository
        name: nfs-provisioner
        namespace: flux-system
      interval: 5m
  values:
    replicaCount: 2
    nfs:
      server: nfs.lan
      path: /mnt/media/k8s
    storageClass:
      defaultClass: false
      name: nfs-provision
      pathPattern: "${.PVC.namespace}-${.PVC.name}"
