---
apiVersion: gateway.networking.k8s.io/v1
kind: ReferenceGrant
metadata:
  name: oauth2-proxy
  namespace: auth
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: default
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: media
  to:
    - group: ""
      kind: Service
      name: oauth2-proxy
