apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy
    namespace: auth
stringData:
    OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:FIOnenRs,iv:qJ99LCv/0xQW1hUtfM2upJwztVN68ejvlY081WzC3xo=,tag:81wjTF7yyNVbaXPxfJlG+A==,type:str]
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:4GVY/XRvGVWM92zZ7vrTrw7ZFvP63MTrcNFzAde2hTc=,iv:rx0v3YySeOb8AqLbit71TAGJgvckCDECLHYQGCTJNhI=,tag:CWEpqfIMTxd3zxdefOvefA==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:nIuDwp1B9uRRRf2WoTWT+wUTgifHvRFbQPPWUpJWWpB64cRmx7Kjg/SzPkw=,iv:6+HToKxz+A5IfhQjkjiK+O07SIQcAS3087f1epDkToI=,tag:oF6KEnTiKMn4OwdN3bMyrA==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrSzR4QXhhcFBsaHp2TTY1
            WkdyWDJCMFk2S3ZXaDR6Wi9Mcnl5clFrQVJFCnpVeElGWUx5dVBmd1lxekJPTG5s
            VkNCcG1hVG9hOVpWbTM4NjNPTC9TbWcKLS0tIGUvaFVpcVlxU01Wb0hWdE9UUi9a
            NGdsTGszTmo2NTZTa3QyVWJHS3pDY1EKl1nE5PF7SLW2m3ZNkDO/ox+BFDCKcdbW
            HXZHwPGCfWPB5CQ4KN2aT7w4vD/2eGKVv0DIAbnG3zMhDWmWVV9Hjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-02T05:56:58Z"
    mac: ENC[AES256_GCM,data:lkRajGdCqbCulikB1/NnGNV7x08NZ36jn3anXLLqFcO9zy0vzkQIEe67WGkU09lh0Ax00OaALAh2JupoiHGMPtBNXyXUQnmkws5nGZjn06UmI3ON3EfFqrrENIHsrDjZN/bezxjAS2zh3Thom+4NZ+erISXBEUscRESf9S8/z5I=,iv:ezjXyswdewsEgqRg7urO7xPU+jhQ7wP85Xcjf/TfS5E=,tag:CzaL9cm913bJi+ASwTnGrg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
