apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
type: Opaque
stringData:
    DB_HOSTNAME: ENC[AES256_GCM,data:94L7fZ8wyXlfUZFEAieBnYexksHfYfJxLJ6Bka2/BOo41p5imXuVdQ==,iv:yZ+EjVqzMVFRguXNqdxUPJ4v0TmN3UoWYTUpz3JBqMk=,tag:VzEDxbmFxpRUvN5pVX9yQg==,type:str]
    DB_PORT: ENC[AES256_GCM,data:lbbTaw==,iv:J9dpNBOGLpGl/UsPKqrqEOOBP6PTGaaQh7CkKnSlkAA=,tag:aA4hd4zliRPYu6ImMXHkXQ==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:jpFOtxMU,iv:Ch3TRRQa6yFuYgLnb/LDIFU0TPMwujIWY9ztAaD8vlE=,tag:WqnY5ucC1yEGVPEU39SCYw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:3y0SDpyqJC8OTmAFyWhEySMDF/2R2nEWvJBrk+qSe2M=,iv:fQv0MWdxvKLyAmdsqtlbuQy5zRz1ORj2TNDBofLFNpY=,tag:F/9VIbKF+YYEV7TBVVfj/g==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:9bnyoVD6,iv:bK113QIwZ1t9T0Y1eWEYNiwEMOs9ULTLzZoCywbhmY0=,tag:AOGH90Lh8l4DFu7NZnFQ8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UEZFUjZzMkNvUk9MekpG
            M3FDbmZFWmRXWkJqNnRpRWJEbzUxUkNwWkFJCm56OU9DZ2pVQmpENkNibW9WQWxN
            eVhXU1JhaGtvbk1nUUkvWVZjUVlwQ0kKLS0tIDdRblNWb0dOT09zY1pYZkNPL0Ez
            UU1NUDRWSlhIWGR5V0hHOTJxcGpYYWcKXVF6LslDm/0ncklVtHntq+RQDJrzI5Wc
            0KrwuVMn7Enfqs8ldJEaZI1NYCEgdUkr16GHEOxcBtRg0xjvi1FLCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-22T12:38:17Z"
    mac: ENC[AES256_GCM,data:xrQFqrWIUbGmsHS/E4ZeNluJCJ3O6cimugUtmxw6w+hxio29wdXqYuhNn/jwYL99NPqop/+zEJtGU+sjeyNisw7XcOi/dOeNvSxp7SpFph3RzwUIT8ovvdcXoBCtoJFAZXOiBaWg/3r4YC0alD2fad9YVD9i7hXHXhar2hXxUhk=,iv:otOPV9wuOB73gSJEkubAPpQhM4GyBgDFCgz5EecPUGo=,tag:+J24wmvHIhPA+tXg9xlkcg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
