apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
type: Opaque
stringData:
    DB_HOSTNAME: ENC[AES256_GCM,data:4PRY2+xCBkqAuSSkjE/11mdxZrsXCr1C/RP46XrVu8Gf6p676AWvCu8q,iv:LrObNDQG4+JkBb2i1jOIdkxkdIs/r2sgjCSSdRN1pPw=,tag:eurpx9LE3yf/ZLNThzmhtQ==,type:str]
    DB_PORT: ENC[AES256_GCM,data:KjD0mA==,iv:1xkMf44WAYBofUZi46+UkIUQuw7IvVLE1gTbvcnZfWE=,tag:XWdZtz3FcfjjcXGqkvhzPQ==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:3XNVAYyg,iv:efEfZ3cdbvy/xVsL7jJtx5NEqKpsM/Bp0xpT68YfM9s=,tag:KACmP6n5i8y6zhx/Z+U1lg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:K4U+N+TfcwR8bvJgGSZCsiT01tMKK6BDHAXFQosyKlXkcXTJD55YwXhIcSnLV+m1ZKnhMdEXwbr54uZZIvAFvA==,iv:srsQakG2c9AFE3MxtNKE6WXHWMpPfjF1bohoogKRHNw=,tag:Q/1ina0Krnud02I7jqw7tA==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:nYmA/VD7,iv:QPvOFHKXHvEjA2xa5eHMA4bkGuzMKP1LcFX0cxhrJgs=,tag:bBCSFFyfwOdhRgZIhjBoLQ==,type:str]
    oauth-config.json: ENC[AES256_GCM,data:Hajdeyay00E3AoNOguw05MzefeOz8hHn7By5CHj5HEaPqH4ShdkVYJ9Zohz93ZC/7VcGcRx65XNk8nRci05040pbYrW7UJgAHAWbFsrkb7JKIAeI1XoRyduGXCGTl95thv8akp4hFZSiKUniUcakql9ReDCLNAkSVGeFLWabj6W5kPKDFM4C+F4JmUo/noQ6lKnj/Su9ZSFDshMSOaueSwW9u0bDQwBUILK2lV1oePVgKrzW1lsIxtUgHVR57tKHxHf0eFoX+lAXJ5GmRqDERmSavhOU2hc3Y5y+jHXNyRnl0UZozGNH7Nk8q0WT6ZUb4chus9uOtUdu2S1pBlJYUWAOK1v+N4jgIztWhFPNfFeIUPUQgQZSk3tUUYo=,iv:CVd4mvzKiae3w9F9ErrsU/mXl4DfhKAJ/TVo2xiS49s=,tag:cLukpYMcFgrSYd6BGQue/A==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoRENxWFl2YzFGUFFvMXhl
            N3h2RnNqa24xUzlPSUYvZERNUDJkNW8vZmxjCnd4eFU4TkZqSWFTWmFtdCtnNzJH
            QURNeXRVVWJDbCtQQ1Y3Q1BxUWZiSk0KLS0tIEdHSXh6blpyZ25PbnYvaDUvSzdC
            MWpVbnA2VkZwZTl6dU1UbzVJb3VHdncKm4kNjlDY+wjzXd6XWVwLvEK4tDnPpEeS
            Xw18xqtaLAfmSAMinkl6YQjv7eSJP2b7bKdW3FAhLORR94rBlxaB4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-18T09:24:33Z"
    mac: ENC[AES256_GCM,data:GGAkDSopPs+L7XP6vLGwryG+AAmFIGQNvuWb5BZF/Uo47/Xeyhf1fV97TrMZFuis+BYBHIFxvejqTQ7n6D/xZioirsns/zo9bcP6uVpxxi8F+jAEIP2TZLi/j2YW7T4LI4nfVeipAmNzgwmQsi0SvN72mV7ti6R+7O0UCxCr+n8=,iv:1o+/Gy2W4zJIKYeICZ+7uPKEowhmQ9cCDPUNSruWdCU=,tag:EXKvgUdHNqleraFcgoNz2A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
