apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
type: Opaque
stringData:
    DB_HOSTNAME: ENC[AES256_GCM,data:vpeOQXUKv/KHDRG3tscEKrmwvEflm890pqNkfg3+97u9N4intIh80H9l,iv:5+kHc38YP/ym6PLnmobrhVdvy/BYU0AlukaHNjd98YM=,tag:WyNcR9QfQKT3YCk0DMbUVw==,type:str]
    DB_PORT: ENC[AES256_GCM,data:FLHjAA==,iv:yvM9pS4mxM16siF6gZkmjMWU/i4bbCy56bLXXZYUReM=,tag:U16ofhq1NVwxZ6BpfRWQ8w==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:iesfMgME,iv:OB7ILZ+JoqQuxD72sJiTW5KWQJMvdg2X8U3sOkYOxVU=,tag:d4iZFlD4/JWbeLQMBpHEGw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:vkF0XAgKQcWMO8flE4XA4OydH4zh5Gdwmk8JxbMwC9I=,iv:RvFIsgcqDqcxxMqwfCrS7N0lY30GaSuwS0Bvp1UxNLU=,tag:mhtZwmHt76nZDe4o6j8vXw==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:oB/xrIYJ,iv:OBCfgrWQqZo+iAmn0P/iNc62+2xhbtQmjl8i095s9wE=,tag:haZ0unCIw3fsr5IxxhaGkg==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSSWJwRlNJMEordlBNVGVo
            TmxFSVk2aUxrT1FaV1JDaHpQd2U2UVdDZTJvCmFncXRybHpTaDJXTWQ3RkZwUmx0
            YWltLzdIN09WdlZiWTBIT0tYWUE0WTQKLS0tIExxdzd3dXNtSkpONUIweHpkSUdJ
            Vy9UbmFBZzdpVUFZbDZGcXJDdmhkNlUKQ5jRonjyO9RmM3q/epBGzhDczLsO4Ulr
            bxvx8G36z+MfFkYhA6aOAazBAsw6mKZ1AuTA9/Jvonzauipecauaxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T09:55:10Z"
    mac: ENC[AES256_GCM,data:/4MJgu3KEUxanQhu44YJ8/CvsfAFfwQHun6VvQr48j3OUz1HwTDKniAvx31OcYkvNrhhvBIc+gdWoVCxr/V51DKhH573o9y0j+AfdGwCBUfeHOX1n0qM9xATyqJgxiN54JqsB5mERm5ba0Hi0iAmEd06m5iKFm1SUZaV2q3/egM=,iv:B/ajzeohv7qD5EPDPGT+Ztlihbo1PleCiQGwiN3Iq2Y=,tag:vYCGu+vYHTekTG2JT+wtFg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
