apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
type: Opaque
stringData:
    DB_HOSTNAME: ENC[AES256_GCM,data:cnyNzrYW1B/RJQzv7dBy7DRidk9pA8WbjKDdn+5TxAA5KaS15kVUB/FU,iv:mG4LSGMvWKUWtYUm0TPV/loEukTEFDqe9fdzpQN7mgo=,tag:8hvAH6Qa+8OQtt33L+jDxQ==,type:str]
    DB_PORT: ENC[AES256_GCM,data:hiaQmA==,iv:T3vBkbSF4f2Dqa5ytsCsX4apMx1EyJj7+m0UdyDnOQA=,tag:LuSGP+dJ4IBDHII+UZNIcQ==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:p1dWQ+FR,iv:YSCed01uSC2MohZJ5MLvNw8F+ug/YtXKOd54t05sByc=,tag:2Z5eT/bOetZXhsa+xg7Mkw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:I2fXxisOAfx5G6+NvLE+XCDLoG/hNQ6vmxUfK9n3Ylxjl6pVfIhFLHe6p8jvakkUUphsmUQna23m85hI1B0M0w==,iv:Xy7/lEVBVwwbfobjZLPHYZFrvbSXTNyiNXE0TRSd9V0=,tag:qxeG7qZuYZnI8IsMyPEpBg==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:oFRdaGcu,iv:55o88NKM0vQWVWYiFS7VAiNrYqUE4Ym5M0glQB6Gmc8=,tag:mlOFmHPoLkjwLpgxXqf15A==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UTJGUS9KanBuTFJnR1V5
            Zzhzdy9ZTXkwMjlDSHNhUjZYYTRGS3dnVkFFCjNNUFBxNURZdW9GNWp1TENpMVlq
            QXpiOEdUdXZaenB4UU01bkFOMmVVMEkKLS0tIDcrT1p6THBrQnBaQ2JpRXpGWEJJ
            aFBCT1Z4RjcwZlM4My9Dc1lUR1doK1kKMEbEbq2i5bGU1hACQYIa79UdWhRk3jBh
            Q6luXnmlZh6lCI8pVOnaBWZUHAyQk7UUugTjnzh+YnFEFPJd0EGBYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T18:52:32Z"
    mac: ENC[AES256_GCM,data:hYGIP7vTpqeGI3Xd2iZcJIOZGslPeZu5Sti8jPpwbIlHfQpZhrnBe+d1eqUnCPyYtKpqRjUtM764rzm/oh4zh3DU8vxIJWH5HCMcXces0z8i6KWr/Ddmf4bioy2jvX4T2XcwcPrG033nlsgurB5cfkIF/x6sRD2FZmh842dIGP4=,iv:fnmc9uQcImEHchhllQ7mLirmIt+/spqT7mSKShDycis=,tag:TMdRBAt4jRycYNMyVV0TeQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
