---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "${BOOTSTRAP_TIMEZONE}"
  KUBE_VIP_ADDR: "${BOOTSTRAP_KUBE_VIP_ADDR}"
  METALLB_LB_RANGE: "${BOOTSTRAP_METALLB_LB_RANGE}"
  GATEWAY_EXTERNAL_ADDR: "${BOOTSTRAP_GATEWAY_EXTERNAL_ADDR}"
  GATEWAY_INTERNAL_ADDR: "${BOOTSTRAP_GATEWAY_INTERNAL_ADDR}"
