apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-secret
    namespace: forgejo
type: Opaque
stringData:
    #ENC[AES256_GCM,data:L1xkO1B6YGvOmms0F9TzQxWOdC67q+sXu6gsIbB8E8QgaJiPkStKXALbcPeOTDBiUg==,iv:9KO3j/OGbEHZQezP0g2tJYucf4eKWtxThoznl2yWmUM=,tag:MnY+WNYDtIqujSEr89PItQ==,type:comment]
    #ENC[AES256_GCM,data:UDmGRk6GdgIDHmR3jyZPIknlfv2eLyoIVpgZhkqy+hxH4WJwmqLJGQoLpEYcq5yl+uVeztyWER9u6oe2zM7h9g==,iv:0aMEknb7N+UlrvmiDbX8O5ZXlxYU9PpOV9uQVx5xA58=,tag:0pK4CRbkU1iC83aSB3zBSw==,type:comment]
    #ENC[AES256_GCM,data:VwaEUqXqFAh41vW26/2V1HUWWtoeWd80Z6lFFmSR2VK8JX/36IsXNa+17A==,iv:FRnIZSIycdyEKPaKPLQcmE0EuoTYaPDSAP7fc+5PIPE=,tag:fthIzystvjZSqB6vGdt0Pg==,type:comment]
    token: ENC[AES256_GCM,data:ld2JQ8L06foYlCo3lQ2hvoRn1V0UIGtzvyDOeMsiJLg3yGjLdIVPz/cz8A==,iv:Y5O8Ohd5kzP2BWYudTQhaaJue3lyn1+9bSEBH4WxJ/w=,tag:AZeJJNuc/qGAMOLUfiVVEA==,type:str]
    uuid: ENC[AES256_GCM,data:lxbVK253ULkMu1Mn+8PX9BkpTcXvhNRsdU7UvG7NaYT8wxbW,iv:pvew0+hzyj22D0blN360+WGpcNMkLdL2428TRYJvpMA=,tag:yO+V66966RxVSbjufczqKg==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrRlNwWjNBRk5YVnEyaEFQ
            UDAwSXdpVTJ2S01sMTEvTW9kQzdsU2Q4QUhNCm51WVZsN0tSdW1yYWR5bnlpZkRJ
            Sk53c2tpa2cvNkx5cWY4SjZ3WklFLzgKLS0tIHFoQ3ArZlVwdFczSTk5VXR0bDRp
            TDdRQjJ3TXJlbkdrVXI2Q1AvY1VHeTAKXcGm0BUVrAqHjzJRyMhGnARoLWOlbX7s
            FbFEkxDMMSalRQf2qNPguP4UtSFHCTJ73tgBXKYM6WjuqZS6X+KdKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-07T20:19:10Z"
    mac: ENC[AES256_GCM,data:I+8fiY7yYBUwuRB4/yQy5meC8H1X8Ke6Igz49NOvPrHvUfaMK9a48U4vUxnVIIKCCn3Tf02BrdB0or3cmIne4aPiUJM4Z5k+AMAQFULOgwqBXyu8+wYmf+e6w1Ps0xgjUorYXuMZjDX11NL8GtivktCnmLJOPy1tCh+vVEognik=,iv:01lh5NzIK3/pnBZ1pp+T5BbFGH5XJZgRDIz9WbJTG8c=,tag:GIe6tS34Eey5l2KBlNMr5g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
