apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-secret
    namespace: forgejo
type: Opaque
stringData:
    #ENC[AES256_GCM,data:H76Uu3n1sYOe6oqytRJcOLXf6A3eLAf/3ga/9cqToGsmF2LinNQTjo7GUDxclQ7oEg==,iv:GmkBDG0ffQRC7bxBymgP8F0V4rnM5gEdbY3tkfs/LfE=,tag:377Va5oIKiRqeASxw9NoOg==,type:comment]
    #ENC[AES256_GCM,data:8j2HJrhz6Y1+1AvVfuRKe0n45+e3EpMzn9LM40VJLTwIm4vEnTw3bRF240zsKxTsjzGI893MAdpZKd6rIrBZiw==,iv:J+Rn00JXn9WJ/ChdhEImvzlDWPUTHEe9vYxy+NfJdyU=,tag:rypWHGo5Y3EoQ/psdY8keQ==,type:comment]
    #ENC[AES256_GCM,data:9EV6GzdN3JkRAxeMRVmO0x4q4R173ILrnGmGl6Ln5cxvf4pdLgSSsgnj+A==,iv:eL6KI73eD4E+piBgzu+Xkox0QaBSfnt97aJPXapHySc=,tag:d7lLLS6pq5bO36e9DfJ4Bg==,type:comment]
    token: ENC[AES256_GCM,data:NrrAkrRM51iQcYrJj4p+wdWeKlUfguvgFzR+kv34yFlhqby0Nrekvw==,iv:bc47BimqhFpgGSsMSvbgQZZBasz7YblpFezJBlw+0vU=,tag:1PVwoo+K4AcgH4yxi1yVIg==,type:str]
    uuid: ENC[AES256_GCM,data:vTqvQwtm3quLWncdDg8gt15aF+AunNpVSQvo4x+htFBc66sU,iv:CVBG4/PdV67UVJjNq02zHs9/9HuiU5JrczJjP0mzeUg=,tag:igE785BoGen1vWNo6X/SDw==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UVJYaEYzTnBnazMvNWlw
            UlduTHU0U3lRU1BBdFpYWmFMekc5Q3Qvcm5rCmdnN1VlUS9mc3JOR2NBdjJSL3dm
            aWltd2MzZzlmL0c4bXltTkhCYU5waVkKLS0tIEkrb2RZN2VqWVlTK3MwejJpUVVV
            UW5yWGliUk5NcE9JT0VwT0VCRng4dm8KSV4RxorZZpobOzBmBnu+y6RopsqXGIA8
            74MAeFu04VA3aJoiJ8WPJkcpOB/tgQvP4zsVzxsdrnFpIZYzTtnFjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-08T05:41:06Z"
    mac: ENC[AES256_GCM,data:JQrcT1awnCms0zKIvqQdcosMtnGnJ9i6SY0V2ObcXS1vobtEphlWcJ5FBUqGjOp5FU98ZmDlhbAKPMCvMiJlDhDYNoq1oFCuY35q3csmFN+2Mz0RIjyVpaNJ4S6SvUgXSmIhPhsTLLUvZdrNoXucLhaW6SnMKdI0Rak1dLIjwOU=,iv:6mipbi4YKKJgac0Jwi54Zpi9WzlAYNZwDgQ3IiGIN/U=,tag:35mbC9SOy4c8ZYI+VfONHA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
