apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-secret
    namespace: forgejo
type: Opaque
stringData:
    #ENC[AES256_GCM,data:L1xkO1B6YGvOmms0F9TzQxWOdC67q+sXu6gsIbB8E8QgaJiPkStKXALbcPeOTDBiUg==,iv:9KO3j/OGbEHZQezP0g2tJYucf4eKWtxThoznl2yWmUM=,tag:MnY+WNYDtIqujSEr89PItQ==,type:comment]
    #ENC[AES256_GCM,data:UDmGRk6GdgIDHmR3jyZPIknlfv2eLyoIVpgZhkqy+hxH4WJwmqLJGQoLpEYcq5yl+uVeztyWER9u6oe2zM7h9g==,iv:0aMEknb7N+UlrvmiDbX8O5ZXlxYU9PpOV9uQVx5xA58=,tag:0pK4CRbkU1iC83aSB3zBSw==,type:comment]
    #ENC[AES256_GCM,data:VwaEUqXqFAh41vW26/2V1HUWWtoeWd80Z6lFFmSR2VK8JX/36IsXNa+17A==,iv:FRnIZSIycdyEKPaKPLQcmE0EuoTYaPDSAP7fc+5PIPE=,tag:fthIzystvjZSqB6vGdt0Pg==,type:comment]
    token: ENC[AES256_GCM,data:omEuoC5MWLzlDNrC2X0S4g==,iv:OnZg0umAEkm0kYEE1CLaWxnFvl8n59W34VzAON6mw98=,tag:sT5YFixfWkoNoIXl7jBq+g==,type:str]
    uuid: ENC[AES256_GCM,data:YyTKwo6xRJfrxrXkEC3l,iv:mn65ikh1JyHsLwgoZEkN32R+ep0vFFCKX5r0LOgiq68=,tag:HTom08EVC5IB/H1AHWXPqg==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrRlNwWjNBRk5YVnEyaEFQ
            UDAwSXdpVTJ2S01sMTEvTW9kQzdsU2Q4QUhNCm51WVZsN0tSdW1yYWR5bnlpZkRJ
            Sk53c2tpa2cvNkx5cWY4SjZ3WklFLzgKLS0tIHFoQ3ArZlVwdFczSTk5VXR0bDRp
            TDdRQjJ3TXJlbkdrVXI2Q1AvY1VHeTAKXcGm0BUVrAqHjzJRyMhGnARoLWOlbX7s
            FbFEkxDMMSalRQf2qNPguP4UtSFHCTJ73tgBXKYM6WjuqZS6X+KdKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-07T15:24:16Z"
    mac: ENC[AES256_GCM,data:BgQkI1mw7JIafSHeevFWr1oL0yhwA8xrn3CnP304frPZdBrsGVXq8CdVI3qZnxlpyiB5HNK/9TATaRK+6++xW0oa2+UNrzKPzFo5ZOX+juvgVrjTvGhG1fx308zjff4mboLJaYzXSSkzjIPpJyCgadK9aWqolzMoAWiZIYp0jKk=,iv:Q2Bk9ufijcUsp5RY7tLmEPZMa2oP9eY2+EDbywfuq5M=,tag:cyJHXiyMiK0OqNRXEN5EhQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
