apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secret
    namespace: forgejo
type: Opaque
stringData:
    #ENC[AES256_GCM,data:+hB1D1mm3d2/WdqFqxXt9ZeFkCVb5OZ3NvZ2dZ46gEEpitAu+IpzA7LGgyCS+eR8diIqLQs3MRw=,iv:JlG+G9Zj3it1R9ealXdgsVv6Tzil+R6fYAAllTpKAxQ=,tag:/4KvJBDbB7EK6uJbNnfuQw==,type:comment]
    username: ENC[AES256_GCM,data:7Hm57T1JJPkRECK21A==,iv:GhIv5rF1yFE5Ly6W2wccwew1wJgf/u165NN1MINsY4M=,tag:hSqFYx/kK4OHE/cDw0vtSA==,type:str]
    password: ENC[AES256_GCM,data:G9YsnnTYOnjzbCpOP161RFv86k8Q7HRmzWzI6Kbv,iv:zaeoRN9EmKZ2lxYxIJ2meuZ2CsA/v5IwIsCwYs7ITp8=,tag:iJJ8jQKojiItUy1ndMvsGQ==,type:str]
    #ENC[AES256_GCM,data:Lgims50d/MZ3RZze/2gzwH7hK3rMVg3Y1vMZwIfrCDAksKCKNwaQUF6Ui3Dy8Eq7CBXCgZ5er30yIL80oNJm2CAc9eDplusmsTI=,iv:tJGwkQ8RUmqM8F4DW3i+O77VOdFt7KV1zpZD2RP3Tpw=,tag:3v0QDPvEByKyaSWzNeYlHg==,type:comment]
    #ENC[AES256_GCM,data:trRrVnsufzypOxNMToMGBB/bwU5iZeY1g56gpYytBL9s0TOs8H1sLTzMKXr2zSdbRaRaJdBAH2C23vA6r5/LB4WoutK1Ww7cTveU,iv:x9d5sofKwyUxyZrRn8ZDPNYccCd4wdSFKioWePYUn9E=,tag:amCH1bIalk/5wgn2T5HHXg==,type:comment]
    GITEA__database__PASSWD: ENC[AES256_GCM,data:th82UDvn/NDKLo0vRE9s,iv:lsAkfw4fVjgXbKS4ndqJb5iRr6HTSZPnseMi0TZP0Z0=,tag:D+uGuWWwblL2j9o+jV34jQ==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3b2xPOTBiSHduL00yWmph
            ZkV0T1ZwUHltdjZlQUFOWWtaUTFBVFNoVUM0CmdwTG92bVM0RCtEaXhZNUpqYjIx
            ckFEWFpGQkZyZkszMlk4MzhiRFRyTzQKLS0tIE5kZHozRDMrUkRPY3kyZ1I1dzB3
            dCtrNTlIazBId0UyY05MTCtZT1graFEKNILB1UlObwSWxBC/IauUFeGSq/IgoqTz
            HFUBmnXBmtBPa7pjRcOf2ybZLbmgMCLNHk9rzbTFbkSBQSt//npB5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-07T15:23:26Z"
    mac: ENC[AES256_GCM,data:MyDDRK0FwmxLTKbQ6lKLGweZKVdqGxKdlRJpwStrw35sMz6gTY+7cF9cNYWhcTsQCGKB+tznA7uErjJnJ4I3fFtIQSjHkxuYaLyv8aJdnQItuMZ3uSFGzJotfwV3Tnoq39CgANOCAi6nAZ2jLww7YNH6OjpwTWLh0c514tUp4Q0=,iv:wxVa2wqDDmLSFZ8aH2XAEG0S+nLLOgDR00G+MNFhDz0=,tag:GSChjo1D/2VnbcEBGAYI3w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
