apiVersion: v1
kind: Secret
metadata:
    name: hoodik-secret
    namespace: default
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:5/QesJCJCkCSzz/AsuQOY5kcoIas1N41KngB14vLoQ9P3JIn/MaMJ2CVbEkB/W818P4NKIBhiu9qInfq3ZA8Ol9ecjoUANO1WmSXluqKl44EScX+VKVBe2rSPanMr8vNmBouTkT+A+Arqgjj2W2Gvv21,iv:AJQLXwuEDecDIAsk4d1EoIk2TqmIQ2QELKGFuLezCNE=,tag:UMBBmGSF2oZpT4kUE+YM7A==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:xSWpy79k,iv:DN8jlnFmzS7ISHeBOmYyzkdLNe0RLJ3kuw9hCr/jzNE=,tag:Ie0JtfdnP0JfEyfsHF5sDw==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:z2uVMMuCH66wQajkvl30BuU9a0fFuHk6EG+3kfpXAIajMSqyvwlJPA==,iv:gmWdHA4PELaYabds5+HMthGtwiAd7d1XlV4ZnQSW6TA=,tag:T/L8llSPv8m7YW9RID/Fwg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:jhzVIRldZP+vpX/XhviSAAIUPGPqHDrGkWWA+hzEh7O/aDromCrjDSxiPjTTuJ5HAXlvKTgnsOaomz3mk8o=,iv:Ka+17VGbu6wIScsKti/SiNLi9KKAVQMu1nEiYDSKae4=,tag:Ov72QiVyIROanOJYu2Z80w==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:hRpVKkPOPN9AivWUMuVvEkVRdvwRweV1BIA7OtoQudMJE5pL,iv:JqnTrrdyw5CuA3GOayas5tdb/205NHJX+icke2W0QEk=,tag:KlLHtGugJnqjx/IiqT1X4g==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRcW9CZmhxNUNxZHdMR2ZY
            dmNvU3FoRGd4cS9POCsxa1Q4dmc4UmYrWVhrClRmWUFReUozZHlaWTZObHJDWEVK
            N1R2OGpuNGpzMzlTTGVaL0JDN3RreFUKLS0tIE9SbjlnZmdZUTlYcUw3KzRNUFJy
            YnVHbTJPU1JhMmhudXhvUnhtM0YzdjAKRthdaNuHXEDvWbKjehTRvUWOYuM053kI
            Xna0KQ9FcjF1NkBilxGCOqnesLnmdvWfB1t9IWkFH3kKjRZ9jgClSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-18T00:16:41Z"
    mac: ENC[AES256_GCM,data:TkQLFXi/eg3WFraEmaBOf9RMvglLSr5l75JR8iUlHkOkOSN+Vswn1rfZzG86pCYS5cWwY+Hkw+Kr4aiHk9m+jk4b6oXfl4tk6rQwwmw/3lM23HHxv1mXTmZCgFnszuMjINnDuIF8xS7HrmMD8M9IniWivgXu4grJes5mbc15+tk=,iv:7btLGX6KQcpidQ7TbBS9AfjG0SzYPRJH/DBJspfOKss=,tag:rE3C0i1DFI38yrEQTDP3dw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
