apiVersion: v1
kind: Secret
metadata:
    name: hoodik-secret
    namespace: default
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:TVwM0wAvLVUJ8vMqaIdUU0y2ccyiHwkhPTQ7wDLli7z+pXaPyD6vrIen4p/aETsuWufqI00QswaAmCVerDUOq0BkYzaitBx2Uw/eJ7kx/YT1k63Wfv5qOLVm2vd/pTSeAUt99AXKR+oedj9rlNJsiTf2,iv:9dmc8ckaFXilV6gIjZ2KQuD5QNbwNfjhN89D81Yfcyc=,tag:s0J0SoT0PqmQFEJlyULJGA==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:Ak6VP2DZ,iv:yVNbWatatkAZUKmbBONwOTFDqjSWrD32gIZ+USiwUKA=,tag:xFpdBTWTrrBLHjysRQq21Q==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:nZTLMXf9iuOc9Gyt2NSaNPZOj6taTGr/+GhD07nSi+MeAB6TQ/7gnw==,iv:GexhmKTOnOl9UgPWSNJAKvnzeSh/YfUu2FfYd8PAm6E=,tag:zIiawTUAGsZKn0lYKofH7A==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:t/vqRwx9F+m/JSFSnRrz60amgejBHtFmKirHGRFUjimAb0IiTStC/VlOm4KYXc5ZSAVqHCJikoM21r+9gHg=,iv:XrqKn/Af1Clxn/XVlE896jbcExCwRfs65WlBe79XbQ4=,tag:uEP4BQirRALcKdgIt1Rn+g==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWWVHbC9ram1lbDVWYWd1
            TmdocGI5T0JBNnUwNEQzdGJZNU5tN29ydENVCmM5NmlqVDZpbzE3eFRPL2ZlWTl4
            Wit1YWNuTG5iTkdVejhtQ3h5c2NxalkKLS0tIE9hbC94QTkwdWl2bkx0dnl5Qk9h
            VEw0R1cvTXZVKzVSSTVMTHJFMXp3ZTAK0Aud+/BY5ia5hYgBdB5PSdWWKMUojPtE
            WRvNz+2ttjj/QoDrLSXor8mptwX9nTW//qCU4dGT3oEMqJnG4935TQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T15:58:24Z"
    mac: ENC[AES256_GCM,data:EsJYMQvm/D1sFws/F2f1N5XUzoAnKpv9zQ2h6IKc2JLUFQDp6+rxtb28OsPPBo7Xg1YXB58ae0UgKLkWO0RZMDz6f3o7XK1RJQRZtOBw+Ydf5373b24KmT7uYtR7S2EyeP7de/0W0q/e95TMr544e94Netl1kBhCsiAqlaTeEoU=,iv:/u3iQ0jWjr4RIDWQYCd4UAOAf0GLZ5KiBz4+iLU7jMg=,tag:AxBSMaDBGftqbgWzXD5byw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
