apiVersion: v1
kind: Secret
metadata:
    name: ocis-secret
    namespace: default
type: Opaque
stringData:
    OCIS_JWT_SECRET: ENC[AES256_GCM,data:NOMLeWwzTD93EHnec0oRdTc0hvdpt8eXanHmJKfJw1M=,iv:MMxTVVY9gruo56DYBH1+6hWtF+zlrUgsKRp2eFD1nik=,tag:k4JYxOsaLe38j2mDxI+KrA==,type:str]
sops:
    age:
        - recipient: age1w02zzfg0y4ast9mgnd9w0yuym0wqx6q967kmrmq355w4cnw0xytq2x369r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXR0szM3AvMUdPb1B4M1k3
            UXd4UFVBb0hkYnBRUUNCNUpjWEpoQ1ExS0ZFCjVHVnJoOXdWMjNPTlR5b1hIeGxZ
            UmpHcU9Mc1VBNzJGWW5yeE5rUzBZTm8KLS0tIE1Bam95SjNBOERZMjRUZVVmSDln
            UkU1d2ZWemlTU0puNWJydXJKaTRCeVUKUFc0Ok8VCeerRtf3CgkECJIQKaZ3RUwE
            NSx75xJExaJDMelxr4gfQa+Cl7A0oTrxIpaK4RExuTVwkjVTQFEKrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-02T22:27:53Z"
    mac: ENC[AES256_GCM,data:PG1jHAuCjl/oY+aWPBDfcnoBizzHh2mRX4G0xMYl7A/GQdsgXw8Oh3YtzReb+0mbnA6DDmwaLXjQeFx24wbqe63srCCYOQbA03SsY7UprcUM+GhlA+nya4dpjFfhvPemdkU4crb/5cMHQ/TtTon/5o/nasVBqzCKZMMAdRU7xGE=,iv:UEtYjWWOIMTLvFNbzw7+F5spFtvvZnpNMPaS8eVTdSQ=,tag:Al3zCGldM/qxnent1SMNtA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
