---
name: "Ansible Validate"

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
    paths:
      - "ansible/**"
      - "ansible.cfg"
      - ".ansible-lint"
      - ".github/workflows/ansible-validate.yaml"

jobs:
  ansible-validate:
    name: Ansible Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.14"
          cache: "pip"
          cache-dependency-path: ansible/ci-requirements.txt

      - name: Install ansible-lint
        run: pip install -r ansible/ci-requirements.txt

      - name: Cache Ansible Galaxy collections and roles
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            ~/.ansible/collections
            ~/.ansible/roles
          key: ansible-galaxy-${{ runner.os }}-${{ hashFiles('ansible/requirements.yml') }}
          restore-keys: |
            ansible-galaxy-${{ runner.os }}-

      - name: Install Galaxy collections and roles
        run: ansible-galaxy install -r ansible/requirements.yml

      - name: Run ansible-lint
        run: ansible-lint ansible/
