---
name: "Kubeconform"

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
    paths: ["kubernetes/**"]

env:
  KUBERNETES_DIR: ./kubernetes

jobs:
  kubeconform:
    name: Kubeconform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Kube Tools
        uses: yokawasa/action-setup-kube-tools@e9417d7e5e0ad29e33ea603f98cddbb46bdb6bcd # v0.13.2
        with:
          setup-tools: |
            kubectl
            kubeconform
            kustomize

      - name: Run kubeconform
        run: |
          bash ./.github/scripts/kubeconform.sh ${{ env.KUBERNETES_DIR }}
