---
- name: Packages | Ensure required packages
  ansible.builtin.import_tasks: opkg-packages.yml
  when: opkg_packages is defined and opkg_packages | length > 0

- name: DHCP | Apply static reservations
  ansible.builtin.import_tasks: dhcp-reservations.yml
  when: dhcp_reservations is defined and dhcp_reservations | length > 0

- name: DNS | Apply hostname bindings
  ansible.builtin.import_tasks: dns-hostnames.yml
  when: dhcp_reservations is defined and dhcp_reservations | length > 0

- name: DNS | Apply dnsmasq address overrides
  ansible.builtin.import_tasks: dns-address-overrides.yml
  when: dns_address_overrides is defined and dns_address_overrides | length > 0
