---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app adguard
  namespace: networking
spec:
  interval: 10m0s
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: adguard/adguardhome
      tag: v0.107.34@sha256:66ba87dddfddbb37ee0dcb988a174704ac71b5096607e3767b327570985ea48e
    env:
      TZ: "${TIMEZONE}"
    service:
      main:
        primary: true
        ports:
          http:
            port: 80
      dns:
        enabled: true
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/loadBalancerIPs: "${ADGUARD_ADDR}"
        ports:
          dns-tcp:
            enabled: true
            port: 53
            protocol: TCP
            targetPort: 53
          dns-udp:
            enabled: true
            port: 53
            protocol: UDP
            targetPort: 53
    persistence:
      config:
        enabled: true
        type: pvc
        storageClass: longhorn
        size: 1Gi
        retain: true
        subPath:
          - path: conf
            mountPath: /opt/adguardhome/conf
          - path: data
            mountPath: /opt/adguardhome/work
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "shield-check"
          nginx.ingress.kubernetes.io/whitelist-source-range: |
            10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
          nginx.ingress.kubernetes.io/configuration-snippet: |
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/adguard/overseerr.css"></head>';
            sub_filter_once on;
        hosts:
          - host: &host "adguard.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
