---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./kopia/ks.yaml
  - ./longhorn/ks.yaml
  - ./snapshot-controller/ks.yaml
  - ./versitygw/ks.yaml
